### ISSUE TITLE
Barrel Conveyances - Create New Barrel Conveyance displays loading bar

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#1]
When creating a new barrel conveyance, after clicking the "Select Conveyance pipe from Map" button, the app displays a Loading bar (identified with arrrow in the screenshot).  The loading bar is behind the Barrel Conveyance window; cannot determine what the bar is for.  The user can continue with the workflow.

![image](https://cloud.githubusercontent.com/assets/4103847/12593559/adee0a0a-c43f-11e5-8ca7-975cb1d26641.png)

**Comment by kanglu666** [comment]
this loading bar is meaning the Barrel conveyance form is disabled and waiting user to select pipe. 
it will not affect current work flow.
