### ISSUE TITLE
WQI Inspected Structure Button Not Functioning

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#10]
For the WQ Investigation, the Inspected Structure button is not allowing you to select a structure nor is the field allowing for manual input of the Inspected Structure #. 

![image](https://cloud.githubusercontent.com/assets/16919958/12678743/50c7d082-c66e-11e5-8fe5-432567850753.png)

**Comment by kanglu666** [comment]
confirm that: 
1: change Inspected Structure # to Inspected Feature #.
2: add another field called Inspected Feature Type (structure, pid point and conveyance) to drive the identify layer.

**Comment by leeensminger** [comment]
@kanglu666 pending discussion on Tuesday

**Comment by leeensminger** [comment]
This field will be removed.

**Comment by kanglu666** [comment]
UI updated.

**Comment by kanglu666** [comment]
ready for testing in next release
