### ISSUE TITLE
Component Measurements

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#100]
Measurement fields default to 0 and the user has to manually delete each value before entering a new one. Is there a way for the 0's to automatically delete when the user clicks in the box or at least be highlighted so the user can easily type over it.

![image](https://cloud.githubusercontent.com/assets/16919958/13017636/2cdadd1a-d193-11e5-96c1-6a58c575e5d0.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1 release

**Comment by cstevenson1** [comment]
Works appropriately for component measurements but would also like the 0 highlighted when you click in the box for Width in the Conveyance Inventory Form to make deleting easier. 

![image](https://cloud.githubusercontent.com/assets/16919898/16744517/86d8770c-477f-11e6-89a2-5245a3840c27.png)

**Comment by mjuber-kci** [comment]
Additionally, can the 0s highlight when you click in the boxes on page 4 of the WQ Investigation.

![image](https://cloud.githubusercontent.com/assets/16919958/18685646/f9f55f12-7f46-11e6-9b99-d290558cb2e6.png)

**Comment by cstevenson1** [comment]
Fixed for conveyances and shouldn't be applicable for WQI once #358 is addressed
