### ISSUE TITLE
Need ability to Modify Geometry 

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#102]
I could not locate a button within the field tool to modify the position of an existing point. 

![image](https://cloud.githubusercontent.com/assets/16919898/13018377/2bd484da-d197-11e5-87cb-4e35b53279cb.png)

**Comment by kanglu666** [comment]
Do we ONLY need function to updated existing Structure Feature's geometry? or we need to update other features' (BMP (polygon), PID Point ) geometry.
We need to discuss this item.

**Comment by leeensminger** [comment]
All existing geometry (structures, conveyances, BMPs) need functionality to be edited and updated.

**Comment by kanglu666** [comment]
ready for testing in next release

**Comment by cstevenson1** [comment]
Modify Geometry is now functional for existing structures but does not work for new structures, even after hitting save. The message below appears when you try to modify geometry on a new structure. We have this ability in the existing field tool and would like to keep it if possible since it is a used feature.

![image](https://cloud.githubusercontent.com/assets/16919898/13929107/e754fe66-ef6e-11e5-9323-fcc8c8a2eb88.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by mjuber-kci** [comment]
We are able to move the structures location, however, should connected conveyances move with the structure?

![image](https://cloud.githubusercontent.com/assets/16919958/15362160/47bbba4c-1ce2-11e6-91ac-82210fe2397c.png)

**Comment by cstevenson1** [comment]
As Melissa showed above, connected conveyances do not automatically move/re-snap when the geometry is modified for the upstream or downstream node.

**Comment by leeensminger** [comment]
See #242.  Closing this issue.
