### ISSUE TITLE
BMP Inspection Tab Enhancment

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#103]
Can we have a small box attached the BMP Inspection Tab with all of the parameters listed.  If you double click on the parameter it will automatically take you to the parameter box so you can fill out the inspection for that parameter.  All paramters that are not selected in the inventory tab can be grayed out in this box.  If you have to scroll through all 24 parameters just to get to one you need to edit seems a bit cumbersome.

![bmp inspection enhancement](https://cloud.githubusercontent.com/assets/16919984/13018442/875100e0-d197-11e5-9a6c-672ee0f8ee53.JPG)

**Comment by cstevenson1** [comment]
minimal value, closing bug
