### ISSUE TITLE
BMP Inventory Tab Misspellings

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#104]
Please make sure the following parameters have the correct spelling/capitalization:

Riser - Low Flow
Upstream Embankment Cover
Downstream Embankment Cover

![bmp parameters spelling corrections](https://cloud.githubusercontent.com/assets/16919984/13018554/2da014fe-d198-11e5-8249-dc3bc1cdeeaf.JPG)

Thanks!

**Comment by kanglu666** [comment]
updated
