### ISSUE TITLE
Error Pops up when selecting for upstream and downstream structures

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#105]
The following error message pops up when the + icon to select a downstream or upstream structure for a new conveyance is clicked more than once.

![image](https://cloud.githubusercontent.com/assets/16919958/13018578/4d93899e-d198-11e5-87b3-1e9aafa66aba.png)

**Comment by kanglu666** [comment]
updated, once user click the button, the button will be disabled until the identify structure work flow is done. then it will be enabled again.

**Comment by leeensminger** [comment]
@kanglu666 , should this be labeled "fixed will be ready for testing..."?  Please update.
