### ISSUE TITLE
Last Edit Device should not be KCI

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#106]
For a PID Point there is a field name Last Edit Device that appears to be filling in the firm instead of the device. The field is not editable and automatically fills in with KCI.

![image](https://cloud.githubusercontent.com/assets/16919898/13018732/62b26c9a-d199-11e5-9580-f83204db7f9b.png)

**Comment by leeensminger** [comment]
related to #108

**Comment by kanglu666** [comment]
updated, Last Edit Device will be current machine name.
ready for testing in next release
