### ISSUE TITLE
GPS Baud Rate Options

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#107]
There is a problem with our new Trimble Pro 6T GPS units staying connected to our current application.  One of the recommendations the manufacture told us to try was to increase the baud rate to 38400.  We were able to do this in the Trimble GPS controller but were not able to set the existing application to accept this speed because the baud rate selected was hard coded into the application.  Can we have the following baud rate options:

Desired Baud Rate Options:

![wanted baud rate](https://cloud.githubusercontent.com/assets/16919984/13018862/25e9a0de-d19a-11e5-974f-16593dbd825e.JPG)

What is proposed in the New Application:

![baud rate](https://cloud.githubusercontent.com/assets/16919984/13018878/3811aa18-d19a-11e5-9ca8-693ae2c3df98.JPG)

**Comment by leeensminger** [comment]
@kanglu666 , we discussed adding the baud rate to the Config file, that could be updated by field crews as needed.  Can we simply list more options in the GPS tab, as Matt shows above?  Instead of the current 4800 and 9600, can we add more values to the list and allow users to update from here?

**Comment by kanglu666** [comment]
updated, Baud Rate options have been added in the config file, user will be able to update it. 
ready for testing in next release

**Comment by mortynsky** [comment]
This issue has been fixed!
