### ISSUE TITLE
Create Date, Last Edit Date, and Last Edit Device

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#108]
All Structure Types, Conveyance Types and BMPs should have fields for Create Date, Last Edit Date, and Last Edit Device. These fields are currently only visible on select structure types. On these select structure types there is a Last Edit By field which is not needed and should instead be Last Edit Device

![image](https://cloud.githubusercontent.com/assets/16919958/13019370/05c49658-d19d-11e5-8686-504ccf1c5ed6.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
