### ISSUE TITLE
PID Points - UI Supports association to WQ Investigations, but shouldn't

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#109]
The UI in the Create New PID Point allows users to generate WQ Investigations from PID Points.  Didn't we discuss that users will not be creating/associating WQ Investigations from PID Points?  This tab should be removed.

![image](https://cloud.githubusercontent.com/assets/4103847/13033855/2b8447d8-d2f3-11e5-84f6-9049e4500c47.png)

**Comment by mjuber-kci** [comment]
WQ Investigations Tab should remain in the PID Point. The PID point was created for the purpose of being able to generate a WQ Investigation outside of a stormwater structure. This is the case when a PID is not directly associated with a structure (i.e. oil spill in the curb).

**Comment by leeensminger** [comment]
Confirmed not a bug.
