### ISSUE TITLE
New structures do not default to the first page of the form

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#11]
When creating additional new structures, the form does not default to the first page of the tab.

**Comment by leeensminger** [comment]
Marking this as a bug.  Please update the UI to display the first page for new features.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
The field tool defaults to the first tab (Location tab) when creating a new structure but does not default to the first page within that tab (example below shows it starting off on page 2 of 2).

![image](https://cloud.githubusercontent.com/assets/16919898/13853711/57ad814e-ec3e-11e5-9d5a-d8eb4cdf57b2.png)

![image](https://cloud.githubusercontent.com/assets/16919898/13853718/61dfde8c-ec3e-11e5-9f95-0f3ad0ade2fc.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Location tab now defaults to page 1. Inventory, Work Orders, Inspection, and WQ Investigation tabs do not. They appear to start on the page that you last visited in that tab for the previous structure. 

Example: I created a work order and finished on the last page (page 5), then saved and exited out of the work order. The next work order I created, started me on page 5 of 5.

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1 release
