### ISSUE TITLE
Structure Inventory -  Outfall Inventory - Outfall Material label display is cut off.

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#112]
The labels "Material" on page 3/3, Structure Inventory (Outfalls) is not displayed correctly.

![image](https://cloud.githubusercontent.com/assets/4103847/13732178/888e9fbc-e952-11e5-9e02-2aa26e56dd35.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
