### ISSUE TITLE
Material Domain under the Inventory Tab for a Structure

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#113]
"Materia" should be spelled, "Material".  "Rip Rap" in the domain dropdown should be spelled, "Riprap".

![inventory material](https://cloud.githubusercontent.com/assets/16919984/13757018/f891912e-e9f8-11e5-810e-c87ddf01d996.JPG)

**Comment by leeensminger** [comment]
Domain value updated to Riprap. @kanglu666 please update Material label

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by mortynsky** [comment]
This issue has been fixed!
