### ISSUE TITLE
Misspelling of the Title of the Shortcut of the Application

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#114]
The Shortcut to the application should be titled, "DelDOT Field Tool"

![spelling of app](https://cloud.githubusercontent.com/assets/16919984/13792390/03032558-eac8-11e5-9419-247f2c07edf4.jpg)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by mortynsky** [comment]
This issue has been fixed!
