### ISSUE TITLE
Warning misspelled in pop up box for creating point outside work area

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#116]
![image](https://cloud.githubusercontent.com/assets/16919898/13847049/8c766cdc-ec21-11e5-9bf9-570f40f83b3d.png)

Warning is misspelling at the top of the box. Also, can we make the message a little more user friendly, such as saying work area instead of replica extent?

**Comment by kanglu666** [comment]
"Warnig" misspelling is updated

**Comment by leeensminger** [comment]
@kanglu666 Is the term "replica extent" updated to = "work area"?  If yes assign back to me with updated label.

**Comment by kanglu666** [comment]
updated, ready for testing in verison 1.0 release
