### ISSUE TITLE
Structures is misspelled in pop up message

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#117]
![image](https://cloud.githubusercontent.com/assets/16919898/13847334/191bf3d6-ec23-11e5-86b2-ae22580f0bf8.png)

Structures is misspelled in the notification box that pops up when I tried to add a conveyance and did not click close enough to the point I was going to use as the upstream structure.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
