### ISSUE TITLE
Address Overlay not functioning properly

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#118]
I added a structure at the intersection of E Green Valley Circle and E Green Valley Circle, however when the address overlay is preformed it is generating an address of "0 OFF SPRING LAKE DR". Spring Lake Drive is not even close to the structure.

![image](https://cloud.githubusercontent.com/assets/16919958/13847355/3812376e-ec23-11e5-8265-2fa527f7d10a.png)

![image](https://cloud.githubusercontent.com/assets/16919958/13847397/7212c4ce-ec23-11e5-96ab-1827ff3d941c.png)

**Comment by leeensminger** [comment]
@kanglu666 I found this to be true.  Can you confirm how this address may be getting loaded like this?  I set up an mxd, if it helps:

**Comment by kanglu666** [comment]
get the nearest pacel data from the new feature location created.

**Comment by cstevenson1** [comment]
no one has observed this issue in a long time so closing bug
