### ISSUE TITLE
Creating Barrel Conveyance Step Numbers

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#119]
The window that displays when creating a new barrel conveyance has "Step 1" twice. It should be changed to Step 1, Step 2 then Step 3.

![image](https://cloud.githubusercontent.com/assets/16919958/13927037/4fc9862e-ef65-11e5-86fc-4bd3d3f3daea.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
