### ISSUE TITLE
Roadway Culvert Conveyance Doesn't Allow for Conveying Streams

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#122]
Roadway Culvert Conveyance does not allow the user to select if it is conveying a stream or not. 

![image](https://cloud.githubusercontent.com/assets/16919958/13928170/10c65866-ef6b-11e5-8c57-32833fd7d1ab.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
