### ISSUE TITLE
Watershed Label is using incorrect Attribute

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#123]
The labels for the watershed layer appears to be using the "Major Basin" attribute rather than the "Watershed" attribute of the DNREC Watershed layer. 

![image](https://cloud.githubusercontent.com/assets/16919958/13953329/cbf997d2-f011-11e5-87b3-21594bab8fa8.png)

The overlay with the conveyance is working properly and is pulling the correct attribute (White Clay Creek). However on the map, it is displaying "Piedmont Watershed" which I believe is the Major Basin attribute of the DNREC Watershed layer. The map should be displaying "White Clay Creek" instead.

**Comment by leeensminger** [comment]
updated in mpk.  will be fixed at next relese.
