### ISSUE TITLE
Component Present Logic

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#127]
When "Component" Present field = no (i.e Frame of Cover Present, or Cover Present, or Wall Present...) for either structure type = inlet or structure type = manhole, then all fields associated with that component should grey out. For example, if Frame of Cover Present = No, then Frame of Cover Material, Length, Width, and Height should grey out (highlighted in yellow). If Grate Present = No, then Grate Type should grey out in addition to the fields listed above. 

![image](https://cloud.githubusercontent.com/assets/16919958/13962418/41af8bd8-f037-11e5-9d55-f6113b54a9db.png)

**Comment by leeensminger** [comment]
Holding off pending discussion for Bruce.

**Comment by mjuber-kci** [comment]
After discussion with Bruce, the first comment is still valid. When a Component Present = "No" then the highlighted fields shown above should grey out. However, when Component Present = "Yes" then the Component Material (along with "Grate Type" for the Grate component) should be required (shown highlighted below). Length, Width and Height should not be required.


![image](https://cloud.githubusercontent.com/assets/16919958/14213868/2def2b48-f808-11e5-90aa-7f9919bf52ff.png)

**Comment by mjuber-kci** [comment]
The low bug portion part, is that if grate present = no, grate type should not be required.

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.2 release
