### ISSUE TITLE
Outfall Component Inspection Logic

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#128]
On Page 3 of the inspection form (Inspection form for the Outfall Components), If Inspected = No (circled in red) then everything below (circled in blue) should grey out. 

![image](https://cloud.githubusercontent.com/assets/16919958/13964353/b44cd68e-f03f-11e5-85be-0b1627e5debe.png)

**Comment by mjuber-kci** [comment]
Overall Rating should be included in the section circled in blue. Overall Rating should grey out when Inspected = No. Additionally, Overall Rating should be at the bottom of the form under all of the ratings. 

![image](https://cloud.githubusercontent.com/assets/16919958/14084571/4c9018f4-f4e9-11e5-8b52-c5314cafe991.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.2 release
