### ISSUE TITLE
If Outfall Component is not present, then should be grey in the inspection

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#129]
If an outfall component is not present, then all associated fields under should grey out. Additionally under the inspection, the rating for that outfall component should be greyed out. 

For example if Undefined Outfall Channel = No (circled in red), then Material should grey out (circled in blue). 

![image](https://cloud.githubusercontent.com/assets/16919958/13964505/7500fba8-f040-11e5-8208-f402e4a0be1c.png)

Additionally, within the inspection for that structure, Condition for Undefined Outfall channel (circled in green) should be greyed out as well

![image](https://cloud.githubusercontent.com/assets/16919958/13964534/9816b9f2-f040-11e5-97de-e9282b5d6cd4.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
