### ISSUE TITLE
Selection for Barrel Conveyance

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#13]
In the Selections tab, is the "deldot_npdes_7.DBO.BARREL_CONVEYANCE" supposed to select the Barrel Conveyances as a whole? I know I created Barrel Conveyances in this work area however, no features are listed in the Features List Tab when I try to query them using "deldot_npdes_7.DBO.BARREL_CONVEYANCE".

![image](https://cloud.githubusercontent.com/assets/16919958/12719039/93ab35de-c8c0-11e5-9f99-2b606dd99f2e.png)

**Comment by kanglu666** [comment]
since deldot_npdes_7.DBO.BARREL_CONVEYANCE is not a feature class, you can't do selection using "Geographics Filters", but you can do selection by "Advanced Query Builder", for example:
Filed Name: pick Object
Operator: pick Is Not Null
click Add then click Select
