### ISSUE TITLE
Manhole and inlet components not present gets greyed out in inspection

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#130]
Any component for both manholes and inlets that are selected as not present in the inventory tab, the rating for that component should be greyed out in the inspection. 

For example, if both frame of cover present and cover present are both "No" (Circled in red),
![image](https://cloud.githubusercontent.com/assets/16919958/13964763/bc3cde8c-f041-11e5-92aa-3a588cbe3b05.png)

Then in the inspection, Frame of Cover Condition and Cover Condition should grey out. 
![image](https://cloud.githubusercontent.com/assets/16919958/13964813/f8e7b76c-f041-11e5-83cf-421c7a563743.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.2 release
