### ISSUE TITLE
Need ability to turn on and off layers individually within DelDOT BaseData

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#131]
We need to be able to turn off a single layer within the base data. Otherwise we would not be able to see the Districts layer or the aerial imagery because the Maintenance Areas layer is drawing on top.

![image](https://cloud.githubusercontent.com/assets/16919958/13994219/2eb04a90-f0fa-11e5-98e9-6597e2907c59.png)

**Comment by leeensminger** [comment]
as discussed earlier, @kanglu666 please implement this feature

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release
