### ISSUE TITLE
Aerial Layer needs to be added to DelDOT BaseMap

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#132]
Aerial Layer needs to be added to the BaseMap.

**Comment by leeensminger** [comment]
aerial imagery will be stored on the local hard drive.  @kanglu666 will implement a setting in the config file, so you can point the application to the imagery files.

**Comment by leeensminger** [comment]
@kanglu666 , Users need ability to toggle on/off aerial imagery per COUNTY (e.g., turn on Kent County aerials, or turn off Sussex county aerials).  You can dictate to us what the directory structure needs to look like, as long as we support this requirement.

**Comment by kanglu666** [comment]
will update, only all base layer .mpks in place, enhancement.

**Comment by kanglu666** [comment]
Sample imagery .mpk (Aerial Imagery) has been added to the field tool. ready for testing in version 1.1 release.

once we get the the final imagery .mpk, i will plug in the tool.

**Comment by cstevenson1** [comment]
The sample imagery loaded for a small portion of New Castle County appears to be working
