### ISSUE TITLE
Discharge Dstrm Type and Ownership Dstrm should only be on Outlet

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#133]
On the first page of the Inventory form for Pipe End, Discharge Dstrm Type and Ownership Dstrm should grey out when Is Outlet = No and Unknown. 

![image](https://cloud.githubusercontent.com/assets/16919958/13994463/41bed13c-f0fb-11e5-812a-8ed01b569d9b.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.2 release

**Comment by mjuber-kci** [comment]
Fields grey out correctly however they are still required fields. See bug #201
