### ISSUE TITLE
Dstrm should be spelled out 

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#134]
On the first page of the Inventory form for Structure Type = Pipe End or Structure Type = Swale Connection, "Dstrm" should be spelled out "Downstream".

Pipe End:
![image](https://cloud.githubusercontent.com/assets/16919958/13994979/97019a74-f0fd-11e5-8229-1781456d89d6.png)

Swale Connection:
![image](https://cloud.githubusercontent.com/assets/16919958/13995044/e8583054-f0fd-11e5-886f-76d624e2c0a0.png)

**Comment by mjuber-kci** [comment]
Also for the Swale Connection, "Discharge DSTRM" should be "Discharge Downstream Type"

**Comment by kanglu666** [comment]
updated, ready for testing in next release
