### ISSUE TITLE
IS Outlet need to be moved after Connection Type for Swale Connection

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#135]
"IS Outlet" should be placed below "Connection Type" on the first page of the Inventory form for Structure Type = Swale Connection. Additionally, "IS Outlet" should be "Is Outlet", the 's' should not be a capital letter.

![image](https://cloud.githubusercontent.com/assets/16919958/13995175/6b0bd960-f0fe-11e5-9182-ade85752946e.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
