### ISSUE TITLE
Swale Connection Inventory Form Logic

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#136]
For the first page of the Inventory form for Structure Type = Swale Connection, when "Connection Type" = Start, Midpoint, or Connection, "Is Outlet" should be greyed out. When "Is Outlet" = No, N/A or is greyed out, "Discharge Downstream" and "Ownership Downstream" should be greyed out. 

![image](https://cloud.githubusercontent.com/assets/16919958/13995457/b51bd61c-f0ff-11e5-9d8d-4443ea7d9482.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
