### ISSUE TITLE
Time stamp is incorrect

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#139]
The date appears to be correct but the time stamp seems off. The top image is from the field tool and the bottom image is the date and time according to my desktop.

![image](https://cloud.githubusercontent.com/assets/16919898/14017003/615119ca-f19a-11e5-9f75-7dd544ce8cbf.png)

![image](https://cloud.githubusercontent.com/assets/16919898/14016970/1c95fc24-f19a-11e5-8e23-e68bd4003355.png)

**Comment by cstevenson1** [comment]
The time stamp also varies between the Location tab and the inspection form. I created a new conveyance and then created an inspection, immediately after filling out the required fields. The time in the Location tab was 9:14 AM and the inspection time said 1:15 PM.

![image](https://cloud.githubusercontent.com/assets/16919898/14352451/9da2cad2-fca2-11e5-8aae-3fcd5a810daf.png)

![image](https://cloud.githubusercontent.com/assets/16919898/14352467/aecc9856-fca2-11e5-86f7-8055f839ecc0.png)

**Comment by kanglu666** [comment]
updated, ready for testing

**Comment by cstevenson1** [comment]
Time stamp no longer shows in the list for conveyance inspections. Examples below do not represent the same conveyance.


Before (snipped from the conversation above): 
![image](https://cloud.githubusercontent.com/assets/16919898/15082713/5ac0a4e4-1397-11e6-9c84-78953900fbfe.png)
 

Now:
![image](https://cloud.githubusercontent.com/assets/16919898/15082689/32b871d4-1397-11e6-9ce0-93aff1dfa09a.png)

**Comment by kanglu666** [comment]
updated, ready for testing in Version 1.1 release

**Comment by cstevenson1** [comment]
Same issue as above where time stamp does not appear but for Structure Inspections. Time Stamp is properly working for Conveyance Inspections.

Structure Inspection
![image](https://cloud.githubusercontent.com/assets/16919898/16732673/5ac00d02-474c-11e6-891c-e2b0c5e4c777.png)


Conveyance Inspection
![image](https://cloud.githubusercontent.com/assets/16919898/16732752/9f9d2324-474c-11e6-9514-2cf27d27ab8d.png)

**Comment by kanglu666** [comment]
at this moment, i have remove the time stamp for the inspections records. because, when user choose and earlier date other than current datetime to save the inspection. user does not get an option to choose the time to save. 
If we do need the correct time stamp for this, we will do it for later ENHANCEMENT.

**Comment by cstevenson1** [comment]
Spoke with Bruce and he said time stamp is not needed at this time but would like to discuss it for a possible enhancement in the future.

**Comment by cstevenson1** [comment]
This may get handled with #271

**Comment by impittman** [comment]
@cstevenson1 i will hold on sending this and assign to myself for tracking to ensure we get this one fixed

**Comment by cstevenson1** [comment]
fix time stamp with #271
