### ISSUE TITLE
Cannot select structure type in new work area

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#14]
I opened the field tool today and created a new work area, then manually placed a new structure. The structure type drop down was blank, however the drop down had valid values in it when I tried to create a new structure within a work area that was generated last week. Melissa tried the same process and experienced the same issue. 

![image](https://cloud.githubusercontent.com/assets/16919898/12719243/e41739b8-c8c1-11e5-8984-94f183ba8580.png)

**Comment by leeensminger** [comment]
Can you retest this issue?  Since the map service was updated last last week (and fixed the inability to create new work areas), this may have fixed this issue.

**Comment by cstevenson1** [comment]
Retested and it is no longer an issue since the update.
