### ISSUE TITLE
Text for Dumping in WQ Investigation does not fit on page

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#140]
For a WQ Investigation when Report Type=Dumping a list of potential dumping types are given on page 2. Some of the text for these options are not fully visible.

![image](https://cloud.githubusercontent.com/assets/16919898/14017265/b5670324-f19c-11e5-8a18-9a0686d2f104.png)

**Comment by kanglu666** [comment]
updated.
