### ISSUE TITLE
Cannot attach photo to culvert Point

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#141]
I created an inspection for a culvert point and was unable to add a photo on page 5  as seen in the snip below. I was prompted to save the inspection first but I had already saved the structure and the inspection. I checked and all fields from previous pages had been filled out excluding page 2 which was a blank page.

![image](https://cloud.githubusercontent.com/assets/16919898/14017980/7dec24d8-f1a1-11e5-874a-2a3c4f727ca0.png)

![image](https://cloud.githubusercontent.com/assets/16919898/14018101/3ed1ec28-f1a2-11e5-9299-94579def7bc3.png)

**Comment by kanglu666** [comment]
We are missing culvert Point table in database, this is also related with issue #142 and #143

**Comment by leeensminger** [comment]
Updated in DB, will be ready when BC loads

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by cstevenson1** [comment]
Able to add photo and page 2 is no longer blank
