### ISSUE TITLE
No pop up box saying new culvert point added

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#143]
When I added a new dummy node and saved, two dialog boxes popped up as shown below (one saying new structure added, followed by one saying new dummy point added). When I added a new culvert point, only the first dialog box popped up saying a new structure was added. Wanted to confirm a new culvert point record was also being made after hitting Save. If so, then the number of pop up boxes should be consistent between structure types. 

![image](https://cloud.githubusercontent.com/assets/16919898/14019067/55393840-f1a7-11e5-8804-6bb86e17c494.png)

![image](https://cloud.githubusercontent.com/assets/16919898/14019080/5f508086-f1a7-11e5-84b0-50d2f997a002.png)

**Comment by leeensminger** [comment]
Updated in DB, will be ready when BC loads

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by cstevenson1** [comment]
Notification for new culvert point pops up now
