### ISSUE TITLE
Typos in deleting a current feature pop up box

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#144]
There are typos in the pop up box that appears when you use the trash can button to delete the current feature. Between "sure" and "delete", the words "you want to" should be added. "the" can also be added between "delete" and "current". The "if" should have the i capitalized in the second part of the message. 

![image](https://cloud.githubusercontent.com/assets/16919898/14020184/6dac533a-f1ac-11e5-93cf-ce98ae78ee35.png)

**Comment by kanglu666** [comment]
updated
