### ISSUE TITLE
Show GPS Location when creating a conveyance 

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#147]
When creating a new conveyance, a window appears that states "Select a method to create feature". there are three options, "Cancel", "Place manually" or "Show GPS Location". Is the "Show GPS Location" needed because using the GPS location could not accurately determine the upstream/downstream structures. Therefore, we would always use the "Place manually" option so would "Show GPS Location" even need to be on the window?

![image](https://cloud.githubusercontent.com/assets/16919958/14117893/d7c0c628-f5b4-11e5-840b-513ac5081067.png)

**Comment by leeensminger** [comment]
@mjuber-kci Have you tested the application with a GPS unit, outside?

**Comment by leeensminger** [comment]
Makes sense - the entire popup box (for conveyances only) could be removed from the workflow
