### ISSUE TITLE
Barrel Conveyance Inspection Tab

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#151]
Because DelDOT wants each barrel inspected individually, there is no need for the Inspection Tab for the Barrel Conveyances. 

![image](https://cloud.githubusercontent.com/assets/16919958/14216718/576b60f8-f818-11e5-9a1f-2378aa759b1f.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by mjuber-kci** [comment]
Cannot test this right now. Cannot create a barrel conveyance, see #179
