### ISSUE TITLE
Manhole and Inlet Inspections

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#152]
On the inspection forms for both Manholes and Inlets, "Frame Cover" should be "Frame of Cover".

Manhole Inspection:
![image](https://cloud.githubusercontent.com/assets/16919958/14216881/1d18b7b0-f819-11e5-9e9e-4a121b700dae.png)

Inlet Inspection:
![image](https://cloud.githubusercontent.com/assets/16919958/14216892/29e57488-f819-11e5-96fd-bbb503ba670c.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release
