### ISSUE TITLE
Component Order for Inlet

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#153]
The order of the Components for Structure Type = Inlet for the Inventory Form should be as follows. Note "Frame of cover" should be "Frame of Cover" and "Ring" should be "Adjustment Ring"

Frame
Grate
Wall 
Curb
Step
Adjustment Ring
LFC
Frame of Cover
Cover

![image](https://cloud.githubusercontent.com/assets/16919958/14249405/9569334a-fa47-11e5-8f03-becdd7bfdae0.png)

The order for the Inspection form should be:

Frame
Grate
Wall 
Curb
Frame of Cover
Cover

![image](https://cloud.githubusercontent.com/assets/16919958/14249511/1495352e-fa48-11e5-9eb2-a0382407b1d9.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version1.0 release
