### ISSUE TITLE
Component Order for Manhole

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#154]
The order of the Components for Structure Type = Manhole for the Inventory Form should be as follows. Note: "Ring" should be "Adjustment Ring".

Frame of Cover
Cover
Wall 
Step
Adjustment Ring
LFC

![image](https://cloud.githubusercontent.com/assets/16919958/14249938/2ba6f502-fa4a-11e5-8bcd-3fc65aec44b3.png)

The order of the Components for the Inspection Form should be:

Frame of Cover
Cover
Wall 

![image](https://cloud.githubusercontent.com/assets/16919958/14249955/3da2add2-fa4a-11e5-9f0e-367dd8de8186.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release
