### ISSUE TITLE
Overall Rating for Manholes and Inlets

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#155]
For the Inspection forms for both Structure Type = Manhole and Inlet, "Overall Rating" field should be located at the bottom of the form.

Manhole Inspection Form:
![image](https://cloud.githubusercontent.com/assets/16919958/14250036/9f7580fc-fa4a-11e5-8348-2148767f1411.png)
Inlet Inspection Form:
![image](https://cloud.githubusercontent.com/assets/16919958/14250157/23723eb8-fa4b-11e5-9bd9-3deebff6f034.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release
