### ISSUE TITLE
Misspelling of Phragmites 

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#158]
Phragmities should be spelled, "Phragmites" for the, "Invasive Type" Domain under the, "3. Invasive Vegetation" Parameter of the BMP Inspection form..

![misspelling of phragmites](https://cloud.githubusercontent.com/assets/16919984/14317110/a570b81a-fbd4-11e5-915e-878df5cf7081.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by mortynsky** [comment]
This issue has been fixed!

**Comment by cstevenson1** [comment]
This appears to no longer be fixed. Causing misspellings on the BMP reports, logged as bug 180 in GitHub for the viewer

![image](https://user-images.githubusercontent.com/16919898/31510033-75f53ee4-af51-11e7-9b83-14a8e198e5f1.png)

**Comment by kanglu666** [comment]
updated in dev

**Comment by cstevenson1** [comment]
Still spelled incorrectly. The last "i" should be an "e"

![image](https://user-images.githubusercontent.com/16919898/32116274-fa2ae070-bb17-11e7-8e13-2061c3b6c8fa.png)

**Comment by leeensminger** [comment]
updated in dev.  do a new work area in the field tool and you should see it. @cstevenson1

**Comment by cstevenson1** [comment]
Appears fixed 
![image](https://user-images.githubusercontent.com/16919898/32379222-4cb2f560-c083-11e7-9a7e-e3c3ea69ff59.png)

**Comment by cstevenson1** [comment]
Appears fine

![image](https://user-images.githubusercontent.com/16919898/32422053-e089a15a-c26b-11e7-9e99-01858a20d1a9.png)
