### ISSUE TITLE
Misspelling of Purple Loosestrife

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#159]
Purple Loostrife should be spelled, "Purple Loosestrife" for the, "Invasive Type" Domain under the, "3. Invasive Vegetation" Parameter of the BMP Inspection form.

![misspelling of purple loosestrife](https://cloud.githubusercontent.com/assets/16919984/14317234/55a78448-fbd5-11e5-9b6c-43f2893488fc.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by mortynsky** [comment]
This issue has been fixed!

**Comment by mortynsky** [comment]
"Purple Loosestrife" is mispelled again both in the field tool and in the D_Invasive Table:

**Field Tool:**
![purple loosestrife](https://user-images.githubusercontent.com/16919984/29982492-e9907aa0-8f1f-11e7-8c77-0b1c3f8b5dd7.JPG)

**D_Invasive Table:**

![image](https://user-images.githubusercontent.com/16919984/29982451-c1ba38f4-8f1f-11e7-9aae-58c3ed9e17c8.png)

**Comment by cstevenson1** [comment]
![image](https://user-images.githubusercontent.com/16919898/59851885-b1643a00-933b-11e9-8eb1-2166ac7cd1c0.png)
