### ISSUE TITLE
Cannot Query PID Points

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#16]
Using the Selections tab I tried to query a PID Point I had just created and nothing happened after clicking the Select button, unlike when I queried Structures which opened the Feature List tab. 

For Select I chose "PID_POINTS" and for County under Geographic Filters I chose "Sussex", which is where my current work area is located.

**Comment by kanglu666** [comment]
confirm with DelDot users for this one. then we will decide whether or not to add County，Watershed etc those fields in PID Point feature class

**Comment by leeensminger** [comment]
@cstevenson1 @mjuber-kci @mortynsky Is it required that we search/select by PID Points?  Would you ever want to reference a PID Point in that way?  If not,then we will remove the PID_POINTS from the filter/selection tab.

**Comment by leeensminger** [comment]
@cstevenson1 @mjuber-kci @mortynsky What fields, specifically, should be added for PID Points?

Address?
Subdivision Name (GIS)?
Subdivision Name (Field)?
Watershed
Watershed HUC8
County
District
Maintenance Area

**Comment by cstevenson1** [comment]
@leeensminger @mjuber-kci @mortynsky Yes to all of the ones you listed since those are the fields available for structures. We were hoping to have the same geographic query capabilities that we would have with structures (i.e. being able to say something like show me all PID points in a certain county or subdivision).

**Comment by leeensminger** [comment]
@kanglu666 , please add the following to the UI for PID points, including the overlay functionality.  I will add these updates to data model:

1. Address
2. Subdivision Name (GIS)
3. Subdivision Name (Field)
4. Watershed
5. Watershed HUC8
6. County
7. District
8. Maintenance Area

**Comment by kanglu666** [comment]
updated, ready for testing in next release
