### ISSUE TITLE
Misspelling of Length in Measure Tool

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#160]
Under the measure tool, Length is misspelled twice.

![misspelling of length](https://cloud.githubusercontent.com/assets/16919984/14317543/b9f4e3c2-fbd6-11e5-9dc8-93a1eb37e383.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by mortynsky** [comment]
This issue has been fixed!
