### ISSUE TITLE
Measure Tool Negative Number for Area

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#161]
When you use the Measure Tool the, "Area Measure Results" generates a negative number (I think the number is correct it just is negative).

![negative units for area](https://cloud.githubusercontent.com/assets/16919984/14317636/2fa65ef2-fbd7-11e5-9148-9db9563aa37f.JPG)

**Comment by kanglu666** [comment]
please testing in version 1.0 release

**Comment by mortynsky** [comment]
I still get a negative number for area when using the measure tool.  Christina and Melissa get a positive number.  Could this be a possible install issue or user error?

**Comment by mortynsky** [comment]
I still get a negative number for area when using the measure tool. Christina and Melissa get a positive number. Could this be a possible install issue or user error on my part?

**Comment by mjuber-kci** [comment]
I believe if you draw the area polygon clockwise, you get a positive acreage. If you draw the polygon counter clockwise, you get a negative acreage.

**Comment by leeensminger** [comment]
Question resolved.
