### ISSUE TITLE
Measure Tool Bar - Needs to have Acres for Area

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#162]
The Measure Tool Bar does not have "Acres" as an option for "Area" under the "Measure Type" box.

![measure tool bar - needs acres](https://cloud.githubusercontent.com/assets/16919984/14318652/e76930b0-fbdb-11e5-8b92-24ff5d4b465b.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by mortynsky** [comment]
This issues has been fixed!
