### ISSUE TITLE
GPS Current Location Button

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#163]
The GPS appears to connect up to the application and gets a location (not sure where).  When I try to select the, "Current Location" button the map keeps scrolling and scrolling......... and never seems to get to my current location.    

![gps](https://cloud.githubusercontent.com/assets/16919984/14323192/8da92dca-fbed-11e5-9eca-7e4aabac4ce1.JPG)

**Comment by kanglu666** [comment]
Reconfigured the setting, ready for testing in version 1.0 release

**Comment by mortynsky** [comment]
This function does still not pan you to your location but gives the following message, "Make sure your GPS is connected and enabled".  Something is wrong because this error message shows even when the GPS is in fact both connected and enabled.  This is evident in the application because the "GPS Info" and "Messages" buttons are both working and functioning properly in the application.

![gps pan to my location error](https://cloud.githubusercontent.com/assets/16919984/16694702/b516a36e-4509-11e6-9ebf-720eeebf737e.JPG)

**Comment by kanglu666** [comment]
for this one, i think you need enable your GPS NEAM data type: GPRMC,
from the message, you can see that you dont get the NEAM  GPRMC data in.

go to your GPS controller setting neam output setting, check all data type.

**Comment by mortynsky** [comment]
The above response has fixed the issue!
