### ISSUE TITLE
Show GPS Location Button

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#164]
The Show GPS Location Button does not work.  This is when the GPS is enabled and has satellites.  

![show gps location](https://cloud.githubusercontent.com/assets/16919984/14323158/6b13b3f2-fbed-11e5-9d88-560a3ef79353.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by mortynsky** [comment]
When creating a feature using the GPS button the following error displays, "Make sure your GPS is connected and enabled!".  This is when the GPS is connected and enabled in the application.  The application is actively displaying the # of satellites (in the "GPS Info" tab) and is receiving positions (in the "Messages" tab).

**Error**
![when creating a structure using gps](https://cloud.githubusercontent.com/assets/16919984/16666597/6fe8ac1e-4456-11e6-959a-5152a8b6fcdb.JPG)

**GPS Info Tab is working**
![gps info works](https://cloud.githubusercontent.com/assets/16919984/16666620/8aedb090-4456-11e6-9e3d-61f4491b4602.JPG)

**Messages Tab is working**
![gps messages works](https://cloud.githubusercontent.com/assets/16919984/16666629/9625153e-4456-11e6-864e-affe5789d67f.JPG)

**Comment by kanglu666** [comment]
for this one, i think you need enable your GPS NEAM data type: GPRMC,
from the message, you can see that you dont get the NEAM  GPRMC data in.

go to your GPS controller setting neam output setting, check all data type.

**Comment by mortynsky** [comment]
This issue has been fixed based on the above recommendations.
