### ISSUE TITLE
Doorhanger Info

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#165]
It appears that the Dumping/Doorhanger Info (circled in red) should be triggered when "Doorhanger Info" = Yes. Currently it is being triggered when "Report Type" = Dumping.

![image](https://cloud.githubusercontent.com/assets/16919958/14326859/cc7d2212-fbfd-11e5-8c5b-6544b667286c.png)

![image](https://cloud.githubusercontent.com/assets/16919958/14326827/b1c154b6-fbfd-11e5-9bed-7d6133698036.png)

**Comment by leeensminger** [comment]
@mjuber-kci Please consider closing this bug, as it is very similar to #167 and will be fixed when that update is implemented.
