### ISSUE TITLE
Field Sheet/Doorhanger Info

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#167]
Currently if the Doorhanger information (circled in red) is triggered, it replaces the Field Sheet information (circled in blue) on page 2 of the WQ Investigation.We need to have the ability to trigger both sets of information within the same WQ Investigation.

![image](https://cloud.githubusercontent.com/assets/16919958/14327928/86f55804-fc02-11e5-846a-eb0de7b5f756.png)

![image](https://cloud.githubusercontent.com/assets/16919958/14327955/a92e6d98-fc02-11e5-8790-95129be72fdf.png)

**Comment by leeensminger** [comment]
[Workflow_Process_WQ_Investigation_20160609.pdf](https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/files/307627/Workflow_Process_WQ_Investigation_20160609.pdf)

@kanglu666 Implement system logic according to this document.

**Comment by kanglu666** [comment]
updated, ready for testing in version 1,1,
