### ISSUE TITLE
Type Discharge logic

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#168]
"Type Discharge" field (circled in red) should be moved below "Determination" (circled in blue) and should only be valid when "Determination" = Evidence of Illicit Discharge. If "Determination" ≠ Evidence of Illicit Discharge, then "Type Discharge" should be greyed out. 

![image](https://cloud.githubusercontent.com/assets/16919958/14328516/07004016-fc05-11e5-8633-17f02618f922.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1. release
