### ISSUE TITLE
Overlay for District within Work Orders Form

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#169]
District should automatically populate with the ability to manually override/change it in the Work Order Form (similar to the Location tab that uses an overlay to fill out the field). The selection within 'District' should still dictate what is populated for 'Supervisor'.

![image](https://cloud.githubusercontent.com/assets/16919898/14353057/66d131bc-fca5-11e5-92ef-320f254fdb4d.png)

**Comment by kanglu666** [comment]
Work Order for Barrel Conveyance and Barrel will not have this function, because they are not carry DISTRICT field. Structure, BMP and Conveyance will do.
