### ISSUE TITLE
Personnel and Last Rain Date

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#17]
Where does Personnel and Last Rain Date get filled out so that it automatically generates for every new inspection and WQ Investigation?

**Comment by leeensminger** [comment]
It should be in the Setting button.  For me, clicking this icon has no result.  This might be intentional/known by Lu, but if you find the same, please log a bug so we can track it.

![image](https://cloud.githubusercontent.com/assets/4103847/12948279/0678fbe0-cfcf-11e5-8583-a72c5a821254.png)
