### ISSUE TITLE
Work Order would not Delete

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#170]
First, I created and saved a work order on a conveyance. I then clicked delete and hit 'Yes' when it asked if I was sure I wanted to delete it but the work order did not disappear from the list of work orders present for the conveyance. 

1.
![image](https://cloud.githubusercontent.com/assets/16919898/14354078/e60126d2-fca9-11e5-8613-f43e90468cb9.png)

2.
![image](https://cloud.githubusercontent.com/assets/16919898/14354088/f2d54848-fca9-11e5-8f96-9999d923240e.png)

3.
![image](https://cloud.githubusercontent.com/assets/16919898/14354118/1790b398-fcaa-11e5-9ba2-8728c2da8fef.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by cstevenson1** [comment]
Able to delete work order now
