### ISSUE TITLE
Incorrect Inspection Date for Swale Inspection

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#171]
I first drew in a swale between a swale connection point and a dummy point. I then filled in the required fields and saved. I then created an inspection and saved the inspection, at which time I noticed that the date was wrong for the inspection date as shown below. However, if I created a second inspection on the same conveyance, the date was correct. 

![image](https://cloud.githubusercontent.com/assets/16919898/14360814/1c3ed822-fcc6-11e5-8b49-e74cf1d1f636.png)

![image](https://cloud.githubusercontent.com/assets/16919898/14360897/72172696-fcc6-11e5-93ea-d311ed05524d.png)

**Comment by kanglu666** [comment]
test in version 1.0 release

**Comment by cstevenson1** [comment]
Inspection date is working so far
