### ISSUE TITLE
Previous Inspection shows for swale

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#172]
I added a new structure to my map and then drew in a swale. I filled out the required fields and then moved to the inspection tab (before hitting save) and the two inspections from the previous conveyance were displayed. I clicked save and the inspections were still displayed. I then clicked new inspection and hit cancel at which time the previous inspections disappeared. 

1. Previously Created Conveyance
![image](https://cloud.githubusercontent.com/assets/16919898/14360956/aee199b2-fcc6-11e5-86c6-01d75f4ac835.png)

2. Newly Created Conveyance With Same Inspections
![image](https://cloud.githubusercontent.com/assets/16919898/14361005/e90719fa-fcc6-11e5-847a-8341aab7a848.png)

3. Cancel Button I clicked after creating New Inspection
![image](https://cloud.githubusercontent.com/assets/16919898/14361091/4bfb215a-fcc7-11e5-92fd-4ec9d3c46c18.png)

4. Result from Hitting 'Cancel'
![image](https://cloud.githubusercontent.com/assets/16919898/14361043/1f7a182a-fcc7-11e5-826e-e5672a0bc310.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release
