### ISSUE TITLE
Clicking Sync Causes the Field Tool to Crash

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#173]
I attempted to Sync Work Area NCC_4_7_16 and the field tool crashed.

![image](https://cloud.githubusercontent.com/assets/16919898/14364047/0ad4eee6-fcd5-11e5-905d-914792bf2cf6.png)

![image](https://cloud.githubusercontent.com/assets/16919898/14364055/16bf631c-fcd5-11e5-9857-4ca1f19b79bd.png)

**Comment by kanglu666** [comment]
the database schema has updates, will be ready for fully test for the SYNC function in next release.
see #125

**Comment by kanglu666** [comment]
ready for testing in version 1.0 release

**Comment by cstevenson1** [comment]
Field tool no longer crashes when I try to Sync, however the following error message now displays. The sync function appeared to be working last week though.

![image](https://cloud.githubusercontent.com/assets/16919898/15113619/55979580-15c3-11e6-843f-6075c77fb6ad.png)

**Comment by kanglu666** [comment]
please test in version 1.1 release. 
Note: keep an eye on the sync, if the same error happens, let me know

**Comment by cstevenson1** [comment]
Have not received the error since
