### ISSUE TITLE
Conveyance Location Tab missing fields

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#174]
Location Tab for conveyances does not have fields for "Conveyance Number" or "Legacy Conveyance #" like Structures do.

![image](https://cloud.githubusercontent.com/assets/16919958/14395149/114dbd38-fd9e-11e5-8ac0-95c6e7456056.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release
