### ISSUE TITLE
Error message for PIPE_SEGMENT_NUM

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#176]
I created a pipe conveyance between two structures and filled out all required fields and the following message appeared when I clicked the Save button.

![image](https://cloud.githubusercontent.com/assets/16919898/15023100/e51f8ee4-11fc-11e6-98ad-323128be3551.png)

**Comment by mjuber-kci** [comment]
It appears that this error appears when saving conveyance type=pipe, roadway culvert and driveway culvert. Additionally, with this error, it does not save any of the pipe properties (ie Material, Shape, Height, Width, and Cross Sectional Area)

**Comment by kanglu666** [comment]
ready for testing in version 1.1. release
