### ISSUE TITLE
Personnel for Water Quality Investigation

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#177]
Personnel should automatically populate on the first page of the water quality investigation with the initials that were entered in the settings/tools for personnel. This feature is functional though for structure inspections.

![image](https://cloud.githubusercontent.com/assets/16919898/15115308/5c0a4706-15cc-11e6-8f55-7b54a0e9e1f1.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1. release
