### ISSUE TITLE
Previous BMP Inspection data shows up when creating a new BMP Inspection

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#178]
Previous BMP Inspection data shows up when creating a new BMP Inspection.  I have created a new BMP and am ready to conduct my inspection.

![no bmp inspection](https://cloud.githubusercontent.com/assets/16919984/15186341/b1335f84-176a-11e6-97d7-2e10a034cd30.JPG)

After creating a new inspection, data from the last BMP that was Inspected shows up in the new BMP Inspection that was just created.

![bmp inspection from previous bmp inspected shows up with all information filled out instead of a blank inspection form](https://cloud.githubusercontent.com/assets/16919984/15186366/c9c6c8a6-176a-11e6-9ee0-162a4914fc34.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in Version 1.1 release

**Comment by mortynsky** [comment]
This issue has been fixed!
