### ISSUE TITLE
Cannot create Barrel Conveyance

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#179]
When creating a new barrel conveyance, a notification comes up stating that the pipe is already associated with an existing barrel and to choose another pipe. I tried multiple pipes and still got the same message. 

![image](https://cloud.githubusercontent.com/assets/16919958/15187432/17b85f9e-176f-11e6-90bc-3d156d92ef36.png)

**Comment by kanglu666** [comment]
i think this message means the selected pipe already associated with another barrel, so it cannot associated to the new barrel conveyance.

please testing in version 1.1
