### ISSUE TITLE
GPS Bluetooth Settings - COM port options

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#180]
We need to have more COM port options.  When testing on my machine i needed to select COM 11 to connect to in the application but the GPS tab does not have this option available in the application.  Can we have COMs 1 - 20, or can we manually type in our own COM number?

![gps com port options](https://cloud.githubusercontent.com/assets/16919984/15226114/65dd368c-184f-11e6-98e8-5e95481bc60d.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1. release

**Comment by mortynsky** [comment]
This issue has been fixed!
