### ISSUE TITLE
GPS Settings - Bluetooth Settings:

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#181]
Under GPS Settings - Bluetooth Settings: the COM, Baud rate, and Location Provider fields do not save after closing and re-opening the application.  The settings for these fields need to be saved in the application so the user does not have to set them every time the need to connect the GPS up with the application.

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1 release

**Comment by mortynsky** [comment]
This issue has been fixed!
