### ISSUE TITLE
GPS Status Box

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#182]
We need to have some sort of "Status Box" like we have in the existing application that states if the GPS is connected to the application and if not why.  In the old application this box would tell you:

1.  If you were connected but had poor satellite signal - Not enough satellites
2.  If you were connected and receiving positions - Working normally!
3.  GPS not connected to COM port - Need to reconfigure Bluetooth connections/settings.

Here is what the GPS Status Box looks like in the existing application:

![gps status](https://cloud.githubusercontent.com/assets/16919984/15226670/aee95700-1851-11e6-9868-0d60819b4506.JPG)

It is very helpful in diagnosing GPS connection/setup issues.

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1 release

**Comment by mortynsky** [comment]
This issues has been added and fixed!
