### ISSUE TITLE
Memo line dates cannot be backdated

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#183]
For Water Quality Investigations, the memo date cannot be backdated. If you select a date in the past, when the memo line is saved, it changes the date to the current date. Additionally, you cannot delete a memo line. We need to have the ability to delete a memo line. 

![image](https://cloud.githubusercontent.com/assets/16919958/15331366/e54fd536-1c2e-11e6-9609-f2272fb418b9.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1 release.
there is no delete memo function at this moment, i will put it in "Enhancement".
