### ISSUE TITLE
Error message when clicking zoom icons when manually placing structure 

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#184]
I selected "New" then selected "Structure".
![image](https://cloud.githubusercontent.com/assets/16919958/15335429/53ad59f2-1c40-11e6-9581-948c49be894f.png)

Then selected the "Place manually" button and then if you select the "Zoom In" or "Zoom Out" tools (fixed zoom in and out does not cause a problem) and an error message appeared stating "Exception Message: A task was cancelled". 
![image](https://cloud.githubusercontent.com/assets/16919958/15335492/97a55164-1c40-11e6-9505-3fdd9c8112d9.png)

If you select "OK" on the error message window, you can no longer place the structure and must go back to the Feature List and start over.

**Comment by kanglu666** [comment]
the correct work flow should be, zoom in/out the correct location and then create new feature (place manual).

updated: once the user click the "place manual" button, toolbar will be disabled, waiting user to click the new feature location on the map, after that the toolbar will be enabled again.
at the meantime, if user want to zoom in/out after click the ""place manual" button, they can user mouse scorller to zoom in and out.

ready for testing in version 1.1. release
