### ISSUE TITLE
Units added to WQ Investigation

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#185]
All of the parameters on pages 2, 3, and 4 of the WQ Investigation should have units, be spelled correctly and have the correct capitalization. The parameters should read:

Air Temperature (F)
Flow Rate (cfs)
Water Temperature (F)
Surfactants (mg/L)
Ammonia (mg/L)
pH (units)
Potassium (mg/L)
Oil and Grease (mg/L)
Diesel Range Organics (mg/L)
Gasoline Range Organics (mg/L)

Page 2:
![image](https://cloud.githubusercontent.com/assets/16919958/15503231/c6fcd0c2-2186-11e6-9c68-f1eac9da42c9.png)

Page 3:
![image](https://cloud.githubusercontent.com/assets/16919958/15503250/ebcbac98-2186-11e6-8f23-0526e5138ff5.png)

Page 4 (Lab Results):
![image](https://cloud.githubusercontent.com/assets/16919958/15503413/c1de317a-2187-11e6-8260-415ddb6397e1.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1 release
