### ISSUE TITLE
BMP Inspections - General Landscape Photo Attachment

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#187]
I don't know if i missed previously, but there is no place to attach a general landscape photo, or any other general photos for a BMP inspection.  We need to take general landscape photos taken during each inspection, general structure photos for a new BMP inspection or after a BMP has been maintained, etc.

![bmp photos](https://cloud.githubusercontent.com/assets/16919984/15835232/ff393b9e-2bfc-11e6-97d1-3557fdc7d405.JPG)

This is the box i would imagine it would be in!

**Comment by kanglu666** [comment]
BMP Inventory Photo work flow has been added into the BMP Inventory page.
ready for testing in version 1.1. release

**Comment by mortynsky** [comment]
1. The comment about the BMP Inventory page is accurate and has been addressed.

2.  Regarding the BMP Inspection Photos, all Landscape photos for a BMP Inspection will be placed on the, "11.  Water Quality Treatment" Parameter.  They will then be migrated over to the specific location described above rather than attached to a BMP Parameter as future enhancement.

**Comment by cstevenson1** [comment]
duplicate with #208
