### ISSUE TITLE
BMP Inspection - Multiple Action Parameters - Need, "Clear Selection"

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#188]
In the Action Type summary box, once an Action Type is selected you cannot clear the selection and start new action type.  There needs to be a way to "clear the selection", otherwise you will have to overwrite or re-enter the same information just to de-select.  

![multiple action paramter overwrite](https://cloud.githubusercontent.com/assets/16919984/15835388/bcf181b4-2bfd-11e6-94b8-7aa72777fb8f.JPG)

**Comment by kanglu666** [comment]
updated, hold "Ctrl" key to deselect the current selected item..
ready for testing in version 1.1. release

**Comment by mortynsky** [comment]
This function does not work!

**Comment by leeensminger** [comment]
workflow error - appears to work
