### ISSUE TITLE
Inspected Reason should grey out

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#19]
Inspected Reason and Reason Description should grey out if "Yes" is selected for Inspected for all Structure Types.

![image](https://cloud.githubusercontent.com/assets/16919958/12725450/bc190724-c8e0-11e5-9885-72d4f6e01595.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
