### ISSUE TITLE
BMP Inventory Photos - Photo Date

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#190]
When adding more than two BMP Inventory Photos the "Photo Date" field automatically changes to the next calendar day.  So in this example the, Photo Date reads 7/9/2016 but the actual date is 7/8/2016.  Even if you manually the change the data back to 7/8/2016 it does not stay and changes back to the next calendar day, in this case 7/9/2016.

![bmp inventory photos](https://cloud.githubusercontent.com/assets/16919984/16697387/69b15938-4517-11e6-8f2c-cac79b0dec56.JPG)

**Comment by cstevenson1** [comment]
issue above was not observed. it looks like new photos do not default to the current date if there are existing photos but this is a very low level issue and not worth resources
