### ISSUE TITLE
BMP Inventory Photos - Photo Type and Photo Date Fields

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#191]
The Photo Type and Photo Date fields under the BMP Inventory Photos cannot be changed once they have been assigned.  Is this intentional?  If you assign the photo the wrong Photo Type by accident when adding a photo would you need to delete the photo and add it back again re-assigning the correct Photo Type?

![bmp inventory photos unable to change photo type or date](https://cloud.githubusercontent.com/assets/16919984/16697727/17051100-4519-11e6-82ff-a1791644c65a.JPG)

**Comment by cstevenson1** [comment]
should be addressed with bug #43
