### ISSUE TITLE
Delete Memo Line

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#192]
You currently cannot delete a memo line on a WQ Investigation. We should have the ability to delete a memo line.

![image](https://cloud.githubusercontent.com/assets/16919958/16688973/a1c84314-44ee-11e6-82c4-52947394b45c.png)

**Comment by cstevenson1** [comment]
this has since been resolved. memo workflow was reformatted
