### ISSUE TITLE
Structures and Conveyances Disappear When Zooming in.

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#193]
I synced my work area this morning and everything looked fine until I zoomed in. I noticed that my structures were visible at all extents but the features Christina added yesterday disappeared after I zoomed in to a certain extent.

Zoomed Out (Christina's data is circled in red, my data is circled in blue):
![image](https://cloud.githubusercontent.com/assets/16919958/16767607/3c2d98ec-480e-11e6-9e03-03e6e6589553.png)

Zoomed in (data circled in red has disappeared but the data circled in blue is still present at same extent):
![image](https://cloud.githubusercontent.com/assets/16919958/16767658/7cf257f0-480e-11e6-9d01-f579d04b4d09.png)

![image](https://cloud.githubusercontent.com/assets/16919958/16767736/cc21f0ce-480e-11e6-9955-1ce0e71958d8.png)

**Comment by leeensminger** [comment]
1. Melissa added structures and conveyances
2. Christina added strucvtures and conveyances on a separate
3. Both users synced
4. All features were present and visible until Melissa zoomed in.  Features created by the other user were not visible upon zooming in.

**Comment by kanglu666** [comment]
all data looks fine in the database. please test in version 1.3 release.

**Comment by cstevenson1** [comment]
she has not experienced issue since.
