### ISSUE TITLE
Date on WQ Investigations List

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#194]
We need to have the Date shown on the tab where all WQ Investigations are listed similar to the structure inspections. Additionally we do not need to see Inspection Type.

![image](https://cloud.githubusercontent.com/assets/16919958/17258345/679852f4-5594-11e6-9a3e-2b466056468e.png)

Structure Inspection:
![image](https://cloud.githubusercontent.com/assets/16919958/17258379/8e6b9954-5594-11e6-884b-3575d4066f75.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.4 release

**Comment by kanglu666** [comment]
the WQ Investigation table does not carry inspection date field, only create date field.

**Comment by leeensminger** [comment]
Ideal: 
1. set up new field for Inspection Date
2. modify feature service to use this field in place of the current Create Date, in images above

**Comment by mjuber-kci** [comment]
Will need to update WQ Report to use Inspection Date instead of CREATE_DATE on the report.

**Comment by mjuber-kci** [comment]
Within the database, the WQ_INVESTIGATIONS table has a CREATE_DATE and a CREATE_TIME field. Both fields include both date and time so only one of these fields is needed. CREATE_DATE, should be deleted when the inspection Date field is created. Additionally, the new Inspection Date field should be field calculated using the existing CREATE_DATE field. This is should be a higher priority enhancement due to the fact that we have to edit the CREATE_DATE if we need to back date an inspection.

**Comment by mjuber-kci** [comment]
To further clarify this issue, we need the following date/time attributes within the WQ_INVESTIGATIONS table:

Inspection Date (Date only) - Editable in Field Tool
Inspection Time (Time only) - Editable in Field Tool
Create Date (Date and Time) - View only in Field Tool
Last Edit Date (Date and Time) - View only in Field Tool

CREATE_TIME should be deleted from the WQ_INVESTIGATIONS table. Currently CREATE_DATE and LAST_EDIT_DATE are in the table, however, the time appears to be off. There are a few records that the LAST_EDIT_DATE is 6:30PM which is incorrect. We are normally finished with our work day at 3:30PM so there shouldn't be any times later than that. Both of the fields should view only in the field tool, but not editable. If it is easier to combine Inspection Date and Inspection Time into one, that is fine, as long as both the time and date are editable within the Field Tool.

Until this bug is completed, Web Viewer Bug #145 will not be fully resolved, regarding the WQI Report.

**Comment by mjuber-kci** [comment]
For WQI, we do not need both Create Date and Inspection Date. If we can update the time for the Create Date in the Field Tool (like we can for the Last Rain Date/Time) then we wouldn't need all of the above fixes to be made and would not need to update the WQI Report. If "Create Date" could be changed to "Inspection Date" only in the Field Tool UI that would be great but not necessary.

Create Date in Field Tool (Need to add ability to update time)
![image](https://user-images.githubusercontent.com/16919958/32558901-f2fef0d8-c473-11e7-9a7f-1722c5a870f9.png)

Last Rain Date/Time Example
![image](https://user-images.githubusercontent.com/16919958/32558941-04cb680a-c474-11e7-8e6d-e9785153ca89.png)

**Comment by leeensminger** [comment]
@impittman can you succinctly summarize the above and list here a numbered list of actions that need to be performed? then reassign to me.

**Comment by impittman** [comment]
@leeensminger I have read through the comments and compiled based on the latest posts. However, it may be advantageous for Newark to review my comments to ensure nothing is missing.
Edits to the WQ Investigation Form:
1) Change "Created Date" field to allow both the Date and Time to be editable. Currently, it only allows the Date to be altered, no time stamp is present to be edited.
2) If possible, change the wording only for "Created Date" on the UI form to show "Inspection Date". 
3) It would be worthwhile to ensure the correct time is being captured as well in the LAST EDIT DATE field. This was noted above as showing a discrepancy in the data vs the actual time entered.

**Comment by cstevenson1** [comment]
Melissa has confirmed Maria's summary is accurate

**Comment by impittman** [comment]
@kanglu666 please see my comments from 11/14/2018 on the issues and potential fixes.

**Comment by kanglu666** [comment]
updated in my local.
![1](https://user-images.githubusercontent.com/6352480/54065668-40689e80-41f2-11e9-891b-8dfd4fe7132e.JPG)
![2](https://user-images.githubusercontent.com/6352480/54065670-4494bc00-41f2-11e9-8cd2-095aa3f2565c.JPG)

**Comment by cstevenson1** [comment]
fixed in dev. please push to prod

![image](https://user-images.githubusercontent.com/16919898/55004263-49a68900-4fb0-11e9-8a46-79f17d19bd31.png)

**Comment by leeensminger** [comment]
@kanglu666 please add to prod release when the time comes

**Comment by mjuber-kci** [comment]
Bug was included in Prod Field Tool 7.0 release. 

![image](https://user-images.githubusercontent.com/16919958/64438718-97163e80-d096-11e9-8690-7fd607ffc1a8.png)
