### ISSUE TITLE
Unable to rate components for a previously created structure

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#196]
I created a new manhole, saved the information, and then proceeded to inventory a pipe conveyance. I then re-opened the manhole to generate an inspection but was unable to rate the wall component even though it was marked as present in the inventory tab and inspected was marked as yes in the inspection tab (see second set of snips). As seen in the snip, all three component rating fields were disabled even though they were marked as present in the inventory tab. Debris, Overall Rating, and Infiltration could be rated though. I then proceeded to create a new inlet and filled out all required fields. Then I clicked saved and immediately continued to create a new inspection. No issues presented, as shown in the first set of snips below. 

Structure that had the inspection created before exiting out:

![image](https://cloud.githubusercontent.com/assets/16919898/17329866/88aaf036-5892-11e6-82ac-997c77cbbcc6.png)

![image](https://cloud.githubusercontent.com/assets/16919898/17329851/7577a18a-5892-11e6-8a55-ebc24489d67a.png)

![image](https://cloud.githubusercontent.com/assets/16919898/17329883/9b508b42-5892-11e6-81f0-bb19ba04d5c1.png)

Structure that had been exited and re-opened to create the inspection:
![image](https://cloud.githubusercontent.com/assets/16919898/17329631/7f13e0d8-5891-11e6-9a1d-0d6366a775b0.png)

![image](https://cloud.githubusercontent.com/assets/16919898/17329644/8c238dfa-5891-11e6-897b-0b6758ebdfc1.png)

![image](https://cloud.githubusercontent.com/assets/16919898/17329663/9c4de7f2-5891-11e6-9c1a-271fdde0fdaa.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.4 release
