### ISSUE TITLE
Rearrange Pipe Inspection Fields

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#197]
We would like the fields to be rearranged on the first page of the conveyance inspection form (both swale and pipe inspections) to match the order on the structure inspections. From a work flow perspective, its more logical.  

Current pipe inspection:
![image](https://cloud.githubusercontent.com/assets/16919958/17338920/873ca350-58b7-11e6-8ad8-f6c14590ce46.png)

Structure inspection
![image](https://cloud.githubusercontent.com/assets/16919958/17338935/9abf699e-58b7-11e6-8450-24f7ac98d524.png)

**Comment by cstevenson1** [comment]
not enough value to invest resources
