### ISSUE TITLE
Base data symbology did not come through correctly

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#198]
Symbology for certain base data layer does appear to have come over correctly in field tool for certain layers. Additionally can the background for the Field Tool be white instead of grey?

**Stream- Too thick of a line**
Field Tool
![image](https://cloud.githubusercontent.com/assets/16919958/17341078/ef45cc02-58c0-11e6-97a1-22645466bdfd.png)

BaseData.mxd
![image](https://cloud.githubusercontent.com/assets/16919958/17341088/016cd376-58c1-11e6-8b58-fb520b371ff2.png)

**Delaware Wetlands - Not Visable**
Field Tool
![image](https://cloud.githubusercontent.com/assets/16919958/17341139/44426fc6-58c1-11e6-9650-8b1d1f950900.png)

BaseData.mxd
![image](https://cloud.githubusercontent.com/assets/16919958/17341155/5b5db8b4-58c1-11e6-9dfd-20294f58272f.png)

**Parcel Layer - Extent Ranges for layer and labels are not correct. Layer should be visible at 1:5000 and labels should not be visible until 1:1000.**
Field Tool
![image](https://cloud.githubusercontent.com/assets/16919958/17341280/d552d168-58c1-11e6-96ed-2542b1f53f4f.png)

BaseData.mxd at 1:1000
![image](https://cloud.githubusercontent.com/assets/16919958/17341458/b110ebea-58c2-11e6-9674-1bc46e138adb.png)

**Comment by leeensminger** [comment]
The base data mxd wasn't changed before published into the field tool.  I updated the Streams from 2 to 1.25.  All other items shown above are correct in the _BaseData_1_Primary.mxd_ provided for the mpk, so should be coming through as-is.

**Comment by leeensminger** [comment]
@mjuber-kci Was this also across multiple work areas?  Have you tested with another machine, too?
If not, @cstevenson1 Can you also test this and confirm this issue is universal?

**Comment by mjuber-kci** [comment]
Yes it is across multiple work areas and on other machines. There appears to be a disconnect between the mxd we provided and the field tool. The wetlands are so faint that they are basically unusable. The parcel labels are visible at a much too zoomed out extent causing the labels to be too jumbled and unusable.  Additionally the stream symbology in the mxd included a directional arrow, shown in the image above, that is not included in the field tool. @leeensminger what would you suggest as the next step to resolving this?

**Comment by mjuber-kci** [comment]
Additionally the same issues present with the Stream layer is also true for the Tax Ditch layer. 

Field Tool
![image](https://cloud.githubusercontent.com/assets/16919958/17894879/1197d526-6919-11e6-85cd-d0d158e020e9.png)

BaseData.mxd
![image](https://cloud.githubusercontent.com/assets/16919958/17894891/20f1e5a2-6919-11e6-8d82-69ee455f8673.png)

**Comment by leeensminger** [comment]
@mjuber-kci Apologies for the delay in responding.  I can assure you that the mxd you provided to us was not modified before imported to the field tool; the process of converting to an mpk (map package) must be tweaking the symbology internally during that process.  Next step would be for me to talk to Lu and see if he has any thought.  Pending that, we can start to change the symbology off of your mxd (i.e., take your tax ditch layer and thin it down even more) and reload base data.
