### ISSUE TITLE
Incorrect Stream Layer

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#199]
It appears that the stream layer in the Field Tool is still using the "Major Rivers and Streams" layer from First Map instead of the "Flowlines" as previously discussed.

**Comment by leeensminger** [comment]
@kanglu666 I have a new mpk and base data GDB that has this update.

New mpk: M:\2014\17141728.A\GIS\BaseData\Base_Data_Package\MPKs\BaseData_1_Primary3.mpk

Updated gdb: M:\2014\17141728.A\GIS\BaseData\Base_Data_Package\BaseData_20160628\DelDOTBase.gdb

The fields with the GNIS information is the same as the previous dataset "GNIS_ID", "GNIS_NAME"

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.4 release.

when you install the app, make sure copy the new BaseData_1_Primary.mpk in MPKs folder and replace the old one

**Comment by leeensminger** [comment]
@mjuber-kci This layer has been updated, but the label (when you are disconnected, working in a work area) still reads "Flowines".  Can you verify and confirm that the data is correct - if so, then we'll add an enhancement to update the label to read "Major Rivers and Streams"
