### ISSUE TITLE
Getting features into the Feature list?

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#2]
Is there another way to get features into the Feature List tab besides using Selection tab to query them? Additionally can you not have Structures, Conveyances, and BMPs in the Feature List at the same time?

**Comment by leeensminger** [comment]
The Select by Map tool (white arrow in the toolbar) should allow you to select multiple features and display them in the Feature List.  However, this does not seem to be working at this time.

We can confirm after the Select by Map tool becomes functional, but the system should allow you to have multiple feature types in the Feature List.

**Comment by mjuber-kci** [comment]
Select by Map tool is still not functional.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by leeensminger** [comment]
This issue should focus on the Select by Map tool.  For the question regarding multiple features in feature list, reference #149

**Comment by cstevenson1** [comment]
Still does not appear to be functioning

**Comment by kanglu666** [comment]
Select by Map tool is now functional. will be ready for testing in version 1.1 release
