### ISSUE TITLE
Greyed out fields are still required for pipe end inventory

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#201]
I created a pipe end and selected Is Outlet = No on the first page of the inventory form. Discharge Downstream Type and Ownership Downstream were greyed out, as they should be. However, when saving the structure, a notification popped up stating that all inventory fields need to be filled out. I then changed Is Outlet to YES and filled in Discharge Downstream Type and Ownership Downstream and the structure was able to be saved. When Is Outlet = No, the two greyed out fields should not be required. 

![image](https://cloud.githubusercontent.com/assets/16919958/17702406/bfeeb05a-639b-11e6-8284-52f05d9a8a6e.png)

![image](https://cloud.githubusercontent.com/assets/16919958/17702419/d3907b20-639b-11e6-9bb9-1369e048de2d.png)

**Comment by kanglu666** [comment]
Discharge Dstrm Type and Ownership Dstrm fields are required in database。
will be set value N/A when they are grayed out.
ready for testing in version 1.4 release
