### ISSUE TITLE
GNIS ID and Stream Comments do not clear.

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#202]
I created a Pipe conveyance and selected Yes for Conveyance Stream. I then selected the stream and it filled in GNID ID and Stream Comments correctly. I then changed Conveys Stream to No. GNIS ID and Stream Comments greyed out like they should but they did not delete the information within the fields. 

![image](https://cloud.githubusercontent.com/assets/16919958/17703141/a6830d8e-639e-11e6-92ba-46bc42be07c6.png)

![image](https://cloud.githubusercontent.com/assets/16919958/17703174/c180badc-639e-11e6-9443-bdcbb5b891be.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.4 release
