### ISSUE TITLE
WQ Investigation Report Type

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#204]
On the first page of the WQ Investigation, Report Type, Reported By, and External Report Type are greying out as they should when Investigation Reason = Targeted. However, even though Report Type is greyed out, it is being populated with Miscellaneous. This field should be left blank when greyed out, or if the field is not nullable, a new domain value of N/A needs to be added to be used when Report Type is greyed out. 

![image](https://cloud.githubusercontent.com/assets/16919958/17708270/4aea465e-63b2-11e6-8a4e-7e93c32d49c4.png)

![image](https://cloud.githubusercontent.com/assets/16919958/17708330/83d8ede4-63b2-11e6-8caf-0357abdf0b3b.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.4 release
