### ISSUE TITLE
Inspection Type for WQ Investigations

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#206]
On the first page of the WQ Investigation, the field "Inspection Type" can be removed, it is not needed.

![image](https://cloud.githubusercontent.com/assets/16919958/17709695/3b13a436-63b8-11e6-99ba-762573f22418.png)

**Comment by cstevenson1** [comment]
not enough value to invest resources in fixing. users will continue to populate field
