### ISSUE TITLE
Investigation Reason of Targeted

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#21]
If "Targeted" is selected for Investigation Reason, then Reported By and External Report Type should grey out. 

![image](https://cloud.githubusercontent.com/assets/16919958/12725901/eaf90092-c8e2-11e5-8948-1deaa8f58304.png)

**Comment by kanglu666** [comment]
"Reported By and External Report Type" need to be set to nullable = true in database

**Comment by leeensminger** [comment]
will be available in next database release

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release
