### ISSUE TITLE
Update workflow for Guardrail Culvert

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#213]
There's a new Conv_Type of Guardrail Culvert.  This needs needs to display and behave the same as a regular pipe (Conv_Type = Pipe).

Possible enhancement, pending LOE.

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.4 release

**Comment by cstevenson1** [comment]
Appears to work but does not display on the map. 

Guardrail Culvert (Selected in Feature List)
![image](https://cloud.githubusercontent.com/assets/16919898/18682044/b70376f2-7f38-11e6-81bf-e957e472be3b.png)

Same Guardrail Culvert (Not Selected in Feature List)
![image](https://cloud.githubusercontent.com/assets/16919898/18682140/1887845e-7f39-11e6-8a22-de54ea0ead71.png)

**Comment by cstevenson1** [comment]
Guardrail Culvert is not listed in the TOC, please let us know if you need the symbology for this.

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.0 release
