### ISSUE TITLE
Photos Should Be Hidden After Use

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#215]
After a photo is added to the database, the photo should be "hidden" from the user's view or at least grayed out to indicate it has already been used. This automatically occurs in our current field tool and benefits our workflow and field staff greatly. All photos should also have the ability to be "unhidden".

Current View from the Field Tool
![enhancement 1](https://cloud.githubusercontent.com/assets/16919898/17907951/2dd76c5a-694c-11e6-80e5-929cf172775c.JPG)

**Comment by leeensminger** [comment]
@kanglu666 Please review possibility to hide photos.  We have a table in the database that should assist with this process.  Do not investigate possibility to "unhide" - this is a modification from the requirements, and will be added to the Enhancements list.

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.4 release
