### ISSUE TITLE
Acceptance Date Does Not Save

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#217]
I created a conveyance and filled out the Acceptance Date as shown in Snip 1. I then continued to inventory additional features. I then went to reopen the conveyance so I could add photos and noticed the Acceptance Date had changed to the current date as seen in Snip 2. Could not verify if it is also an issue for structures because I was unable to reopen a structure.

Snip 1
![image](https://cloud.githubusercontent.com/assets/16919898/17933416/06d695b8-69e2-11e6-90bd-d920d8e9a827.png)

Snip 2
![image](https://cloud.githubusercontent.com/assets/16919898/17933511/55e847fa-69e2-11e6-9e92-ab08a3309f96.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.4 release
