### ISSUE TITLE
Having GPS enabled affects conveyance display on map

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#219]
I created a handful of structures and conveyances as seen in the first snip below with the GPS enabled. I reopened a conveyance, updated the Acceptance Date since it had been changed to the current date, clicked save, and then the conveyance disappeared from the map (area circled in red). I tried again on another conveyance but did not update any info, just clicked save after reopening it and that conveyance also disappeared from the map. However, if I went to the feature list, the conveyance was still listed as shown in the second Snip. I did not make the same observation though when the GPS was disabled (conveyance would stay visible on map). I then completed a sync at the end of the day (yesterday) and created a work area today containing those features on another toughbook (not connected to the GPS). I noticed if I reopened a new conveyance, I had no issues but if I reopened a conveyance created yesterday when I was having issues that the pipe would disappear from the map.

![image](https://cloud.githubusercontent.com/assets/16919898/17934350/9d56ea3a-69e5-11e6-9b66-e16362b97095.png)

![image](https://cloud.githubusercontent.com/assets/16919898/17934358/ac962628-69e5-11e6-9fab-392db14c952b.png)

**Comment by leeensminger** [comment]
These conveyance IDs seem to be involved with this problematic situation:
0207000030
0207000033
00207000027

**Comment by kanglu666** [comment]
no issue found, please testing in version 1.4 release.
if the issue happens, when can do a screen share to work it out.

**Comment by leeensminger** [comment]
I also attempted to recreate, and could not.  Likely, the work area somehow got corrupted.  Keep an eye on the issue, and let us know if you are able to recreate it.

If you cannot recreate it after a few tries, please close this issue, and continue to monitor in the future.

**Comment by cstevenson1** [comment]
No issues so far. Will continue to monitor and keep an eye out for things corrupting the work area.
