### ISSUE TITLE
External Report Type not required

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#22]
External Report Type should grey out if "MS4 Field Crew" is selected for Reported By.

![image](https://cloud.githubusercontent.com/assets/16919958/12726019/5cde748a-c8e3-11e5-989b-a45148e7d141.png)

**Comment by kanglu666** [comment]
"External Report Type" field is a required field in database, need it to be "nullable" = true to fix this item

**Comment by leeensminger** [comment]
will be updated in next database release
