### ISSUE TITLE
Reopening Structures Causes Crash

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#220]
During field testing yesterday, I inventoried a closed drainage system containing pipe ends, inlets, and pipe conveyances. After completing the initial mapping I went to reopen a structure so I could add photos and the information for the structure would not open. The below message appeared, causing the field tool to close.

![image](https://cloud.githubusercontent.com/assets/16919898/17935161/51bd8b9e-69e8-11e6-86b4-5b04a49f1db3.png)

**Comment by kanglu666** [comment]
We made some map services changes for testing the Web viewer.
that map services changes cause this issue.
i'm change the map services back, please check out an new work area and test it.
