### ISSUE TITLE
Map Rotates When GPS is Enabled

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#222]
Upon connecting the field tool to the GPS, the map began to rotate. The forms nor the screen itself rotated, only the map display spun. It seemed to stop after approximately a minute so maybe it was due to the GPS searching for satellites/locking in. We do not want the map to rotate in these circumstances. I have a video I can email if needed.

**Comment by leeensminger** [comment]
V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LEE\DelDOT\Rotating Map Video

**Comment by leeensminger** [comment]
@cstevenson1 to retest with other Map Mode settings... default, navigation, off, and see the results

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.4 release

i have set the GPS mode to "default" which means your GPS location will always be the center of the map.

you can manually set it to "off" : map will do nothing when your GPS location change.
you can manually set it to "navigation" : map will affected by the GPS location update.(rotate, etc)
you can manually set it to "default" :  your GPS location will always be the center of the map.

**Comment by cstevenson1** [comment]
GPS mode/Map Auto Pan Mode appears to be set to "Off" instead of "Default" but this should be fine.
