### ISSUE TITLE
Unhide photos from selectable photos

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#223]
In #215 , @cstevenson1 identified that the ability to hide or unhide photos that have been "used" by the user would be useful.  The original requirements state that we should hide photo that have been selected.

This enhancement speaks to optionally showing photos that have already been selected (and therefore, "hidden" from view from the user).

**Comment by cstevenson1** [comment]
No fix necessary. This is currently being handled through file explorer view settings.
