### ISSUE TITLE
Update Identify workflow

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#228]
The Identify tool has the following workflow steps.  Remove steps 2 and 3, they're unnecessary.
1. Click "I" toolbar button.
2. Click the "OK" at the popup message (if first time)
3. Click the "I" toolbar button again.
4. Select a feature layer.
5. Draw box on the map to identify features.

**Comment by cstevenson1** [comment]
Not enough value in bug to invest resources in fixing it
