### ISSUE TITLE
Structure Form Does Not Show Properly After Creating Barrel Conveyance Work Order

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#230]
After testing bug #200 and closing the issue because the two forms were no longer overlaid, I proceeded to create a new Structure and saw the work order barrel conveyance form was shown below the normal structure location form.  

![image](https://cloud.githubusercontent.com/assets/16919898/18673666/9e16cc02-7f1a-11e6-871c-fd5d4f64bac7.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.0 release
