### ISSUE TITLE
Unable to Add Lab Results on PID points

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#231]
Unable to add lab results on WQ Investigations for PID Points. I selected Sent to Lab = Yes on Page 4 of the WQ Investigation however I cannot click on the  +New Lab Sample (as if it was greyed out).

![image](https://cloud.githubusercontent.com/assets/16919958/18683117/ecbffd0c-7f3c-11e6-9e7a-869ad675c074.png)

**Comment by mjuber-kci** [comment]
Upon further investigation, when you initially create the PID point, you cannot add a lab sample but if you close the PID point and then reopen it, you can then add the lab sample to the WQ Investigation.

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.0 release
