### ISSUE TITLE
When WQ Investigation Field Form Not Required fields

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#232]
On page 2 of the WQ Investigation form, highlighted fields should not be required. 

![image](https://cloud.githubusercontent.com/assets/16919958/18713780/81c75702-7fe1-11e6-88b0-c3f85a37020b.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.0 release.
