### ISSUE TITLE
Photo Comments Should Not be a Required Field

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#233]
When attempting to attach a photo to a swale conveyance, I was unable to unless I entered a value in the photo comments. This however was not the case with the pipe conveyance photos (did not require a comment). No 'photo comments' should be required. 

![image](https://cloud.githubusercontent.com/assets/16919898/18720820/a58be2a6-7ffb-11e6-8dd3-1be899ae71a2.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.0 release

**Comment by cstevenson1** [comment]
While testing issue #250 I observed the above issue was occurring again (Snip 1). I also noticed that the comment I entered carries to the next inspection I create (Snip 2 and 3). If I manually delete the text from the photo comments field, on the next inspection the pop up box will not appear and there is no text in the photo comments field (I'm guessing the photo comment still carried over (as blank) but since it wasn't null, the pop up box didn't show?). 

Snip 1
![image](https://cloud.githubusercontent.com/assets/16919898/20316998/35f19212-ab32-11e6-9afd-26fb085c5f96.png)


Snip 2 (First new inspection created - photo comment was entered)
![image](https://cloud.githubusercontent.com/assets/16919898/20317361/bb0d5552-ab33-11e6-8e20-62adf6d3b26c.png)

Snip 3 (Second new inspection created - no photo comment was entered)
![image](https://cloud.githubusercontent.com/assets/16919898/20317402/dc7a032a-ab33-11e6-95ee-007fa7d1917e.png)

**Comment by impittman** [comment]
@kanglu666 please see @cstevenson1 comments from 11/15/2016. This provides a detailed account of the issues experienced. 

@cstevenson1 if the Photo Comments should not be required, do you want the "Note" portion of this form below deleted:
![image](https://user-images.githubusercontent.com/16418393/53991409-87726900-40f8-11e9-9b0f-36e8f52f913a.png)

**Comment by kanglu666** [comment]
updated in local

**Comment by cstevenson1** [comment]
I was able to successfully save/sync without populating Photo Comments for a photo on a swale inspection. Please push to prod

![image](https://user-images.githubusercontent.com/16919898/54944449-e19d6780-4f09-11e9-9a3e-0e4d9830be9d.png)

**Comment by leeensminger** [comment]
@kanglu666 please add to prod release when the time comes

**Comment by cstevenson1** [comment]
Staff is able to save swale inspection photos without a comment so this must have already been pushed to prod
