### ISSUE TITLE
Display Issues After Changing Conveyance Type

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#234]
I created an open drainage system and then re-opened a conveyance so I could change the conveyance type. I hit save and the conveyance disappeared from the display (see snip 1). I then tried on another conveyance and the symbology changed with the conveyance type update as it should (see snip 2). The second observation seems to be the anomaly since 3 of the 4 conveyances disappeared when I changed the conveyance type as seen in Snip 3.

Snip 1
![image](https://cloud.githubusercontent.com/assets/16919898/18725924/3663dcf2-8010-11e6-8e53-7d3fb97519a5.png)

Snip 2 (Before)
![image](https://cloud.githubusercontent.com/assets/16919898/18726068/d042de2c-8010-11e6-9f45-092570341c6f.png)

Snip 2 (After)
![image](https://cloud.githubusercontent.com/assets/16919898/18726098/e80b43b4-8010-11e6-96fd-f29c2f459b65.png)

Snip 3

![image](https://cloud.githubusercontent.com/assets/16919898/18726171/371be9b8-8011-11e6-99ad-584e160554af.png)

**Comment by kanglu666** [comment]
please testing in version 2.0 release

**Comment by cstevenson1** [comment]
Still not working properly. I switched the conveyance type for a conveyance I had just created and the symbology adjusted accordingly. However, when I switched the conveyance type for a conveyance that was pre-existing (from migrated data), the conveyance disappeared. I had switched the conveyance type from hydraulic connection to driveway culvert. I then tried switching a pre-existing pipe to driveway culvert and made the same observation. I tried a couple more times and the conveyances continued to disappear. I then used 'Select by map' to try and re-open the conveyance I created earlier and had successfully changed the conveyance type for to notice that multiple conveyances were listed even though my selection box only contained the one pipe (the extra conveyances listed appear to correspond with the pre-existing conveyances that I tried to change the conveyance type for). 

![image](https://cloud.githubusercontent.com/assets/16919898/19858750/19f96722-9f59-11e6-8f3f-cfe228882e76.png)

**Comment by leeensminger** [comment]
Recreated with the following steps:

1. Create 3 new structures
2. Create new swale (swale 1) between structure 1 and structure 2
3. Create new swale (swale 2) between structure 2 and structure 3
4. Select by map to select **swale 1**.  Edit, and change swale to Pipe.  Populate required fields and save.
5. Geometry of swale 1 disappears.

Could not recreate with other circumstances.  Please start here and we'll review.

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.1 release
