### ISSUE TITLE
Work Area Sync Message

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#236]
I created a work area on Tuesday and it was working fine however when I tried to sync the work area today, a message pops up stating that the work area replica does not exist on the server.

Message when syncing
![capture2](https://cloud.githubusercontent.com/assets/16919958/18762432/b9e54748-80d6-11e6-80be-8f810d0198cd.PNG)

Work Area Opened
![capture1](https://cloud.githubusercontent.com/assets/16919958/18762425/b5b1a9aa-80d6-11e6-8434-21e4d4eb2349.PNG)

**Comment by kanglu666** [comment]
this message means your local work area copy has been dropt on the server side by someone else.

please test on version 2.0 release

**Comment by leeensminger** [comment]
A function of active development and simultaneous active testing.  Please monitor for repeated occurence.

**Comment by mjuber-kci** [comment]
Will continue to monitor and will reopen the issue if necessary.
