### ISSUE TITLE
BMP Inventory Photos - Does not clear

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#237]
When attaching BMP Inventory Photos, the photos assinged from the previous BMP Inventory Photos tab do not clear when creating a new BMP.  If you delete the photo it will delete the photo from the previous BMP Inventory tab!

![new inspection - inventory photos from last inspection](https://cloud.githubusercontent.com/assets/16919984/18789619/9c26a7d0-8179-11e6-8abe-1443739e1d25.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.0 release

**Comment by mortynsky** [comment]
This has been fixed.
