### ISSUE TITLE
Cannot create Inspection if you change Structure Type

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#239]
I create a structure with Structure Type = Inlet, filled out all Location and Inventory information and saved the structure successfully. Then I changed the Structure Type = Culvert Point and saved the structure successfully. Then I tried to create an inspection on the culvert point and a message popped up stating "Structure Type changed, must save current Structure First". I selected the OK button and saved the structure again successfully but the message continued to appear when attempting to create an inspection. However if you close out of the structure, and then reopen it, you can then create an inspection.

![image](https://cloud.githubusercontent.com/assets/16919958/18920310/04d1e904-856f-11e6-86ea-1c7122b660e8.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.0 release
