### ISSUE TITLE
Measure tool needs feet as a unit

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#24]
Measure tool should have feet as the default unit for distance.

**Comment by mortynsky** [comment]
Can we have the same, "Length" and "Area" options that are currently available in the existing application?

New field Length = Old Distance

![distance](https://cloud.githubusercontent.com/assets/16919984/13018200/404da636-d196-11e5-817c-2f9a68dc1b8d.JPG)

Area

![area](https://cloud.githubusercontent.com/assets/16919984/13018204/47f866fa-d196-11e5-8e19-6ee14dbb6cd3.JPG)

**Comment by leeensminger** [comment]
We should be providing options for units of measure, as shown in mortynsky's comment.

**Comment by kanglu666** [comment]
options added, ready for testing in next release

**Comment by cstevenson1** [comment]
New Measure Tool
![image](https://cloud.githubusercontent.com/assets/16919898/13853259/529c2ab8-ec3c-11e5-9b14-b21f3c6a1424.png)

Old Measure Tool
![image](https://cloud.githubusercontent.com/assets/16919898/13853461/33c8f688-ec3d-11e5-8254-c5b80f5cc421.png)

 Acres is missing as a unit option for measuring area.

**Comment by leeensminger** [comment]
@kanglu666 Add Acres for Area measurement

**Comment by kanglu666** [comment]
Acres added, ready for testing in next release

**Comment by cstevenson1** [comment]
all units have been added except hectares which is not needed at the time
