### ISSUE TITLE
Buffer work area extent before download

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#240]
Use case:  user downloads a work area.  A conveyance is intersected by the work area boundary, so the upstream structure comes down with the work area, but the downstream structure does not.  User edits the conveyance geometry, and during sync the relationship to the downstream structure is lost.

Solution:  BC suggested we buffer the work area in the background (not known to user) and enlarge the work area extent.  So when user edits the same conveyance (as described in the use case), the downstream structure relationship is not lost at sync.  The downstream structure should remain hidden from user if possible.

**Comment by kanglu666** [comment]
updated, extend 300 feet buffer for the work area.
ready for testing in version 2.0 release

**Comment by cstevenson1** [comment]
this has since been fixed
