### ISSUE TITLE
When structure geometry modified, associated conveyance geometry should be refreshed

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#242]
When a structure is moved, the associated upstream and downstream conveyances should be redrawn in the map to show that they are connected to the structure.  In the image below the blue dot was moved.  The blue lines represent how the conveyances should be redrawn.

Sourced from #102 

![image](https://cloud.githubusercontent.com/assets/4103847/19386358/ba388e50-91e1-11e6-9266-23ef7fa69240.png)

**Comment by kanglu666** [comment]
i will mark this as enhancement, if we need to this function, it's a big effort
