### ISSUE TITLE
Unable to Delete Pipe Connection Point

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#247]
I created and saved a new structure with structure type=pipe connection. I then re-opened it and attempted to delete it but it did not delete. I successfully deleted a new culvert point and dummy node with no issues though.

Clicked Delete
![image](https://cloud.githubusercontent.com/assets/16919898/19853549/43e1eeec-9f40-11e6-8e92-2de7d4f27d53.png)

Normal Delete Message Pop-Up Box Appeared and Clicked 'Yes'
![image](https://cloud.githubusercontent.com/assets/16919898/19853569/6a137734-9f40-11e6-89c3-ce12bd43d986.png)

Structure was still on Screen
![image](https://cloud.githubusercontent.com/assets/16919898/19853578/7fd4c85c-9f40-11e6-9f3d-e826f2433e92.png)

The snip below is the message box that appeared after clicking 'Yes' to delete the other structure types but never appeared for pipe connection. 
![image](https://cloud.githubusercontent.com/assets/16919898/19853616/b727d3ee-9f40-11e6-9ccb-162cd8422d98.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.1 release
