### ISSUE TITLE
Time Stamp is Incorrect for Barrel Conveyance

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#248]
I created and saved a new barrel conveyance. I then re-opened and noticed the time stamp was 4 hours off as shown in the snip below.

![image](https://cloud.githubusercontent.com/assets/16919898/19854747/064db5b4-9f47-11e6-94c4-62875afdad60.png)

![image](https://cloud.githubusercontent.com/assets/16919898/19854790/4c625226-9f47-11e6-89cd-a408fc352d17.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.1 release
