### ISSUE TITLE
Inventory Tab did not Save after updating conveyance type

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#249]
1. I opened an existing conveyance using the 'Select by map' feature
![image](https://cloud.githubusercontent.com/assets/16919898/19857029/744a1750-9f52-11e6-9143-60980640f2b4.png)

2. I changed the conveyance type from hydraulic connection to pipe
![image](https://cloud.githubusercontent.com/assets/16919898/19857060/93212a56-9f52-11e6-9842-2702fd26029f.png)

3. I updated the inventory tab and clicked 'Save'
![image](https://cloud.githubusercontent.com/assets/16919898/19857083/b91158ee-9f52-11e6-8ce0-3d8435b49858.png)

4. I then re-opened the conveyance and the conveyance type had saved but the inventory information had not
![image](https://cloud.githubusercontent.com/assets/16919898/19857125/e3ae54d0-9f52-11e6-8ecf-fd3eb478126d.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.1 release
