### ISSUE TITLE
Ownership Downstream not needed on the Outfall Form

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#25]
Ownership Downstream is not needed on the Outfall Form. 

![image](https://cloud.githubusercontent.com/assets/16919958/12728373/8c7a8a10-c8ef-11e5-8f1d-d94e3aafccf1.png)

**Comment by leeensminger** [comment]
Lu, this will be provided for in the database model update list.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
