### ISSUE TITLE
New Inspection Shows Picture from Old Inspection on Same Conveyance

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#250]
Similar to issue #3 

I opened a pre-existing swale (migrated data) which already had an inspection on it. I then viewed the inspection and made no changes so I clicked cancel. I then proceeded to create a new inspection and noticed the photo from the pre-existing inspection was showing under the inspection photos of the new inspection. If I delete the photo from the new inspection, it also deletes the photo from the old inspection. 

Old Photo on New Inspection
![image](https://cloud.githubusercontent.com/assets/16919898/19864077/0a7d908e-9f6d-11e6-9b0e-7815c5f88318.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.1 release
