### ISSUE TITLE
Integrate new base mapping MPK

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#251]
M:\2014\17141728.A\GIS\BaseData\Base_Data_Package\MPKs\BaseData_1_Primary_20161102.mpk

You will need to update layer order.  Two new layers are added in spots 2 and 3.  

Please advise if this level of effort is > 1 day.

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.1 release
