### ISSUE TITLE
Switching Photo Category Corrupts Photos Section of Inspection

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#252]
I opened an existing swale point and then modified the geometry to move the position. I saved the structure and moved on to another point. I then re-opened the swale point that I modified the geometry for and created an inspection. I entered a photo category and attached a photo on the 5th page of the inspection form. I then changed the photo category for the photo I just attached and attempted to save then exit the structure. The field app crashed which was not alarming but when I relaunched the field tool, I navigated back to that same structure and was unable to get to the 5th page of the inspection form (photo section) without the field tool crashing. Everything else continued to work properly but I could not access the photos for that one structure after modifying the photo category. 

Within the same work area I tried to replicate the issue (on other structures) and it did not crash that initial time from just changing/saving the new photo category but crashed after I reopened the structure and tried to navigate to the photos page. I had the same results if I did not modify the geometry. I also had the same results if I changed the photo category by either using the update button then saving or just saving.

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.1 release

**Comment by cstevenson1** [comment]
Swale Point Inspection
![image](https://cloud.githubusercontent.com/assets/16919898/20318545/a7cfc0ba-ab38-11e6-8e5e-75c8aba1cb62.png)
