### ISSUE TITLE
Pipe End Inventory form not properly saving

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#255]
I opened a migrated pipe end structure, updated the inventory tab and successfully saved the structure. I then closed out of the structure and reopened it. The top 3 fields saved successfully however, the bottom two fields did not. When the 2 fields are greyed out as N/A, the N/A doesn't save. However when they aren't greyed out, and have a value, they save as N/A.

Saved Sucessfully with bottom two fields greyed out as N/A
![image](https://cloud.githubusercontent.com/assets/16919958/20277476/c2733f84-aa6e-11e6-929d-6005a5c5b5fa.png)

Reopened Structure and bottom two fields are no longer N/A
![image](https://cloud.githubusercontent.com/assets/16919958/20277533/f7428670-aa6e-11e6-8047-feb300bb8580.png)

Saved structure successfully with bottom two fields filled out
![image](https://cloud.githubusercontent.com/assets/16919958/20277660/86f0cd22-aa6f-11e6-986c-fa2b8f347954.png)

Reopened structure and bottom two fields are N/A
![image](https://cloud.githubusercontent.com/assets/16919958/20277694/a25878f8-aa6f-11e6-819b-db1bf79a4d25.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.2 release

**Comment by leeensminger** [comment]
This is now being written correctly to the database, but when you follow the sequence below, the field tool does not show the NA values, and subsequently will not allow a save on the PIPE END.
- In Pipe End Inventory, set Is Outlet = No.  The application correctly disables the fields "Discharge Downstream Type" and "Ownership Downstream", and sets the values for these two fields to "N/A" 
- Save structure, and sync.  The database is written correctly with NA for these two fields.
- Close, and reopen the structure in the field tool.  The same two fields (Ownership Downstream, and Discharge Downstream Type) are disabled (which is correct), but they are blank.  The field tool does not allow a save at this point, and throws the message that all inventory fields are not populated (even though they are NA in the database).

**Comment by kanglu666** [comment]
updated, ready for testing
