### ISSUE TITLE
Inventory Form Display Issue Followed by Field Tool Freezing

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#256]
I created two culvert points approximately 12 feet apart from one another. I then attempted to draw a pipe conveyance between them but the two points were within the point buffer and I could not tell them apart because they had the same ID number. It resulted in the message saying I could not use the same point for the upstream and downstream node (which is good). I then modified the downstream node for the conveyance and everything seemed fine. I then attempted to open a previously existing (migrated data) pipe end to notice that the inventory form of the culvert point was overlaying the inventory form of the pipe end (snip 1). I closed the structure and re-opened it and the two forms were no longer overlaying. I then tried to reproduce the issue but upon re-opening a different pipe end, the application froze (snip 2).

Snip 1
![image](https://cloud.githubusercontent.com/assets/16919898/20277421/7b6be208-aa6e-11e6-8368-8efbeedbfc1d.png)

Snip 2
![image](https://cloud.githubusercontent.com/assets/16919898/20277621/4f0e2134-aa6f-11e6-9b11-6ad3352cd3dd.png)

**Comment by cstevenson1** [comment]
Upon further attempts to re-create, we believe the issue is with the culvert point. Within a new work area, we successfully created and saved a new culvert point. We then attempted to open a different structure and the inventory forms were overlaid.

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.2 release
