### ISSUE TITLE
Stream Distance tool is not functional

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#26]
Tool to measure the stream distance and to populate the GNIS Name and GNIS ID is not functional.

![image](https://cloud.githubusercontent.com/assets/16919958/12728427/d0149da6-c8ef-11e5-85c6-353d1152e122.png)

**Comment by leeensminger** [comment]
See issue #53

**Comment by kanglu666** [comment]
updated, ready for testing in next release
