### ISSUE TITLE
Sync error code '400'/ structures not being assigned unique ID

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#260]
Yesterday I downloaded a work area and made edits (added new structures). Melissa then downloaded a work area yesterday that overlapped the area I was working in and made edits. At the end of the day she performed a sync and received a message that it was successful. I then tried to sync this morning and received the error message below. When Melissa resynced (no error message) and opened the work area this morning she noticed that her new structures were present but they had not been assigned unique ID numbers. 

![image](https://cloud.githubusercontent.com/assets/16919898/20308048/444522b0-ab10-11e6-93f8-e25d2ed0e729.png)

**Comment by kanglu666** [comment]
deldot GP script updated, ready for testing inversion 2.2 release

**Comment by cstevenson1** [comment]
Did not receive the error message but will continue to monitor. However, the ID numbers are still not being assigned. Melissa created the structures circled in the snip below yesterday and I generated a new work area today containing them and as shown they do not have unique numbers assigned. Melissa made the same observation when she did a sync on her work area today.

![image](https://cloud.githubusercontent.com/assets/16919898/20844648/e5e824b0-b88e-11e6-86a7-e24d1953bc04.png)

**Comment by leeensminger** [comment]
We already documented this via email.  This should be working now, as of Friday morning.  All structures in the structures feature class have a valid, complete, unique structure number, so the numbering issue is resolved.

Please create new structures today, sync, and confirm tomorrow morning.

**Comment by cstevenson1** [comment]
I received the 400 error code message again today after clicking sync.

I was able to successfully sync other work areas immediately before and after the error message so I don't believe it was a network issue. The work area that generated the error message was newly created from this morning and I had only made one change in it. The change I made was adding a new Swale Point with IS Outfall = Yes and creating an inspection for that point. Before creating the inspection, I saved the structure as required. After creating the inspection, I made an update to the the location tab, clicked save again and received the following 3 pop up boxes in sequential order.

Box 1
![image](https://cloud.githubusercontent.com/assets/16919898/21566222/0c8050d4-ce6f-11e6-8746-3ec628d0f136.png)

Box 2
![image](https://cloud.githubusercontent.com/assets/16919898/21566225/164ed914-ce6f-11e6-9af7-cb5b1276454a.png)

Box 3
![image](https://cloud.githubusercontent.com/assets/16919898/21566230/25903fe4-ce6f-11e6-81e7-3dd5cd25e0b1.png)

I noticed box 3 had said "added", when it should say updated. I was unsure if it was writing to the database correctly. This is when I returned to the main page to try and sync but received the 400 error code message. Since I thought it may have something to do with the outfall aspect of the structure, I had Melissa replicate what I did in a work area of her own and she also received the 400 error message. This was the first sync issue she had today.

**Comment by kanglu666** [comment]
"Structure Outfall Added" message updated. 
working on the sync issue now,  i think it's the database issue.

**Comment by kanglu666** [comment]
after testing, this was a database issue, and updated, ready for testing in version 3.1 release

**Comment by cstevenson1** [comment]
Have not received the sync error since version 3.1 release but will continue to monitor.
