### ISSUE TITLE
Need ability to create barrel conveyance using all conveyance types with pipe segments

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#262]
I tried creating a barrel conveyance using a roadway culvert conveyance and was unable to because "No conveyance pipes in the selection area! Please try again." (Snip 1). All conveyances that can have pipe segments (pipes, roadway culvert, driveway culvert, guardrail culvert) should be able to be used to create a barrel conveyance. This is at least a high priority enhancement, see Lee

Snip 1
![image](https://cloud.githubusercontent.com/assets/16919898/20313442/f49f9a32-ab24-11e6-8ab2-bb2f61470638.png)

**Comment by cstevenson1** [comment]
CONVEYANCE_NUM = 0110037109 is an example. It appears to have migrated properly in the migrated database (2 conveyances with conveyance type=roadway culvert, 2 pipe segments, 2 barrels, 1 barrel conveyance) and the geometry is there. In the field tool however, the two geometries are there but if you try to search for the barrel conveyance using the advanced query, the result does not show. even though it is within my work area

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.0 testing
