### ISSUE TITLE
Re-Inspection "Action Items" form doesn't reset

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#263]
When doing a re-inspection of a new BMP, the "Action Items" menu does not collapse for parameters that you placed an action on during the previous inspection.  There is no data there but the forms should always default to the, "Parameter Scoring" tab.  

![inspection action doesn t reset](https://cloud.githubusercontent.com/assets/16919984/20316754/3f199570-ab31-11e6-995f-948b6fb69162.JPG)

**Comment by cstevenson1** [comment]
not enough value to complete, closing bug
