### ISSUE TITLE
BMP Water Quality Treatment Parameter

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#266]
The "11. Water Quality Treatment Parameter" is a new parameter that we added during the database redesign.  When doing a re-inspection of a BMP on migrated data you need to select, "Yes, No, Unknown" from the "Inventory" tab.  If you select, "Yes" the Water Quality Treatment Parameter is still greyed out in the "Inspection" tab until you save, close, and re-open that inspection.  This should become editable in the "Inspection" tab as soon as you select, "Yes" under the "Inventory" tab.

**Inspection Tab**

![water quality treatment parameter](https://cloud.githubusercontent.com/assets/16919984/20320381/b026fa74-ab3f-11e6-8b4b-8e06fd08d559.JPG)

**Inventory Tab**

![water quality treatment parameter inventory tab](https://cloud.githubusercontent.com/assets/16919984/20320545/2e2809e0-ab40-11e6-8bd7-0f48fa48f9a5.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in version 2.2 release

**Comment by mortynsky** [comment]
This issue has been fixed!
