### ISSUE TITLE
Check Boxes for Outfall Component Inspections

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#27]
What is the purpose of the check boxes in the Outfall Component Inspection Form? 

![image](https://cloud.githubusercontent.com/assets/16919958/12728535/4b459fac-c8f0-11e5-8e09-614e02558c48.png)

**Comment by leeensminger** [comment]
This is probably a legacy item that can be removed.  The inventory tab indicates if the item (i.e., Outfall Protection, Defined Outfall Channel, etc.) are present at the outfall.  Those that are not present, as indicated in inventory, should be disabled in the inspection tab.  @kanglu666 please confirm there is no other functionality associated with these checkboxes in inspection tab.

**Comment by kanglu666** [comment]
check box in outfall inspection form have been removed. ready for testing in next release.
