### ISSUE TITLE
Spatial query sample message appears when you refresh

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#272]
I opened a pre-existing structure and noticed fields within the location tab were not filled out so I clicked select all and then 'Refresh Selected'. Upon doing so I received the spatial query sample error message shown below. 

![spatial query sample](https://cloud.githubusercontent.com/assets/16919898/20809500/3c3f1672-b7d4-11e6-9639-bdde8c69069d.JPG)

**Comment by leeensminger** [comment]
Resolved.

**Comment by cstevenson1** [comment]
I created a new work area and opened a pre-existing manhole. I selected the 3 fields I wanted to be populated and clicked Refresh Selected. I received the same error message as before. Melissa also experienced the same issue. 

![image](https://cloud.githubusercontent.com/assets/16919898/20892627/f9a5c9c6-badc-11e6-8452-43d893c00a34.png)

**Comment by leeensminger** [comment]
Attempted to reproduce the experience above and am unable to do so.  All overlays refresh correctly, whether its the 3 above, all overlays, or just 1.  

I believe you have already done so, but just to begin tracing this:  
The devices currently in use have the updated MPK file?
The work areas were generated after the MPK file was updated?
