### ISSUE TITLE
Selecting Problem Within Work Order Causes Crash

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#274]
I created a new culvert point and later re-opened it after I created additional points. I then proceeded to create a work order. I filled out 'Status, 'Immediate Action', and 'District' (district populated automatically) on page 1 and then I went to page 2. I tried to click the box next to 'Clear Vegetation' and then the field tool crashed as seen in the snip below. This was observed for new and existing structures. 

![image](https://cloud.githubusercontent.com/assets/16919898/20846270/e7a4f032-b896-11e6-8760-f4992821e5e4.png)

**Comment by leeensminger** [comment]
@kanglu666 This seems to occur when user clicks the checkbox for any item (not just clear vegetation).

@cstevenson1 Did you test work orders before?  When did you last successfully create a work order without this issue?

**Comment by cstevenson1** [comment]
@leeensminger Yes I know we have tested work orders in the past because we have had multiple issues with the work orders section that have been closed. I'm not exactly sure when we last successfully created one but I would say version 2.0 because I think version 2.1 testing focused on open bugs on our side and there were no work orders bugs to test for 2.1

**Comment by leeensminger** [comment]
Fixed.  Need to get new work areas.
