### ISSUE TITLE
Opening Existing Inspection for Culvert Point Causes Crash

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#276]
I created a new work area and used the select by map to open a culvert point. I then navigated to the inspection tab and noticed one previous inspection (8/23/12) existed for the structure. I then clicked on the green check mark under details to open the inspection and the field tool crashed. 

![image](https://cloud.githubusercontent.com/assets/16919898/20890897/abd7ed4c-bad6-11e6-9eda-11bd7430b43b.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.0 release
