### ISSUE TITLE
WQ Flow Characteristics carrying over

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#277]
I believe it may be a similar issue to #275.

I created a WQ Investigation with Sample Collected = Sample Collected (WQ#1) on page 2 which triggers the Flow Characteristics section to be available (working fine). 
![image](https://cloud.githubusercontent.com/assets/16919958/20891637/56b4591a-bad9-11e6-99a2-91c9024cd8a4.png)

I then created a second WQ Investigation on the same structure with Sample Collected = Not Collected - No Flow (WQ#2) which should grey out the Flow Characteristics information and it did. However, when I closed out of it and reopened WQ#1, then closed out of it, and reopened WQ#2, the Flow characteristics were no longer greyed out and the information from WQ#1 was populated in the Flow Characteristics of WQ#2. 
![image](https://cloud.githubusercontent.com/assets/16919958/20892068/acc29e42-bada-11e6-9573-9c870c3703c4.png)

Then I closed out WQ#2 and reopened it right away. The Flow characteristics were still populated with the values from WQ#1 but are now greyed out.
![image](https://cloud.githubusercontent.com/assets/16919958/20892149/ed505a44-bada-11e6-847b-213cbb6378a5.png)

I am unsure if it is just a display issue in the field tool or if it is writing to the database incorrectly.

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.0 release
