### ISSUE TITLE
When using Select by Map Tool, Selection List Clears

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#278]
When using the Geographic Filters, if you open a structure from within the list and use the Back button (circled in red), it takes you back to the previous list.
![image](https://cloud.githubusercontent.com/assets/16919958/20896812/75010d96-baed-11e6-8f4c-ac0f7a94c374.png)
![image](https://cloud.githubusercontent.com/assets/16919958/20897541/c1fb81a0-baf0-11e6-92fd-414360df9955.png)

When you use the Select by Map tool, and use the same Back button, it clears the Selection List generated from the Select by Map tool. The list should remain so that we don't need to use the Select by Map tool for every single structure we open. 
![image](https://cloud.githubusercontent.com/assets/16919958/20897384/1c79cb7e-baf0-11e6-8e28-0daa06cd0f12.png)

**Comment by cstevenson1** [comment]
same issue as #304
