### ISSUE TITLE
IDDE Photos Within Inspection Tab Carry Over to Next Inspection

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#279]
I opened an existing structure and navigated to the inspection tab. I clicked to add a new inspection and filled out all required fields on the first 3 pages. When I paged over to the 4th page, I observed the IDDE photo I had attached on the 4th page of the last inspection I created (different structure) was showing. However, if I saved and re-opened the inspection, the previous IDDE photo was no longer there. 

![image](https://cloud.githubusercontent.com/assets/16919898/20899584/04b3cb12-baf9-11e6-9baa-0db65c9fa053.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.0 release
