### ISSUE TITLE
Inspected Reason domain values

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#28]
Domain values need to be updated with latest list for Inspected Reason.

![untitled](https://cloud.githubusercontent.com/assets/16919958/12730202/db45d52e-c8f8-11e5-883a-d95752e42ff8.png)

**Comment by leeensminger** [comment]
@mjuber-kci Please provide the latest list.

**Comment by mjuber-kci** [comment]
This is the updated list for domain values for Inspected Reason for both Structures and Conveyances.

![image](https://cloud.githubusercontent.com/assets/16919958/13854843/da14b742-ec43-11e5-89ef-71d250c4b05b.png)

Not all of these domain values apply to both structures and conveyances and it would be extremely helpful if only the options that apply would be visible. The ones shaded in yellow apply only to structures, the ones in green apply to BOTH structures and conveyances, and the one in orange only applies to conveyance.

**Comment by leeensminger** [comment]
Updated to include two new domains that replace the old D_Reason:

![image](https://cloud.githubusercontent.com/assets/4103847/14154447/79cfa9f4-f68a-11e5-9d51-e8d71ba6e2e0.png)

**Comment by mjuber-kci** [comment]
It appears that the Inspection Reason for Conveyance Inspections is hitting the D_ReasonStructure instead of the D_ReasonConveyance

![image](https://cloud.githubusercontent.com/assets/16919958/20930982/85838454-bb9d-11e6-9488-beff94131ec1.png)

**Comment by leeensminger** [comment]
@kanglu666 PIPE_INSPECTIONS.INSPECTED_REASON appears to have the correct domain associated to it.  Please check in the services to confirm the fields and domains are correct.

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.0 release
