### ISSUE TITLE
Work Order Contact Record Not Deleting

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#281]
I created a work order and saved successfully. I then added a Contact record on page 4 successfully. I clicked on the record in the box below and tried to hit delete and it doesn't do anything.
![image](https://cloud.githubusercontent.com/assets/16919958/20931677/d647c3c6-bb9f-11e6-8922-77a05dd2bef5.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.0 release
