### ISSUE TITLE
Structure Photos and Pipe Inspection Go Away After Sync

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#282]
I used the field tool yesterday on the toughbook to conduct initial inventory - inspection (all new structures and conveyances) and a re-inspection (new inspections and updating information on migrated data). The issues were observed under both conditions. At the end of the day I synced both work areas with what appeared to be no issues (Snip 1). The next morning I had Melissa create two work areas that would include that two areas from the day before. The new inventory was there, unique IDs had been assigned, and the location/inventory information was correctly updated. However, when she went to a structure inspection, the photos I had attached were not there (Snip 2 shows what it looked like from the toughbook prior to the sync). She checked the 4th page of the structure inspection and also noticed that 'water quality inspection needed' was filled out as unknown but I had entered it as No in the toughbook (Snip 3). She then checked a pipe and observed that the pipe inspection I had created was not showing (Snip 4 shows what I created on the toughbook). 

Snip 1
![work area](https://cloud.githubusercontent.com/assets/16919898/21055396/47aa54be-bdff-11e6-9ad0-eba1cd4fa831.JPG)

Snip 2
![structure photo](https://cloud.githubusercontent.com/assets/16919898/21055515/a333065a-bdff-11e6-9a9d-b48e9dca505f.JPG)

Snip 3
![wq needed](https://cloud.githubusercontent.com/assets/16919898/21055563/e693a800-bdff-11e6-971c-d85588f3a702.JPG)

Snip 4
![conveyance](https://cloud.githubusercontent.com/assets/16919898/21055544/cb2cddd4-bdff-11e6-9c2e-dc66717a46ba.JPG)

Melissa will comment with the Snips of what she saw on her side after downloading the work areas the day after they were synced.

**Comment by mjuber-kci** [comment]
Here's what I observed on my side

Snip 1 
![image](https://cloud.githubusercontent.com/assets/16919958/21055834/0b57e9f2-be01-11e6-8287-0d7a71231246.png)

Snip 2
![structure_inspection_photos](https://cloud.githubusercontent.com/assets/16919958/21055855/2b2c5f9c-be01-11e6-8c7b-4750f4fe4982.JPG)

Snip 3
![wq_prelim](https://cloud.githubusercontent.com/assets/16919958/21055863/33555732-be01-11e6-8a4f-c69ca5c8bd31.JPG)

Snip 4
![conveyance_inspection](https://cloud.githubusercontent.com/assets/16919958/21055871/3ab33454-be01-11e6-83da-380df1185c03.JPG)

**Comment by mjuber-kci** [comment]
Structure 0111306905 should have 1 inspection record with 2 photos. The database is showing the inspection record however, the associated photo records are not there. 

Conveyance 0111306908 should have 1 inspection record with 2 photos as well. In the database, there is no inspection record associated to this conveyance and therefore no photo records. 

So it appears that it is writing to the database incorrectly and is not just a field tool viewing error.

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.0 release.

new fields added.
script updated
