### ISSUE TITLE
External Report Type is not greyed out upon reopening WQ Investigation

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#283]
I created a WQ Investigation with Reported by = MS4 Field Crew which greys out the External Report Type (as it should) (Snip 1). Then I saved and closed out of the WQ Investigation, When I opened it back up, External Report Type is no longer greyed out (Snip 2).

Snip 1
![image](https://cloud.githubusercontent.com/assets/16919958/21140805/ecd58dcc-c107-11e6-8b25-306af7297172.png)

Snip 2
![image](https://cloud.githubusercontent.com/assets/16919958/21140817/f9c1297e-c107-11e6-860e-f2a2ba52afe6.png)

**Comment by cstevenson1** [comment]
Only affecting a select number of scenarios but not affecting functionality. Not enough value to invest resources
