### ISSUE TITLE
Incorrect Cross Sectional Area for Box Pipe

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#284]
I updated the inventory for a pipe to have a shape of box and dimensions of 36 in x 36 in. The corresponding cross sectional area according to the field tool was 28.2 sq. ft but it should be 9 sq. ft. Not sure what calculation is being used here.

![image](https://cloud.githubusercontent.com/assets/16919898/21315990/b88c6c10-c5cc-11e6-862c-96c3016118b8.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.0 release
