### ISSUE TITLE
Cannot Open Pipe Inspection After Creating Barrel Conveyance from Roadway Culvert

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#287]
While in the process of testing bug #262, I created a new barrel conveyance from an existing roadway culvert conveyance with no issues (snip 1). I then proceeded to create a new barrel inspection for one of the barrels of the new barrel conveyance with no issues. I saved my changes and then used the 'Select by map' tool to open a pipe conveyance. I then navigated to the Inspection tab for that conveyance and attempted to open an existing inspection by clicking on the green check mark details button (Snip 2). The loading bar appeared for a very brief moment but the inspection did not open. I then attempted to create a new inspection for that same conveyance but I had to click the new inspection button twice to even get the inspection form to pop up. I then clicked the drop down for Inspected and changed the value from Unknown (the default value) to Yes. Immediately afterwards the form closed and returned me to the main inspection page that lists the historical inspections with no sign that I had attempted to create a new one (Snip 3). Melissa was able to replicate the bug using a different work area but the same process outlined above. 

Snip 1
![image](https://cloud.githubusercontent.com/assets/16919898/21527410/32afb136-ccf9-11e6-85ae-ea2b0bf34a0b.png)

Snip 2
![image](https://cloud.githubusercontent.com/assets/16919898/21527486/a443eaf6-ccf9-11e6-9bb3-a4699dbdec89.png)

Snip 3
View before the inspection form closed
![image](https://cloud.githubusercontent.com/assets/16919898/21527600/666a294c-ccfa-11e6-9adf-4aab6a99c9f4.png)

View after the inspection form closed
![image](https://cloud.githubusercontent.com/assets/16919898/21527627/8579a3ee-ccfa-11e6-9811-02b10cb56a8b.png)

**Comment by mjuber-kci** [comment]
Issue does not seem to be triggered by creating an inspection. I followed the same process as above minus creating an inspection, and got the same result. Additionally I repeated the process using a Pipe Conveyance to make the Barrel Conveyance and had the same outcome, meaning its not specific to Roadway Culvert Conveyances but Barrel Conveyances in general.

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.1 release
