### ISSUE TITLE
Remove Button Does Not Work In Barrel Conveyances

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#288]
The Remove button (Snip 1) within the Barrels/Conveyances tab of barrel conveyances does not function (nothing happens when you click it). The button is needed to remove conveyance pipes from a particular barrel. Pending level of effort, we may be able to mark as an enhancement and find a work around on the user side for the time being. 

![image](https://cloud.githubusercontent.com/assets/16919898/21529037/c70cd088-cd04-11e6-8932-cd5ffcbf7152.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.1 release
