### ISSUE TITLE
Advanced query produces no results for migrated barrel conveyances involving roadway culverts

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#289]
Related to issue #262. 

A multi barrel roadway culvert conveyance was migrated properly according to the migrated database (3 conveyance records, 3 pipe segments, 3 barrels, 1 barrel conveyance) and displays in the field tool properly with 3 geometries. However, when I tried to open the barrel conveyance by using the advanced query builder, no features were found. I will test barrel conveyances involving other conveyance types to see if the issue is specific to roadway culverts. The advanced query does work when you search for newly created barrel conveyances. Currently though, using the advanced query builder is the ONLY way to open a barrel conveyance so without this function, we cannot open, edit, or inspect existing barrel conveyances. 

![image](https://cloud.githubusercontent.com/assets/16919898/21530641/340f6848-cd10-11e6-8930-f38b8f370598.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.1 release.

note: all barrel conveyance and barrel will be bring down with the check out.

**Comment by cstevenson1** [comment]
I don't know if this will be sufficient since you won't be able to open the barrel conveyance unless you know its ID number. Since it has no geometry, it won't highlight in the map and cannot use the identify tool. The snip below shows a double barrel driveway culvert conveyance and the results from the advanced query to find the barrel conveyance. I could not determine which record corresponded to the barrel conveyance I was interested in by just scrolling through the massive list. If this ends up being the only issue in this release, we can discuss a work around such as finding the ID number back at the office and calling the field team with it so we can change this issue to an enhancement. 

![image](https://cloud.githubusercontent.com/assets/16919898/21728491/79351f48-d414-11e6-8b4a-a9645cea0a3c.png)

**Comment by leeensminger** [comment]
@cstevenson1 Let's take the workaround for the time being.  This will be very involved to fix, and there may be some retooling of barrel conveyances in the future anyway that may affect this.

**Comment by cstevenson1** [comment]
Issue has been discussed offline multiple times but to update bug...

Advanced query produces no results when you search a barrel conveyance by the number or by OBJECTID IS NOT NULL.  Therefore, barrel conveyances cannot be opened and edited in the field tool.

**Comment by cstevenson1** [comment]
Able to search for barrel conveyance based on ObjectID Is Not Null or by the Barrel Conveyance Number

![image](https://user-images.githubusercontent.com/16919898/32114346-4a199f56-bb11-11e7-9a59-93a4cad0539a.png)

However, see bug #324

**Comment by cstevenson1** [comment]
@leeensminger the UI appears to be working fine. You and I discussed possibly looking into updating the data since the conveyances making up the barrel conveyances were assigned the same ID but when we create new barrel conveyances, each conveyance has a unique ID
