### ISSUE TITLE
Identify tool does not work for Sussex County Contours

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#292]
Within my work area located in Sussex County, I went to the Identify Results tab and clicked the drop down to select Contours Sussex. I then clicked the identify button on the top task bar and selected the individual contour I wanted to identify but received no results. I went to a work area I had created in New Castle County and was able to successfully identify an individual contour from the Contours NewCastle layer. I was also able to identify contours within my Kent County work area. Melissa made the same observation. 

![image](https://cloud.githubusercontent.com/assets/16919898/21569378/443d619a-ce8a-11e6-87a8-798e623a6029.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.1 release
