### ISSUE TITLE
Ownership field for PID Point

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#296]
Add "Ownership" field for PID Point.

![image](https://cloud.githubusercontent.com/assets/16919958/21780244/d8a2ee9a-d678-11e6-9510-47ad76d9201f.png)

**Comment by leeensminger** [comment]
@impittman please spec out suggested field types, lengths, nullable y/n, and table location.  Then assign Christina to confirm.

**Comment by impittman** [comment]
This appears to be a 2 part Issue. One is adding a field to the database, and the other is to add a field to form.

**Database Field Suggestion:**
PID_POINTS.OWNER
TEXT
Character = 58 to match other Owner fields
Domain: D_Ownership
Nullable: Y

Form Comments:
1) Perhaps add "Owner" in between the Subdivision and Watershed - see blue arrow
2) Red Box denotes where the form shows what appears to be an open ended parenthesis around the word "Field". This could be a form space issue or a typo, but it should be updated.

![screenshot_1](https://user-images.githubusercontent.com/16418393/48366754-c62d7080-e67c-11e8-89ad-4b2e3b64a2e1.png)

**Comment by cstevenson1** [comment]
Spoke with Julie and we both agree with the suggestion

**Comment by impittman** [comment]
@kanglu666  please see my comments from 11/12/2018 for creating the field on the PID POINT form and updating the database.

**Comment by kanglu666** [comment]
owner filed has been added in to the PID_Point feature
the new field also has been added into the field tool

**Comment by mjuber-kci** [comment]
Confirmed field has been added to dev database and Dev Field tool 8.0. Will confirm that it populating correctly in database after nightly script.

![image](https://user-images.githubusercontent.com/16919958/64444167-83240a00-d0a1-11e9-9ee0-4e3247171087.png)

**Comment by mjuber-kci** [comment]
Confirm that it is populating correctly in database, push to prod.

**Comment by KCI-Ablowers** [comment]
Confirmed by @mjuber-kci - Push to Prod

**Comment by kanglu666** [comment]
owner filed has been added in to the PID_Point feature in PROD

**Comment by kanglu666** [comment]
ready in PROD 8.3 release

**Comment by mjuber-kci** [comment]
Confirmed in Prod Field Tool 8.3. Will confirm it is populating correct field in database after nightly script.
![image](https://user-images.githubusercontent.com/16919958/65884282-9192d800-e366-11e9-8de3-3fa0b66efb50.png)

**Comment by mjuber-kci** [comment]
Confirmed in database.
