### ISSUE TITLE
Cannot add a photo for BMP Action that has no comment

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#298]
If you do not put a comment after you input a BMP Action:

![bmp action without a comment](https://cloud.githubusercontent.com/assets/16919984/21782108/44bd0082-d680-11e6-8b59-3f28b35003fe.JPG)

You cannot add a photo or the application crashes:

![bmp action without a comment crash](https://cloud.githubusercontent.com/assets/16919984/21782130/591be76e-d680-11e6-8da2-7f55d9f30a6a.JPG)

FYI....I think we had a similar issue before and it related to the comment field being required.  If this is in fact the issue, hopefully the fix is quick and easy.

**Comment by kanglu666** [comment]
updated, ready for testing in version 3.2 release

**Comment by mortynsky** [comment]
This issue has been fixed!
