### ISSUE TITLE
BMP Inspection Date

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#299]
If you try and change an inspection date for BMPs the application appears to change the date within the inspection and on the inspection summary (list of all inspections), however, when you save and re-open that inspection the date reverts back to the current date.

![actual inspection date](https://cloud.githubusercontent.com/assets/16919984/21811493/e4aea120-d71d-11e6-9860-77d2dfa651f0.JPG)

**Comment by cstevenson1** [comment]
Bug needs to be addressed so BMP Reports display proper inspection date.

**Comment by kanglu666** [comment]
updated in local dev

**Comment by cstevenson1** [comment]
@leeensminger it does not let you change the date when creating a new BMP inspection record but it does if you update an existing record (you can create and save a new inspection, then re-open it and the date will change). If this is the intended workflow, then the issue is fine and can be pushed to prod.

**Comment by cstevenson1** [comment]
same as before. confirmed March 26 comment is true in Dev Field Tool v8.0

User can edit inspection date on an existing inspection record but not a new one. Probably not worth additional effort. @KCI-Ablowers push to prod
![image](https://user-images.githubusercontent.com/16919898/64450816-e79a9580-d0b0-11e9-80f8-f3b10beb1da1.png)

**Comment by KCI-Ablowers** [comment]
Confirmed by @cstevenson1 - Push to Prod

**Comment by kanglu666** [comment]
ready in PROD 8.3 release

**Comment by cstevenson1** [comment]
Confirmed in PROD. User can back date an existing inspection but not a new inspection.
