### ISSUE TITLE
New inspection showing photos from previous inspection

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#3]
When I created a new inspection on a second structure, it automatically showed the pictures i attached on the inspection for the first structure. 

![photos from previous inspection](https://cloud.githubusercontent.com/assets/16919958/12657239/51272256-c5d0-11e5-9e01-0959503fb4b4.JPG)

**Comment by kanglu666** [comment]
fixed, will be ready for testing in next release.
