### ISSUE TITLE
Low Flow Channel Component 

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#30]
Can the Low Flow Channel component be referred to as "LFC" instead of "Flow" for the Inventory and Inspection Tabs since Flow is already a field in another form.

![image](https://cloud.githubusercontent.com/assets/16919958/12730319/6cf418c8-c8f9-11e5-99c3-dac43f968d13.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by mjuber-kci** [comment]
This needs to be changed for structure type = manhole as well.

![image](https://cloud.githubusercontent.com/assets/16919958/13962484/947dafde-f037-11e5-888c-f2aba4116463.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
