### ISSUE TITLE
Swale Point Inspection - Inspected, Inspection Reason, and Reason Description Not Saving

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#301]
The fields Inspected, Inspection Reason, and Reason Description in a Swale Point Inspection are not saving at all. This is probably because none of those are fields within the SWALE_CONN_INSPECTIONS Table in the database. The fields should be added in the database so that the values save within the Field Tool.  Additionally, the Inspection Comments save correctly upon creation of the Inspection record, however it will not update if the Inspection is reopened and the value is changed. 

Before Closing Out:
![image](https://cloud.githubusercontent.com/assets/16919958/22163920/ed9d1c00-df22-11e6-8a04-e2af0fb0292a.png)
 
After Reopening Inspection:
![image](https://cloud.githubusercontent.com/assets/16919958/22163945/0d619ca0-df23-11e6-8839-5bf7159be238.png)

Updating Inspection Comments:
![image](https://cloud.githubusercontent.com/assets/16919958/22163978/353392c4-df23-11e6-8738-50383624bce5.png)

Inspection Comments not did not update upon reopening inspection:
![image](https://cloud.githubusercontent.com/assets/16919958/22164004/4f2bc296-df23-11e6-9f63-14127cf9bdab.png)

**Comment by leeensminger** [comment]
Discussed with @cstevenson1 03-13-17

Determined this will continue to be an enhancement for the foreseeable future.  As Christina does desktop inventory, she will create new inspections.  To isolate these so that we can later update with Inspected = No (desktop) vs Yes (field):

She'll comment these as Desktop Inventory or something similar.  We can use this, and a combination of Create Date, Last Edit Date, and machine ID to isolate these in the future (where Create Date = Last Edit Date and device name = Christina's machine name are desktop inventory inspections).

**Comment by impittman** [comment]
@kanglu666 please see @mjuber-kci comments from 1/20/2017 for a detailed explanation of what needs to be updated for the V 7.0 fixes

**Comment by KCI-Ablowers** [comment]
@kanglu666 Can you please review this issue and determine if it is possible under the current field tool push? Given the "extra" time we decided it would be good to get all schema changes in now.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 were you able to confirm after the nightly script run?

**Comment by cstevenson1** [comment]
@KCI-Ablowers Retested and confirmed in v8.2 Data is saving to the new fields in the Dev database. Push to prod

![image](https://user-images.githubusercontent.com/16919898/65041991-ec1f4380-d925-11e9-9c39-6030419716ed.png)

**Comment by kanglu666** [comment]
Inspected, Inspection Reason, and Reason Description  have been added in to SWALE_CONN_INSPECTIONS in PROD

**Comment by kanglu666** [comment]
ready in PROD 8.3 release

**Comment by mjuber-kci** [comment]
Confirmed fields are saving in prod field tool 8.3. Will confirm in database after nightly script. 

![image](https://user-images.githubusercontent.com/16919958/65897864-3f5db100-e37e-11e9-813a-31519e973e27.png)

**Comment by mjuber-kci** [comment]
Confirmed to be populating correctly in database.
