### ISSUE TITLE
Adding a Photo to a Swale Inspection

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#305]
When adding a photo to a swale inspection there is a 10 character limit to the Photo Comments field:

Adding a swale inspection photo with 10 characters or less works!

![swale_photo_worksjpg](https://cloud.githubusercontent.com/assets/16919984/24212388/998ba09c-0f05-11e7-8af7-5dfc59818264.JPG)

Adding a swale inspection photo with more than 10 characters throws an error!

![swale_photo_error](https://cloud.githubusercontent.com/assets/16919984/24212437/bd8f1cee-0f05-11e7-8ac6-4865cd7a57d0.JPG)

This field should have a limit of 255 characters so this error does not occur.

**Comment by cstevenson1** [comment]
The comments field should not be required

**Comment by leeensminger** [comment]
@impittman  please confirm the field specs as they currently are.  Then here in this GH item, please list 1) the current specs, and 2) what the field configuration needs to be.

Apply the database changes needed label, and reassign me

**Comment by impittman** [comment]
From the screenshot, there appears to be two things going on here.
1) Entering text greater than 10 throws an error in the "Photo Comments" text box.
2) When adding more than 10, the error message shows "Invalid type or Value for the field SWALE_PHOTO_CATEGORY".

My thoughts on the issue:
1) Why does the error message reference the "SWALE_PHOTO_CATEGORY" field when entering the comments? With the message stating an invalid entry, it appears that the Comments field in the UI is mapped to the wrong field. The indicator to me is the invalid type, which is likely the domain value found in the SWALE_PHOTO_CATEGORY field. 

2)To confirm the point above, I would suggest double checking that "SWALE_INSP_PHOTO_COMMENTS" is what is mapped to the Comments text box.

3) As requested, the "SWALE_INSP_PHOTO_COMMENTS" specs are below, which appear to match what is needed by @cstevenson1 :
![specs](https://user-images.githubusercontent.com/16418393/48493302-922b8a00-e7f9-11e8-9c96-6c6cb5b0b1e7.png)

**Comment by leeensminger** [comment]
@kanglu666 see above; please address.  work with Maria for more details.

**Comment by cstevenson1** [comment]
no longer appears to be an issue. i'm guessing the mapping was corrected
