### ISSUE TITLE
"Nearest Stream" field to WQ Investigations table

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#309]
Add a "Nearest Stream" field to the WQ Investigations table. It should not be a required field. High priority enhancement- needed for the WQ Report.

**Comment by leeensminger** [comment]
@mjuber-kci If it's only purpose is for the report, and its not needed in the database for other purposes, we can do a spatial analysis during the report generation to populate this data into the report.

**Comment by mjuber-kci** [comment]
We discussed this internally and we feel that the spatial join would not be the best option since over 14,000 of the 19,800 features in the Stream layer for Delaware do not have the GNIS_Name populated and we need this to be filled out in the report. Currently this is primarily a manual effort by looking at Google Maps. It would also be useful to have this information saved in the database to be able to query how many illicit discharges we had to each water body. Additionally this would address cases where the feature drains to one stream but is technically located closer to another stream.

**Comment by cstevenson1** [comment]
Update WQI report. See WebViewer Github Bug #64

**Comment by kanglu666** [comment]
new field "Nearest Stream" has been added into the dev database
How do you want to populate the data for this field, now, it's null for all records

**Comment by leeensminger** [comment]
The logic will be a user-generated text input. @kanglu666 please hold on making this update in the field tool until next fiscal year.

**Comment by mjuber-kci** [comment]
Confirmed field "Nearest Stream" has been added to dev database.

**Comment by mjuber-kci** [comment]
Confirmed field "Nearest Stream" has been added to Prod Database.

![image](https://user-images.githubusercontent.com/16919958/65886425-4e3a6880-e36a-11e9-90e3-30c8fee383cd.png)
