### ISSUE TITLE
Frame of Cover material drop down not present

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#31]
Drop down to select Frame of Cover material is not present

![image](https://cloud.githubusercontent.com/assets/16919958/12730489/38518bae-c8fa-11e5-9000-3da8cb16339e.png)

**Comment by leeensminger** [comment]
The dropdown for this field is present for Manholes (this field is present for manholes; see bug #34 ).

Can you confirm which structure types which should have a field for Frame of Cover Material, and list each structure type for which this field/dropdown is missing?  You can add the list as a comment in this thread.

**Comment by mjuber-kci** [comment]
This bug and #34 are not related. #34 is a misnamed field, whereas this bug, refers to the box that holds the domain values (the drop down) being missing from the UI.

**Comment by leeensminger** [comment]
Clarified with Christina this morning - will send to Lu.

**Comment by kanglu666** [comment]
fixed, ready for testing in next release
