### ISSUE TITLE
Frame of Cover Height on Manholes is not recording properly

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#310]
I added a new manhole and filled out all information in the Location tab. I then went to the Inventory tab to update the component information (Snip 1). I noticed that when I filled out the Height of the Frame of Cover component that the height duplicated in the Adjustment Ring Height field, even though I had not marked the component as present yet (Snip 2). I then updated the Adjustment Ring Height and noticed it changed my Height for the Frame of Cover component (Snip 3).

Snip 1
![snip 1](https://cloud.githubusercontent.com/assets/16919898/24921847/36d50000-1eba-11e7-86a7-7ac25776325e.PNG)
Snip 2
![snip 2](https://cloud.githubusercontent.com/assets/16919898/24921857/3d5a3b0c-1eba-11e7-99e6-ebf757dc0cfd.PNG)
Snip 3
![snip 3](https://cloud.githubusercontent.com/assets/16919898/24922038/e47d04fa-1eba-11e7-8235-3fb441d4ded1.PNG)

We have checked this in the field database and noticed all manholes that we have inventoried since deployment have a Frame of Cover Height of 0. There are mostly valid values in the Adjustment Ring Height field and are not sure but believe the Frame of Cover Height and Adjustment Ring Height fields in the field tool may both be pointed at the Adjustment Ring Height field in the database.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Measurements appeared to correctly save when I updated the values and came back to it later. I did not check the database to make sure it was writing correctly but we are not observing the issues noted above in the field tool. Passing back to Lee to check in prod
