### ISSUE TITLE
FLOW_CHAR and Photos not displaying in WQ Investigations

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#312]
The FLOW_CHAR (page 4) and Photos (page 6) of the WQ Investigations are not displaying in the field tool. It appears that the information is being written to the database correctly. 

![image](https://user-images.githubusercontent.com/16919958/27588520-7b0a3d2e-5b16-11e7-9c39-3083e14f68d2.png)

![image](https://user-images.githubusercontent.com/16919958/27588540-8c2f5bb6-5b16-11e7-87ca-32e74c9ebae8.png)

**Comment by mjuber-kci** [comment]
When the user initially creates a Water Quality Investigation, the information appears to be writing to the database correctly. However, when attempting to update any part of the Water Quality Investigation, it appears that the database is creating additional FLOW_CHAR records related to the WQI_FIELD_SHEET instead of updating the original one. For example, on Structure 0111211765, we created a WQ_INVESTIGATION on 5/17/2017. On 6/27/2017 we edited the WQ_INVESTIGATION from a different machine to update Determination field and to add the Lab Results that were received back from the Lab. There are 2 related records within the FLOW_CHAR table, one from the day we preformed the initial investigation (5/17/2017) and one record from the day we updated the investigation (6/27/2017). Additionally the Lab Results that were added are related to the second FLOW_CHAR record from 6/27/2017 instead of on 5/17/2017. The multiple records need to be consolidated with the original record and the Lab Results associated to the original FLOW_CHAR record as well. Additionally, the field tool needs to update the original record instead of creating another one. I am not sure how the database is allowing this because the relationship between the two tables is one to one.  There are currently 50 records in the WQ_FIELD_SHEET table that relate to the 61 FLOW_CHAR records.

**WQ_INVESTIGATION Table:**
![image](https://user-images.githubusercontent.com/16919958/28828926-3d8d82d0-76a0-11e7-99b5-987423fbcfb8.png)

**WQI_FIELD_SHEET Table:**
![image](https://user-images.githubusercontent.com/16919958/28828942-48da920e-76a0-11e7-9a40-8cba986368ae.png)

**FLOW_CHAR Table:**
![image](https://user-images.githubusercontent.com/16919958/28828957-55feb2ee-76a0-11e7-9e21-1686cb83c08e.png)

**Relationship Class for WQI_FIELD_SHEET and FLOW_CHAR table:**
![image](https://user-images.githubusercontent.com/16919958/28829086-b3f604e2-76a0-11e7-9058-2afb58fe19b6.png)

**Comment by leeensminger** [comment]
Per email from Melissa 20170824 - Additionally, I noticed that the cardinality for the relationship between PIPE_INSPECTIONS and PIPE_INSP_PHOTOS is 1 - 1, however, for pipe inspections we attach two photos (an upstream and a downstream photo). This is not in GitHub because I have not observed it causing any issues yet. Let me know if you would like me to log this in GitHub for tracking purposes.

![image](https://user-images.githubusercontent.com/4103847/30059481-440a1974-920d-11e7-9f31-63c496676e42.png)

**Comment by kanglu666** [comment]
i do see the duplicated records in the database, not sure how they get into the database.
tested on the dev, at this moment, it looks like the field tool is working correctly for the flow char.

recommendation:  clean the duplicated data in the flow char table, and monitor it to see if there are new duplicated data created

**Comment by mjuber-kci** [comment]
@leeensminger and @cstevenson1 to discuss during their next meeting. We know what is causing the duplicate records in the FLOW_CHAR table. It is caused when the WQ_INVESTIGATION record and original FLOW_CHAR record is created in one work area and then it is edited in a second work area. When the second work area is downloaded, the original FLOW_CHAR record is not pulled down and is shown as blank in the field tool. There are required fields so the user needs to fill them out before saving and this creates the second FLOW_CHAR record.

**Comment by kanglu666** [comment]
updated, ready for testing in next release.
also duplicated flow_char data in dev have been deleted

**Comment by mjuber-kci** [comment]
appears to be working in dev

**Comment by cstevenson1** [comment]
appears to be working. will continue to monitor
