### ISSUE TITLE
Relationship cardinality for PIPE_INSPECTIONS_has_PHOTOS

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#315]
Per email from Melissa 20170824:

Additionally, I noticed that the cardinality for the relationship between PIPE_INSPECTIONS and PIPE_INSP_PHOTOS is 1 - 1, however, for pipe inspections we attach two photos (an upstream and a downstream photo). This is not in GitHub because I have not observed it causing any issues yet. Let me know if you would like me to log this in GitHub for tracking purposes.

_Marked as high priority due to potential to cause gp issues_

![image](https://user-images.githubusercontent.com/4103847/30059506-58d26320-920d-11e7-81f3-1801caf37463.png)

**Comment by kanglu666** [comment]
need database update for the relationship class

**Comment by kanglu666** [comment]
the relationship class has been updated in DEV DATABASE , ready for test in next release
