### ISSUE TITLE
Incident ID for WQ Investigation needs to be moved to page 1/7 in the Field Tool

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#316]
The Incident ID field needs to be moved to page 1 of the WQ Investigations in the Field Tool. It is currently on page 2 with the information included with the WQI_FIELD_SHEET table, however, the Incident ID is stored in the WQ_INVESTIGATIONS table in the database along with the information shown on page 1. This is causing an issue for Dumping situations (Doorhanger Info = "Yes") because we would select "No" for Field Sheet on page 1 (which greys out all of page 2) however, these situations still need to be assigned a Incident ID.

Selecting Field Sheet = No, Doorhanger = Yes
![image](https://user-images.githubusercontent.com/16919958/30325045-217bda94-9791-11e7-8c7f-0a67b394e9e9.png)

Page 2 Greyed Out - 
![image](https://user-images.githubusercontent.com/16919958/30325057-3302642c-9791-11e7-8875-1a8419fb30fc.png)

**Comment by leeensminger** [comment]
Discussed with CS options are either to drop system logic, or move the field in the UI

**Comment by kanglu666** [comment]
Incident ID field has been moved to the first page, ready for testing in next release

**Comment by cstevenson1** [comment]
was moved to page 1

![image](https://user-images.githubusercontent.com/16919898/32117185-71ccde3c-bb1b-11e7-87dc-6e0f64108e44.png)
