### ISSUE TITLE
Frame is misspelled in the inspection form

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#32]
Frame Cover Condition is misspelled on the second page of the inspection form. It should be Frame of Cover Condition. 

![image](https://cloud.githubusercontent.com/assets/16919898/12730453/0be7808c-c8fa-11e5-9637-b0413419cef7.png)

**Comment by cstevenson1** [comment]
This was for structure type=inlet

**Comment by kanglu666** [comment]
updated.
