### ISSUE TITLE
Convert map services to https

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#321]
Based on this email from DelDOT (Bruce Allen) Thursday, September 28, 2017 7:55 AM:

Recently ESRI instituted a new policy whereby only HTTPS map services can be loaded into ArcGIS Online based map applications.
Because of this, DelDOT is now having difficulty using the NPDES map service inside our Gateway mapping portal.

**Comment by cstevenson1** [comment]
This has since been completed
