### ISSUE TITLE
WQI - Memo descriptions don't clear for new WQI

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#322]
to repeat:
1. create a new WQ investigation for a structure.  add WQ memo, with memo dates and descriptions and comments.  save.
2. in another structure, create a new WQ investigation.  go to page WQ Memo page (7/7).  the previous descriptions are still present.  see screenshot... areas in red are from the previous structure entries.

![image](https://user-images.githubusercontent.com/4103847/32057961-c23e76b8-ba36-11e7-829a-fe875aba3a46.png)

**Comment by leeensminger** [comment]
@cstevenson1 Confirm on pending dev release

**Comment by cstevenson1** [comment]
@leeensminger I have not been experiencing the above issue thus far. Will continue to monitor though.

![image](https://user-images.githubusercontent.com/16919898/32339344-f08ecfda-bfcd-11e7-9abb-c644461ae5fa.png)

**Comment by cstevenson1** [comment]
have not been able to reproduce the issue noted above. c
