### ISSUE TITLE
WQI Memo - a new WQI_MEMO is saved for each part of the UI form

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/DelDOT-NPDES-Field-Tool#323]
In this screenshot, I had just created a WQ Investigation, and went through the process of adding a memo:
1. Add new memo From/To/Date. Then save
2. Add new Memo description comment date and Description, then save that.
3. Add new comment, and save that. 

It appears that after each part when I save, system creates a new record in WQI_Memo.  This should not be the case, it should be one record that gets updated in the WQI_MEMOS.MEMO_COMMENT field.

![image](https://user-images.githubusercontent.com/4103847/32060249-3788d2b0-ba3c-11e7-8276-212c5297f2d3.png)

**Comment by kanglu666** [comment]
it looks that way in the sqllite database. all update record will display as an new record.
check in your data, look it at in ArcGIS
