### ISSUE TITLE
BMPs - Fields missing in Database

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#329]
Paved Area (ac), Facility Location, Facility Size, and Expiration Date are shown in the field tool but not the database. Please update the database to include these fields.

![image](https://user-images.githubusercontent.com/16919898/36047195-59c90816-0da9-11e8-986a-b062356e0ed4.png)

**Comment by leeensminger** [comment]
@impittman Please confirm that these are not in the database, and also list suggested field types, lengths and nullable (y/n).  Then assign Christina to confirm, and apply the 'database changes needed' label.

**Comment by impittman** [comment]
I can confirm these fields are not in Production or Dev. Here are my suggestions @cstevenson1 , please feel free to modify:

BMPS.PAVED_AREA
Double
Nullable = Y    reason is so it will not default to 0 and be a misrepresentation in the tool

BMPS.FACILITY_LOCATION
Text
Characters= 255 to provide ample space to capture long description comments?
Nullable: Y

BMPS.FACILITY_SIZE
Text
Characters = 50
Question here: Does this plan to become a domain field to control data entry?
Nullable: Y

BMPS.EXPIRATION_DATE
DATE
Nullable: Y   reason for Nullable is to prevent the value auto defaulting to 1899 as is common in ArcMap with required date fields.

**Comment by impittman** [comment]
Updated to match @cstevenson1 comments

Confirmed fields needed:

BMPS.PAVED_AREA
Double
Nullable = Y reason is so it will not default to 0 and be a misrepresentation in the tool

BMPS.FACILITY_LOCATION
Text
Characters= 255 to provide ample space to capture long description comments?
Nullable: Y

BMPS.FACILITY_SIZE
Text
Characters = 255
Question here: Does this plan to become a domain field to control data entry?
Nullable: Y

BMPS.EXPIRATION_DATE
DATE
Nullable: Y reason for Nullable is to prevent the value auto defaulting to 1899 as is common in ArcMap with required date fields.

**Comment by impittman** [comment]
@kanglu666 please update/add the fields in the database to match my comments from 11/13/2018

**Comment by kanglu666** [comment]
fields have been added in field tool local dev.

**Comment by cstevenson1** [comment]
cannot edit Paved Area field in dev field tool 7.3. I can delete the 0 but cannot enter a new value

**Comment by KCI-Ablowers** [comment]
@kanglu666 Can you please review this issue and determine if it is possible under the current field tool push? Given the "extra" time we decided it would be good to get all schema changes in now.

**Comment by cstevenson1** [comment]
@KCI-Ablowers same as previous comments - fields have been added to Dev but Paved Area defaults to 0 when it should be Null. However, we are fine with this being addressed later if necessary in order to not delay the next release

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers same as previous comments - fields have been added to Dev but Paved Area defaults to 0 when it should be Null. However, we are fine with this being addressed later if necessary in order to not delay the next release

@kanglu666 if time allows, can you look into the issue in @cstevenson1 reply in this comment. If not, I will mark as confirmed.

**Comment by kanglu666** [comment]
this filed can only type in number including decimal type, no characters.  
since it's a decimal type field, can not be 0...

**Comment by cstevenson1** [comment]
@KCI-Ablowers given @kanglu666 comment, please proceed to push to prod

**Comment by KCI-Ablowers** [comment]
Confirmed by @cstevenson1. Push to prod confirmed.

**Comment by kanglu666** [comment]
Paved Area (ac), Facility Location, Facility Size, and Expiration Date  have been added in to BMP feature class in PROD database

**Comment by kanglu666** [comment]
ready in PROD 8.3 release

**Comment by cstevenson1** [comment]
fields present in PROD
