### ISSUE TITLE
Zoom Icon on Feature List does not Zoom

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#33]
The Zoom icon on the Feature List Tab does not zoom, it only pans to the selected structure.

**Comment by mjuber-kci** [comment]
It appears that the Zoom icon is functional for Conveyances and BMPs, but it is not functional for Structures.

**Comment by kanglu666** [comment]
actually, this "Zoom" button is for set the selected feature into the middle of the view.
for structure, it will also highlight it.

**Comment by leeensminger** [comment]
The button zooms for Conveyances and BMPs, but only pans for structures.  The system should consistently zoom with this button.  We may need to apply a defined scale level to which the system will zoom for structures.  Pending further discussion with Lee / Lu.

**Comment by leeensminger** [comment]
For points: center point on screen, then increase map scale.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
