### ISSUE TITLE
Duplicate Temporary Dummy Records

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#331]
Around April 2017 there were email discussions about duplicate records being created in the database, particularly with temporary dummy nodes. The issue was not given a top priority since the temporary dummy points aren't used as frequently as other structure types, such as inlets but the issue still seems to persist. When there are duplicate records, field staff have difficulties deleting the point. 

![image](https://user-images.githubusercontent.com/16919898/36997785-c1f736fa-2088-11e8-83a9-9369d6a2e95e.png)

**Comment by impittman** [comment]
An extra record is created when a new temporary point is initially created in the field tool. This is not related to user error or inadvertently creating two points. This appears to be logging the point twice upon creation within the database upon syncing. Please see the screen shot in the above comment.

**Comment by kanglu666** [comment]
updated in local dev

**Comment by cstevenson1** [comment]
@leeensminger the duplicate record was not occurring for every temporary dummy point and is difficult to test. Not sure what changes were made but I'm going to say it's fine and will keep an eye on it. I was able to delete all temp dummy records I created during testing. Push to prod

**Comment by cstevenson1** [comment]
@KCI-Ablowers same as March 27. No issues observed in Dev Field Tool v8.0 for deleting temp dummy points but it wasn't happening every time and don't know what changes were made so difficult to say if it's fixed. Push to prod.

**Comment by KCI-Ablowers** [comment]
Confirmed by @cstevenson1 - Push to Prod

**Comment by kanglu666** [comment]
ready for PROD 8.3 release

**Comment by mjuber-kci** [comment]
Created 3 Temporary Dummy points and successfully deleted all, so it appears issue is fixed. Will reopen if problem occurs again.
