### ISSUE TITLE
Add Ability to Select Odor When No Field Sheet

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#336]
Currently Odor is associated with the tracking form of the water quality investigation. We need the ability to fill out Odor even when there is no tracking form, which is often the case with Door Hanger related investigations (dumping as opposed to water flow). We need to add a field to the database and to the field tool to account for this. We may need to further discuss if we should have two odor fields (one on doorhanger and one on tracking form) or one odor field that would be accessible for every WQI. Afterwards, the WQI report in the viewer needs to be updated (Viewer Bug 280).

**Comment by cstevenson1** [comment]
also corresponds with Viewer Bug 224

**Comment by mjuber-kci** [comment]
Confirmed in Dev Field Tool. Will confirm in dev database tomorrow after nightly script.

![image](https://user-images.githubusercontent.com/16919958/56512439-5958b500-64fd-11e9-940e-8f6d85cc9168.png)

**Comment by mjuber-kci** [comment]
Confirmed it is populating correctly in the dev database. Following field need to be deleted: 

WQI_FIELD_SHEET.ODOR

**Comment by mjuber-kci** [comment]
Confirmed in Dev Field Tool 8.0. Will confirm in dev database after nightly script.

Following fields still need to be deleted in the dev database:
WQI_FIELD_SHEET.ODOR

Old Odor field need to be removed in UI on page 2 of the WQI:
![image](https://user-images.githubusercontent.com/16919958/64435128-ed33b380-d08f-11e9-9554-c07a888d59b3.png)

**Comment by mjuber-kci** [comment]
@KCI-Ablowers please include this in the current milestone.

**Comment by mjuber-kci** [comment]
Confirmed in dev database.

Field still need to be deleted in the dev database and removed from UI on pages 2 of the WQI. Viewer bug 280 must be completed before pushing to prod.

**Comment by KCI-Ablowers** [comment]
@kanglu666 See comment above M:\2009\01090421.103\GIS\SHA_Proposed\Maria_Working\mp_submittals\BASELINE_INSPECTIONS\Field\Winter 2017-2018\Photos

**Comment by KCI-Ablowers** [comment]
@kanglu666 will update the field tool UI.

**Comment by cstevenson1** [comment]
@KCI-Ablowers please make sure data is appropriately migrated to the new field in prod before deleting the old fields

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers please make sure data is appropriately migrated to the new field in prod before deleting the old fields

@kanglu666 just a reminder.

**Comment by kanglu666** [comment]
setting, odor, setting desc, odor desc and nearest stream fields have been added into wqi_investigation table in PROD

**Comment by kanglu666** [comment]
ready for PROD 8.3 release

**Comment by mjuber-kci** [comment]
Confirmed in Prod Field Tool 8.3. Will confirm it is populating correct field in database after nightly script. 

![image](https://user-images.githubusercontent.com/16919958/65884775-6ceb3000-e367-11e9-8728-58f2f3bfddda.png)

**Comment by mjuber-kci** [comment]
Confirmed Odor is populating correctly in database.
