### ISSUE TITLE
Swale Inspection Date

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#339]
Basically the same as #299 

User needs ability to back date a swale inspection.

**Comment by cstevenson1** [comment]
To clarify, the inspection date field is completely missing from swale inspections so the field needs to be added and we need ability to back date it. It is present for pipe inspections.

Pipe inspection
![image](https://user-images.githubusercontent.com/16919898/53570082-a2ab0a80-3b33-11e9-8c7b-e854fc7296fc.png)

Swale inspection
![image](https://user-images.githubusercontent.com/16919898/53570110-b9516180-3b33-11e9-96dc-92f5e9f1a22d.png)

**Comment by impittman** [comment]
@kanglu666 please see the screen shot above. The Swale Inspection form needs to add the field Inspection Date. This field should be dynamic in nature to allow the user to capture the correct date the inspection was done. A calendar feature would be ideal.

**Comment by kanglu666** [comment]
swale inspection date has been added in the field tool.
![1](https://user-images.githubusercontent.com/6352480/54242961-f7b82a80-44fc-11e9-8e45-6bdd068fe4e1.JPG)

**Comment by cstevenson1** [comment]
Unlike the BMP Inspection Date, this date field appears to allow back dating when you first create the record or during an update. Please push to prod.

**Comment by cstevenson1** [comment]
same as March 26 comment. Dev Field Tool v8.0 allows user to change inspection date for new or existing record.

@KCI-Ablowers push to prod

**Comment by KCI-Ablowers** [comment]
Confirmed by @cstevenson1 - Push to Prod

**Comment by kanglu666** [comment]
ready for PROD 8.3 release

**Comment by mjuber-kci** [comment]
Confirmed in Prod Field Tool 8.3. Will confirm in database after nightly script.

**Comment by mjuber-kci** [comment]
Confirmed in database.
