### ISSUE TITLE
Update Maintenance Area in MPK

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#341]
@leeensminger per our phone discussions, please update the maintenance area layer in the MPK to change Seaford to Bridgeville (in line with bug 282 in the viewer). 

Is it a large effort for the overlay to populate the NEW_NAME instead of AREA_NAME in the field tool? See snip below
![image](https://user-images.githubusercontent.com/16919898/51992256-abe48100-247a-11e9-8fd1-579a9d93d761.png)

Maintenance area is currently populated in the format of AREA_NAME in the database but we would prefer to have the maintenance area number in front (as it is in NEW_NAME). This would allow the BMP Reports to keep its format and we are ok with it being in the Structure and Conveyance Reports.

If it is a large effort, can we field calculate AREA NAME so it is the same as the NEW_NAME when you are updating Seaford to Bridgeville.

**Comment by impittman** [comment]
mpk was created/tested and submitted to @cstevenson1 for review and testing

**Comment by cstevenson1** [comment]
The MPK was updated and loads in the field tool but the "Refresh Selected" button no longer works. If the user changes a value and then checks the refresh selected to change it back, the value goes away completely (it's blank). If the user puts in a new feature, the field does not automatically populate like it did before. 

![image](https://user-images.githubusercontent.com/16919898/52563644-0d3c1680-2dd0-11e9-93de-66dc4e8c6866.png)

**Comment by kanglu666** [comment]
I believe the field tool is using the area_name/new_name to populate the maintenance area data.   the value in the Area_Name column has been changed, that would break the function of "refresh" button.

Solution:
option 1: use the old MPK, nothing need to change
option 2: if want to use the new one, i need to change the code in the field tool.
Please pass me the new MPK, i will make the update debug, the new MPK will only be used once the new release v7.0 out

**Comment by impittman** [comment]
@kanglu666 we will need to use the new mpk as it has the updates to the maintenance area that newark has approved for use. i will email the file location to this new mpk created in 10.3.

**Comment by kanglu666** [comment]
Just checked the code, the field tool is using “BaseData_1_Primary” to query all the location (watershed, main_area, etc).
BaseData_2_LargePolygons has nothing to do with the query.

For issue 341, the “refresh selected” button is not working for maintenance area, is because, the maintenance area field values pulled directly from the Domain of the database.
And looks like the maintenance area Domain has been updated in the database.

I have updated the field tool code to using the new domain.

**Comment by impittman** [comment]
Thanks for checking on this portion of the code and updating the domain field. We will test upon the new release. If any changes get made to BaseData_1_Primary, I will keep this in mind.

**Comment by cstevenson1** [comment]
refresh is now working in the field tool for maintenance area. i was unable to sync (Error Code 500) to ensure no issues but I am guessing it is fine.

**Comment by cstevenson1** [comment]
staff has reported refresh is now working
