### ISSUE TITLE
Need ability to select Setting outside of field sheet/doorhanger

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#342]
Very similar to issue #336 

Currently, Setting is populated on the WQI report based on the Field Sheet or Door hanger. However, sometimes there is no field sheet or door hanger associated with the water quality investigation so there is no way to populate Setting on the report. We suggest pulling this field out (along with Odor as in bug 336) from the field sheet/doorhanger work flow to the main WQI page in the field tool. That way the 
Setting field would be available for every water quality investigation.

**Comment by impittman** [comment]
After speaking with Newark, the following should occur:
1) the "SETTING" field needs to be removed from the following 2 depicted tabs in the field tool:

![setting 1 remove JPG](https://user-images.githubusercontent.com/16418393/54287350-dea28e80-457b-11e9-80cd-81a6ab5a41fe.png)

![setting 2 remove](https://user-images.githubusercontent.com/16418393/54287370-e6fac980-457b-11e9-861c-c0b25356b6e9.png)

2) Add a "SETTING" field similar to the ones removed on the first page of the WQI form:
![add setting](https://user-images.githubusercontent.com/16418393/54287416-fe39b700-457b-11e9-813d-00c7f9fb236d.png)

3) A "SETTING" field needs to be added to deldot_migration2.DBO.WQ_INVESTIGATIONS

4) Migrate the "SETTING" field data from the following two database fields into the field created in  deldot_migration2.DBO.WQ_INVESTIGATIONS. 

Migrate data from these 2 fields:
deldot_migration2.DBO.WQI_FIELD_SHEET.SETTING

deldot_migration2.DBO.WQI_PURPOSE_DUMPING.SETTING

to the new field in deldot_migration2.DBO.WQ_INVESTIGATIONS

the following are the related ids for the join in the tables to migrate the SETTING Field

deldot_migration2.DBO.WQI_PURPOSE_DUMPING.WQ_INVESTIGATION_ID = deldot_migration2.DBO.WQ_INVESTIGATIONS.GlobalID

deldot_migration2.DBO.WQI_FIELD_SHEET.WQ_INVESTIGATION_ID = deldot_migration2.DBO.WQ_INVESTIGATIONS.GlobalID

**Comment by kanglu666** [comment]
Setting field added in WQI and plugin local field tool
.
Note: Setting field in WQI_FIELD_SHEET and WQI_PURPOSE_DUMPING are still there in case break the current dev field tool.  Will need to delete them and update the field tool at the very last

**Comment by kanglu666** [comment]
version dev 7.1 has been released, ready for testing

**Comment by mjuber-kci** [comment]
Confirmed in Dev Field Tool. Will confirm in dev database tomorrow after nightly script. 

![image](https://user-images.githubusercontent.com/16919958/56512363-21ea0880-64fd-11e9-9def-8048e6377136.png)

**Comment by mjuber-kci** [comment]
Confirmed it is populating correctly in the dev database. Following fields need to be deleted: 

WQI_FIELD_SHEET.SETTING
WQI_PURPOSE_DUMPING.SETTING

**Comment by mjuber-kci** [comment]
Confirmed in Dev Field Tool 8.0. Will confirm in dev database after nightly script.

Following fields still need to be deleted in the dev database:
WQI_FIELD_SHEET.SETTING
WQI_PURPOSE_DUMPING.SETTING

Old Setting fields need to be removed in UI from pages 2 and 3 of the WQI:
![image](https://user-images.githubusercontent.com/16919958/64434705-24ee2b80-d08f-11e9-912f-0c8c0687d5dd.png)

![image](https://user-images.githubusercontent.com/16919958/64434724-320b1a80-d08f-11e9-9489-a5ac6c24b874.png)

**Comment by mjuber-kci** [comment]
Confirmed in dev database.

Fields still need to be deleted in the dev database and removed in UI from pages 2 and 3 of the WQI before pushing to prod.

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please see the comment above (https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/342#issuecomment-528873273) to updates to the UI in the Field Tool.

**Comment by KCI-Ablowers** [comment]
@kanglu666 will drop fields and update Field tool UI.

**Comment by kanglu666** [comment]
WQI_FIELD_SHEET.SETTING
WQI_PURPOSE_DUMPING.SETTING have been removed from database and UI

**Comment by cstevenson1** [comment]
@KCI-Ablowers please keep in mind that the new setting field in Dev was populated (field calculated) using the old setting fields before they were deleted. Please make sure the Setting field is also populated in prod before deleting the old setting field data considering the Dev data is much older than the prod data.

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers please keep in mind that the new setting field in Dev was populated (field calculated) using the old setting fields before they were deleted. Please make sure the Setting field is also populated in prod before deleting the old setting field data considering the Dev data is much older than the prod data.

@kanglu666 just a reminder.

**Comment by kanglu666** [comment]
updated, ready for testing in dev version 8.3

**Comment by mjuber-kci** [comment]
Confirmed domain is correct in dev Field Tool 8.3. Push to prod. 

![image](https://user-images.githubusercontent.com/16919958/65243142-c0cb5e80-dab5-11e9-990e-98c89b94e40b.png)

**Comment by KCI-Ablowers** [comment]
confirmed by @mjuber-kci. Push to prod confirmed.

**Comment by kanglu666** [comment]
setting, odor, setting desc, odor desc and nearest stream fields have been added into wqi_investigation table in PROD

**Comment by kanglu666** [comment]
ready for PROD 8.3 release

**Comment by mjuber-kci** [comment]
Confirmed in Prod Field Tool 8.3. Will confirm it is populating correct field in database after nightly script.

![image](https://user-images.githubusercontent.com/16919958/65884595-1ed62c80-e367-11e9-9efd-03c03e4d67df.png)

**Comment by mjuber-kci** [comment]
Confirmed Setting is populating correctly in database.
