### ISSUE TITLE
Cannot Reset Inspection Reason to Null in Conveyance Inspection

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#343]
Currently, Inspection Reason should only be enabled/populated when Inspected = No. If the user accidentally populates the inspection reason, they should be able to change Inspected to Yes, removing the value that had been selected for Inspection Reason. This appears to be properly working for structure inspections but not conveyance inspections. There is no way to reset the Inspection Reason value to blank unless you create a new inspection.

![image](https://user-images.githubusercontent.com/16919898/53569586-7e9af980-3b32-11e9-8a54-06ba7d381724.png)

**Comment by kanglu666** [comment]
updated in local dev

**Comment by cstevenson1** [comment]
appears to be working in dev. please push to prod.

**Comment by cstevenson1** [comment]
same as March 26 comment. Confirmed Inspection Reason resets when changed Inspected from No to Yes in Dev Field Tool v8.0

@KCI-Ablowers push to prod

**Comment by KCI-Ablowers** [comment]
Confirmed by @cstevenson1 - Push to Prod

**Comment by kanglu666** [comment]
ready for PROD 8.3 release

**Comment by mjuber-kci** [comment]
Appears to be working in prod field tool 8.3. Will confirm in database after nightly script.

**Comment by mjuber-kci** [comment]
Confirmed to be populating correctly in database.
