### ISSUE TITLE
Remove "Immediate Action Needed" from page 3 of WQ Investigations and Database

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#348]
Remove "Immediate Action Needed" from page 3 of WQ Investigations and from the WQI_PURPOSE_DUMPING Table in the database. It is not needed and it will not have any affect on the reports generated from the Web Viewer. 

![image](https://user-images.githubusercontent.com/16919958/54221706-6c25a600-44ca-11e9-88fa-9c97663fdc9f.png)

![image](https://user-images.githubusercontent.com/16919958/54221779-88294780-44ca-11e9-8276-f93e146bca99.png)

**Comment by cstevenson1** [comment]
not enough value to invest resources in fixing. users will continue to populate field
