### ISSUE TITLE
Two Flow Present fields for WQ Investigation

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#35]
Does there need to be fields that both identify if there is flow or not? Could the one on the first page be removed?

Page 1 of WQ Investigation - Flow Present:
![image](https://cloud.githubusercontent.com/assets/16919958/12752273/bc269632-c98f-11e5-84e1-480f2a42ccde.png)

Page 2 of WQ Investigation - Flow Observed:
![image](https://cloud.githubusercontent.com/assets/16919958/12752303/ed5e6ac2-c98f-11e5-9183-8c484eee4425.png)

**Comment by leeensminger** [comment]
@mjuber-kci I don't have in my notes why there are two.  So the one on the first page can get removed, I think.

**Comment by leeensminger** [comment]
@kanglu666 please update in UI.  change has been made in database, will be ready at BC's next load.

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release
