### ISSUE TITLE
Add "SETTING_OTHER_DESC" to WQ_INVESTIGATIONS Table and update field tool

### ISSUE THREAD

**Issue by impittman** [leeensminger/DelDOT-NPDES-Field-Tool#350]
This is similar to issue #342 

1.	A "SETTING_OTHER_DESC" field needs to be added to deldot_migration2.DBO.WQ_INVESTIGATIONS
2.	Migrate the "SETTING_OTHER_DESC" field data from the following two database fields into the field created in deldot_migration2.DBO.WQ_INVESTIGATIONS.SETTING_OTHER_DESC

Migrate data from these 2 fields:
deldot_migration2.DBO.WQI_FIELD_SHEET. SETTING_OTHER_DESC
deldot_migration2.DBO.WQI_PURPOSE_DUMPING. SETTING_OTHER_DESC
to the new field in deldot_migration2.DBO.WQ_INVESTIGATIONS

3. The following are the related ids for the join in the tables to migrate the SETTING_OTHER_DESC Field
deldot_migration2.DBO.WQI_PURPOSE_DUMPING.WQ_INVESTIGATION_ID = deldot_migration2.DBO.WQ_INVESTIGATIONS.GlobalID
deldot_migration2.DBO.WQI_FIELD_SHEET.WQ_INVESTIGATION_ID = deldot_migration2.DBO.WQ_INVESTIGATIONS.GlobalID

4.	Once the fields are migrated, delete the SETTING_OTHER_DESC field from:
deldot_migration2.DBO.WQI_FIELD_SHEET. SETTING_OTHER_DESC
deldot_migration2.DBO.WQI_PURPOSE_DUMPING. SETTING_OTHER_DESC

5.	Once added, the deldot_migration2.DBO.WQ_INVESTIGATIONS SETTING_OTHER_DESC field needs to populate the box below:

![image](https://user-images.githubusercontent.com/16418393/56432542-c8cf6a00-629b-11e9-8bd8-eaa80915eb07.png)

**Comment by mjuber-kci** [comment]
Statements 1, 2, and 3 above are correct. However, the field needs to be moved in the UI to either underneath or next to the new Setting field on page 1 of the WQI form.

![630EC78A_LI](https://user-images.githubusercontent.com/16919958/56437065-089e4d80-62ac-11e9-97f9-9922479d4f01.jpg)

**Comment by mjuber-kci** [comment]
Confirmed in Dev Field Tool. Will confirm in database tomorrow after nightly script. 

![image](https://user-images.githubusercontent.com/16919958/56512247-c750ac80-64fc-11e9-9bcf-5613e67d616e.png)

**Comment by mjuber-kci** [comment]
Confirmed it is populating correctly in the dev database. Following fields need to be deleted: 

WQI_FIELD_SHEET.SETTING_OTHER_DESC
WQI_PURPOSE_DUMPING.SETTING_OTHER_DESC

**Comment by mjuber-kci** [comment]
Confirmed in Dev Field Tool 8.0. Will confirm in dev database tomorrow after nightly script.

Confirmed WQI_FIELD_SHEET.SETTING_OTHER_DESC and WQI_PURPOSE_DUMPING.SETTING_OTHER_DESC have been deleted from dev database.

**Comment by mjuber-kci** [comment]
Confirmed in dev database, push to prod.

**Comment by cstevenson1** [comment]
@KCI-Ablowers similar to #342, please make sure data is migrated to the new field in prod before deleting the old fields. That's highlighted in the first comment of this thread by Maria,

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers similar to #342, please make sure data is migrated to the new field in prod before deleting the old fields. That's highlighted in the first comment of this thread by Maria,

@kanglu666 just a reminder.

**Comment by KCI-Ablowers** [comment]
@mjuber-kci confirmed. Push to Prod Confirmed. 

> Confirmed in dev database. Viewer bug 302 and 334 need to be addressed before pushing to prod.

Confirmed by @mjuber-kci. Push to Prod confirmed

**Comment by mjuber-kci** [comment]
Confirmed in Prod Field Tool 8.3. Will confirm it is populating correct field in database after nightly script.  

![image](https://user-images.githubusercontent.com/16919958/65884650-39a8a100-e367-11e9-8668-46c83a26d209.png)

**Comment by mjuber-kci** [comment]
Confirmed Setting Description is populating correctly in database.
