### ISSUE TITLE
Add "ODOR_OTHER_DESC" field to WQ_INVESTIGATIONS and field tool form

### ISSUE THREAD

**Issue by impittman** [leeensminger/DelDOT-NPDES-Field-Tool#351]
This is similar to issue #336 

1.	A "ODOR_OTHER_DESC" field needs to be added to deldot_migration2.DBO.WQ_INVESTIGATIONS
2.	Migrate the "SETTING_OTHER_DESC" field data from the following database field into the field created in deldot_migration2.DBO.WQ_INVESTIGATIONS.
Migrate data from this field:
deldot_migration2.DBO.WQI_FIELD_SHEET. ODOR_OTHER_DESC
to the new field in deldot_migration2.DBO.WQ_INVESTIGATIONS.ODOR_OTHER_DESC
the following are the related ids for the join in the tables to migrate the ODOR_OTHER_DESC Field
deldot_migration2.DBO.WQI_FIELD_SHEET.WQ_INVESTIGATION_ID = deldot_migration2.DBO.WQ_INVESTIGATIONS.GlobalID
3.	Once the fields are migrated, delete the ODOR_OTHER_DESC field from:
deldot_migration2.DBO.WQI_FIELD_SHEET. ODOR_OTHER_DESC

4.	Once added, the deldot_migration2.DBO.WQ_INVESTIGATIONS. ODOR_OTHER_DESC field needs to populate the box below:

 
![image](https://user-images.githubusercontent.com/16418393/56432848-e94bf400-629c-11e9-90e2-639145027443.png)

**Comment by mjuber-kci** [comment]
Statements 1, 2, and 3 above are correct. However, the field needs to be moved in the UI to either underneath or next to the new Odor field on page 1 of the WQI form. 

![630EC78A_LI (2)](https://user-images.githubusercontent.com/16919958/56437288-c590aa00-62ac-11e9-8b88-ae76613759bc.jpg)

**Comment by mjuber-kci** [comment]
Confirmed in Dev Field Tool. Will confirm in database tomorrow after nightly script. 

![image](https://user-images.githubusercontent.com/16919958/56512247-c750ac80-64fc-11e9-9bcf-5613e67d616e.png)

**Comment by mjuber-kci** [comment]
Confirmed it is populating correctly in the dev database. Following field need to be deleted:

WQI_FIELD_SHEET.ODOR_OTHER_DESC

**Comment by mjuber-kci** [comment]
Confirmed in Dev Field Tool 8.0. Will confirm in dev database tomorrow after nightly script.

Confirmed WQI_FIELD_SHEET.ODOR_OTHER_DESC has been deleted from dev database.

**Comment by mjuber-kci** [comment]
Confirmed in dev database.

Viewer bug 280 and 334 must be completed before pushing to prod.

**Comment by cstevenson1** [comment]
@KCI-Ablowers please make sure data is appropriately migrated to the new field in prod before deleting the old fields

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers please make sure data is appropriately migrated to the new field in prod before deleting the old fields

@kanglu666 just a reminder.

**Comment by KCI-Ablowers** [comment]
Confirmed by @mjuber-kci. @kanglu666 will have the data populated correctly.

**Comment by kanglu666** [comment]
ready for PROD 8.3 release

**Comment by mjuber-kci** [comment]
Confirmed in Prod Field Tool 8.3. Will confirm it is populating correct field in database after nightly script.

![image](https://user-images.githubusercontent.com/16919958/65884927-b3d92580-e367-11e9-8e20-85087228b3d2.png)

**Comment by mjuber-kci** [comment]
Confirmed Odor Description is populating correctly in database.
