### ISSUE TITLE
Sample Collected Field Missing

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#36]
Under the WQ Investigation, before the Reason, there should be "Sample Collected" field with Boolean values as options. If "Yes" is selected for Sample Collected then Reason greys out and when No is selected, Reason is required. 

![image](https://cloud.githubusercontent.com/assets/16919958/12752623/6e5cf462-c991-11e5-9edd-0971b57d22cf.png)

**Comment by leeensminger** [comment]
@mjuber-kci , Sometimes having duality in fields like this becomes problematic from a data management perspective, and requires a QC check in your database to make sure the logic, as you spell it out above, is present.  I think we could eliminate that, and reduce a step for field crews, if we added a value in the Reason domain list, for "Inspected".  This way, users would click the field, and either select a value of "Inspected", or if they did not inspect it, one of the other reasons.  Something like below.  Thoughts?

![image](https://cloud.githubusercontent.com/assets/4103847/13055835/954127e4-d3df-11e5-887a-e9e712b41273.png)

**Comment by mjuber-kci** [comment]
Yes that could work however, the domain values should include the values used in the "Reason" domain in the WQ Investigation:


The values should be:
Sample Collected
Not Collected - No Flow
Not Collected - Cannot Access/Cannot Locate
Not Collected - Stream

![image](https://cloud.githubusercontent.com/assets/16919958/13058008/0a3d3250-d3ee-11e5-822f-d437e1d7b545.png).

Also, I didn't know if it would be an issue to change or not, but currently the "Flow Observed" domain on page 2 is linked to the flow characteristics on page 3. If Flow Observed = "Yes" then page 3 becomes required to be filled out, whereas if "No" is selected then page 3 is greyed out. Technically, we only fill out the flow characteristics if we sample it. If there is flow, but we don't sample it (because of the reasons above) we wouldn't fill out the page 3 of the WQ investigation. Would it be possible to link page 3 to only being available when "Sample Collected" is selected?

An alternative option is to add domain values to "Flow Observed" field and completely remove the "Sample Collected" domain suggested above. The options would be Yes, No, Stream, and Cannot Access/Cannot Locate. If Yes is selected, the flow characteristics would be completed (how it is currently set up) and all other values would grey out the flow characteristics.

**Comment by leeensminger** [comment]
@mjuber-kci , we will incorporate this into the next scheduled release (approx March 21).

**Comment by leeensminger** [comment]
@kanglu666 Update the label for Reason (on page 2 of WQ Investigations, sourced from WQI_FIELD_SHEET.REASON)  = Sample Collected.  The domain will be updated at next db update.

**Comment by leeensminger** [comment]
@kanglu666 please do the following:

1. change the label for the field "Reason" here to read "Sample Collected?"
2. Page 3 (field sheet) of a WQ Investigation should only display if WQ_INVESTIGATIONS.FIELD_SHEET = Y.
3.

**Comment by kanglu666** [comment]
Would it be possible to link page 3 to only being available when "Sample Collected" is selected?

Page 3 (field sheet) of a WQ Investigation should only display if WQ_INVESTIGATIONS.FIELD_SHEET = Y. 3.

which one is correct?

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release
