### ISSUE TITLE
Add "Underdrain" to Conveyance Type domain

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Field-Tool#366]
Add `Underdrain` to the `D_Conv_Type` domain in the NPDES Database.

**Comment by kanglu666** [comment]
"Underdrain" has been added into Conveyance Type domain

**Comment by KCI-Ablowers** [comment]
Confirmed in "new" dev - @cstevenson, please verify that this is correct. 
![image](https://user-images.githubusercontent.com/35460336/90534668-053cff80-e148-11ea-8c9f-c241d966da1f.png)

**Comment by cstevenson1** [comment]
New value to D_Conv_Type appears correct in new dev

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Please confirm this is correct in production and close.

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in production field tool v9.9
