### ISSUE TITLE
Add "Underdrain Segments" table and relationship classes

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Field-Tool#367]
Add a new table called `Underdrain_Segments` to the NPDES database. The schema should be identical to `Pipe_Segments`. 

Add relationship classes to `Underdrain_Insp`, `Conveyances` and `File_Attachment`.

**Comment by kanglu666** [comment]
UNDERDRAIN_SEGMENTS table created.

**Comment by KCI-Ablowers** [comment]
> UNDERDRAIN_SEGMENTS table created.

Thanks @kanglu666, please update when you have the relationship classes and other tables in place.

**Comment by kanglu666** [comment]
Three Relationship classes have been created:  ready for testing in new dev
1:  relationship class between Conveyance and Underdrain_Segments 
2:  Underdrain_Segments has  Underdrain_Insp, 
3: Underdrain_Segments has  File_Attachment.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 - @kanglu666 noticed a relationship that I missed in the initial analysis - `Pipe_Segments` (table) to `Barrel` (table). Do the new `Underdrain_Segments` need to relate to `Barrel` as well? This relationship does not exist right now in the dev DB or the feature service published to new dev - https://devgis.kci.com/arcgis/rest/services/deldot_npdes_field_new

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please go back and update the domains to match the replicated tables for underdrain segments.

**Comment by KCI-Ablowers** [comment]
> @kanglu666 Please go back and update the domains to match the replicated tables for underdrain segments.

@kanglu666 Hold off on the domains for now.

**Comment by cstevenson1** [comment]
@KCI-Ablowers All fields in the UNDERDRAIN_SEGMENTS table should have referenced underdrains, not pipes in the name. For example, it should be UNDERDRAIN_COMMENTS, not PIPE_COMMENTS. If this is a large effort, please let us know so we can discuss internally before you proceed.

**Comment by cstevenson1** [comment]
@KCI-Ablowers the typos should be corrected in the relationship class to the CONVEYANCES feature class and renamed to be more consistent with the pipe segments. CONVEYANCES_has_UNDERDRAIN_SEGS or CONVEYANCES_has_UD_SEGS if that is too long

![image](https://user-images.githubusercontent.com/16919898/93093140-53bdbb00-f66e-11ea-97c3-19b0e27d6059.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers Per our meeting on 9/7, please confirm FILE_ATTACHMENT is still an active table. If it is not, it should be deleted from the database, along with the associated relationship classes, including the one to UNDERDRAIN_SEGMENTS.

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers Per our meeting on 9/7, please confirm FILE_ATTACHMENT is still an active table. If it is not, it should be deleted from the database, along with the associated relationship classes, including the one to UNDERDRAIN_SEGMENTS. If the table is still active/valid, then the typos in the relationship class to UNDERDRAIN_SEGMENTS should be addressed.

@cstevenson1 based on the `date_attached` it looks like all records in this table got loaded (attached) on 2/27/17. We will have to investigate any dependencies (scripts, field tool, etc.) before deciding to delete this or not.

**Comment by KCI-Ablowers** [comment]
@kanglu666 we will need to review these new tables and update the field names. I overlooked this initially so we can set up a time to discuss it.

**Comment by KCI-Ablowers** [comment]
Closing due to the updated schema/workflow.
