### ISSUE TITLE
Add "Underdrain Inspection" tables 

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Field-Tool#368]
Add a new table called `UNDERDRAIN_INSP` to the NPDES database. The schema should be identical to the `PIPE_INSPECTIONS` table. 

Add a new table called `UNDERDRAIN_INSP_PHOTOS` to the NPDES database. The schema should be identical to the `PIPE_INSP_PHOTOS` table and have attachments enabled.

Add a new table called `UNDERDRAIN_INSPECTION_RATINGS` to the NPDES database The schema should be identical to the `PIPE_INSPECTION_RATINGS` table. 

Create necessary relationships mimicking existing pipe inspection associated tables.

**Comment by kanglu666** [comment]
tables created,

next: relationships

**Comment by kanglu666** [comment]
TwoRelationship classes have been created: ready for testing in new dev
1:  Underdrain_Inspection has UNDERDRAIN_INSP_PHOTOS (1:M)
2: Underdrain_Inspection has UNDERDRAIN_INSPECTION_RATINGS (1:1)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please go back and update the domains to match the replicated tables.

**Comment by cstevenson1** [comment]
@KCI-Ablowers The highlighted typos/inconsistencies with current schema should be corrected to:
UNDERDRAIN_INSP_has_RATINGS, UNDERDRAIN_has_INSP, and UNDERDRAIN_INSP_has_PHOTOS 


![image](https://user-images.githubusercontent.com/16919898/92501092-166bb000-f1cc-11ea-8906-6276d2685adc.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please make the updates above - https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/368#issuecomment-688984329

**Comment by KCI-Ablowers** [comment]
Closing due to the updated schema/workflow.
