### ISSUE TITLE
Add "Underdrain Pipe End" to Structure Types Domain

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Field-Tool#369]
Add `Underdrain Pipe End` to the `D_StructureTypes_1` domain.

**Comment by kanglu666** [comment]
"Underdrain Pipe End" has been added into Structure Types Domain

**Comment by KCI-Ablowers** [comment]
Confirmed in "new" dev - @cstevenson1 please confirm this is correct.
![image](https://user-images.githubusercontent.com/35460336/90535210-a7f57e00-e148-11ea-8e92-df2ef56ac009.png)

**Comment by cstevenson1** [comment]
Verified "Underdrain Pipe End" has been added to D_StructureTypes_1 in new dev

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Please confirm this is correct in production and close.

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed in production field tool v9.9

![image](https://user-images.githubusercontent.com/16919898/101024898-c5f1bd80-3542-11eb-9efe-dc61355c5db3.png)
