### ISSUE TITLE
Creating New Features Outside of Work Area

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#37]
What happens if you create a structure outside of your work area? I noticed that the field tool does allow you to do so. 

![image](https://cloud.githubusercontent.com/assets/16919898/12753705/32678058-c996-11e5-9f2c-208f6bc50a64.png)

**Comment by kanglu666** [comment]
updated, the tool will not allow user to add features outside workarea. 
ready for testing in next release
