### ISSUE TITLE
Add "Underdrain Pipe End Inspection" tables

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Field-Tool#371]
Add a new table called `UNDERDRAIN_PIPE_END_INSPECTIONS` (or _INSP if too long). The schema should be identical to the `PIPE_END_INSPECTIONS` and include a new Yes/No field called `DELINEATOR_FLAG`. 

Add relationship classes to `structure_insp_photos`, `outfall_inspections`, and `idde_prelim_screenings`.

**Comment by kanglu666** [comment]
Underdrain_Pipe_End and UNDERDRAIN_PIPE_END_INSPECTIONS tables have been added, 
relationshipclass has been created. ready for testing in new dev

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please go back and add all of the domains to match the replicated table - `PIPE_END_INSPECTIONS`

**Comment by KCI-Ablowers** [comment]
> @kanglu666 Please go back and add all of the domains to match the replicated table - `PIPE_END_INSPECTIONS`

@kanglu666 hold off on domain updates for now.

**Comment by KCI-Ablowers** [comment]
Adding the final schema/workflow document for reference. 
[Underdrain Schema Comments_Final.docx](https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/files/5246479/Underdrain.Schema.Comments_Final.docx)

**Comment by kanglu666** [comment]
updated, please test in dev

**Comment by KCI-Ablowers** [comment]
@kanglu666 It looks like some of the items from the word doc above were not applied in deldot-sql2016 deldot_migration2. Please apply the changes below. Note: We each only **two hours** each to finalize the schema updates. 

- [ ] Update `STRUCTURE_HAS_UNDERDRAIN` relationship class name to `STRCTURE_has_UNDERDRAIN_END`
- [ ] Update `UPIPEEDNISP_HAS_ISPPHOTO' relationship class name to `UNDERDRAIN_PIPE_END_INSP_has_PHOTOS`
- [ ] Update `UPIPEENDINS_HAS_OF_INS` relationship class name to `UNDERDRAIN_PIPE_END_INSP_has_OF_INSP`
- [ ] Update `PRE_SRC_HAS_UNDERDRAINPEISP` relationship class name to `PRE_SCR_has_UNDERDRAIN_END_INSP`

**Comment by KCI-Ablowers** [comment]
@kanglu666 similar to the [comment](https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/371#issuecomment-714651665) above: 

- [ ] Apply the `D_EndTreatmentType` domain to the `END_TYPE` field in the `UNDERDRAIN_PIPE_END` table

**Comment by kanglu666** [comment]
Relationship classes name updated
Domain  D_EndTreatmentType added
ready for testing in dev
