### ISSUE TITLE
New Underdrain Symbology

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Field-Tool#373]
@kanglu666 Please provide the link to the most recent field tool MXD. 

@cstevenson1 I will reassign to you once Lu gets the MXD. We will need you guys to determine what symbology should apply to the new underdrain conveyance and underdrain pipe end structure.

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please drop the link to the MXD here when you can.

**Comment by kanglu666** [comment]
Field tool mxd:

V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\fieldtool\deldot_npdes_field_prod4_withUnderdrain.mxd

**Comment by KCI-Ablowers** [comment]
@kanglu666 Looking at the MXD, I noticed that the `STRUCTURES` are symbolized on `STR_TYPE_IS_OUTFALL` and not `STRUCTURE_TYPE`. Do we need to apply the `D_StructureTypes_1` domain to this field? or can the symbology be updated without it? When adding values to the structures symbology, only "Underdrain Pipe End, No" appears and I assume there should be a "Yes" option? 
![image](https://user-images.githubusercontent.com/35460336/96904864-a8bad100-1465-11eb-9680-57e6c5b5fbb1.png)

The conveyances appear to be fine to add the symbology. Also, do we need to update the feature templates for both structures and conveyance after @cstevenson1 updates the symbology? 

Please let me know before I pass this off to @cstevenson1 and @mortynsky for the updates.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 You can ignore the comment above and update the symbology as you have in the past. Please let us know when the MXD is updated.

**Comment by cstevenson1** [comment]
@KCI-Ablowers unable to open MXD. Is the location above to the MXD that was saved in an older version of ArcMap for us?

**Comment by cstevenson1** [comment]
@KCI-Ablowers please let me know if there are any issues. We added symbology for underdrain conveyance, underdrain pipe end, and updated a couple things to match the viewer (3 to 1 arrows on conveyances and drainage areas).

V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\fieldtool\deldot_npdes_field_prod4_withUnderdrain_106.mxd

**Comment by kanglu666** [comment]
New Feature service has been published, underdrain symbology showing up in the fieldtool now, ready for testing in new dev
![Capture](https://user-images.githubusercontent.com/6352480/97513957-f5217780-1963-11eb-8dfc-d63ffac57749.PNG)

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed underdrain symbology is showing in Dev. Push to prod when underdrain workflow is finalized

![image](https://user-images.githubusercontent.com/16919898/97728453-f5c32680-1aa7-11eb-8697-6d371a6bc271.png)
