### ISSUE TITLE
Underdrain Components for Testing - Field Tool 9.5 New Dev

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Field-Tool#374]
The field tool version with underdrain components is here - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDotDev\FieldTool 9.5-new dev on the network. 

Please test both the complete underdrain conveyance and underdrain pipe end structure workflows. Check out and check in functionality is available and should be tested as well. Please attempt to push through both conveyance and structure test data for review by Newark and KCI. This data will also be used once confirmed correct to assist in finalizing the reporting.

**Comment by cstevenson1** [comment]
Since the symbology has not been updated, you cannot see underdrain conveyances of underdrain pipe ends in the field tool

![image](https://user-images.githubusercontent.com/16919898/95608158-b8c8be80-0a2a-11eb-945e-9479b39f2419.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Can we make a temporary update to the MXD for testing? Relates to #373.

**Comment by cstevenson1** [comment]
Unable to delete new underdrain pipe end features. When you click the delete button, there are no messages and no response from the field tool. Although you cannot see the feature on the map, you can still select it so I know it wasn't deleted.

**Comment by cstevenson1** [comment]
Unable to save inspection for underdrain pipe ends. I added a new underdrain pipe end feature and proceeded to add a new inspection. When I clicked save, I received a message saying an underdrain pipe end inspection record was created, but when I returned to the page of the field tool that would display any existing inspections, my newly created inspection was not listed. 

![image](https://user-images.githubusercontent.com/16919898/95612469-6ccd4800-0a31-11eb-8455-23b55a505dbf.png)

![image](https://user-images.githubusercontent.com/16919898/95612478-735bbf80-0a31-11eb-90d4-f0b4aa464116.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev (version dev 9.6):

V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDotDev\FieldTool9.6-dev_with underdrainDB

**Comment by cstevenson1** [comment]
@KCI-Ablowers I'm not seeing the delineator flag field for the underdrain pipe end inspection.

![image](https://user-images.githubusercontent.com/16919898/97884045-98231a00-1cf3-11eb-9fc9-07d92789e3f8.png)

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers I'm not seeing the delineator flag field for the underdrain pipe end inspection.
> 
> ![image](https://user-images.githubusercontent.com/16919898/97884045-98231a00-1cf3-11eb-9fc9-07d92789e3f8.png)

@kanglu666 Please review on your end

**Comment by kanglu666** [comment]
Delineator filed has been added into the Underdrain Pipe end inspection in field tool. new release out:

V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDotDev\FieldTool9.7-dev_with underdrainDB

**Comment by cstevenson1** [comment]
@KCI-Ablowers 

We are able to edit Discharge Downstream Type and Ownership Downstream for regular pipe ends when Is Outlet = Yes but we cannot modify these fields for underdrain pipe ends, even though the fields are visible in the field tool.

Pipe End
![image](https://user-images.githubusercontent.com/16919898/99085724-8ca6dd00-2596-11eb-97bf-cee81820ce83.png)


Underdrain Pipe End
![image](https://user-images.githubusercontent.com/16919898/99085842-b2cc7d00-2596-11eb-8e62-2e24928e8ed7.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers Delineator field should be Delineator Flag in field tool to match database and limit confusion

![image](https://user-images.githubusercontent.com/16919898/99086116-1060c980-2597-11eb-8ae4-8ef13bae003c.png)

![image](https://user-images.githubusercontent.com/16919898/99086133-18206e00-2597-11eb-9158-4637e0bd8553.png)

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please review the two comments below and let me know how many hours you think you will need to address. 

- https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/374#issuecomment-726811639
- https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/374#issuecomment-726812655

**Comment by KCI-Ablowers** [comment]
@kanglu666 - https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/370#issuecomment-719655105 we need to make this DB change as well.

**Comment by kanglu666** [comment]
Discharge Downstream Type and Ownership Downstream fields are now editable.
Delineator Flag label updated.

New dev release: 

V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDotDev\FieldTool9.8-dev_with underdrain

**Comment by cstevenson1** [comment]
@KCI-Ablowers 

Delineator Flag was updated 
![image](https://user-images.githubusercontent.com/16919898/99679699-3cbe8f00-2a4a-11eb-91dc-ab4c55787a2e.png)

Discharge Downstream Type and Ownership Downstream fields are editable in field tool 
![image](https://user-images.githubusercontent.com/16919898/99679909-7bece000-2a4a-11eb-9aaa-b53da2c01f22.png)

Pending a successful sync of the edits with the database tonight, this is ready to push to prod.
