### ISSUE TITLE
Reported By and External Report Type not in correct order

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#38]
Reported By and External Report Type should be moved below Report Type because they pertain to Investigation Reason and Report Type instead of to the information at the bottom of the form.

![image](https://cloud.githubusercontent.com/assets/16919958/12752815/3f9e9bca-c992-11e5-98e3-d0c54da5ece6.png)

**Comment by kanglu666** [comment]
updated
