### ISSUE TITLE
Previous inspection carries over to new structure

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#39]
I added a new structure with structure type=swale connection and connection type=start. After updating the location and inventory tabs, I hit the Save button and a dialog box popped up saying Structure Updated, followed by one saying Swale Connection Updated. I then went into the inspection tab and an inspection was already opened. The second page of the inspection form appeared to be the inspection form for an inlet (most recent structure I added before the swale connection point). I then went back to the location and inventory tabs to make sure the structure type was properly selected and hit Save. After hitting save, the Structure Updated box popped up, followed by the Swale Connection Updated box, then a third box popped up saying Inlet Updated. I think this relates to the bug Melissa logged in #3 

![image](https://cloud.githubusercontent.com/assets/16919898/12757824/a8b88f20-c9a7-11e5-96e5-0607e9afb8fb.png)

![image](https://cloud.githubusercontent.com/assets/16919898/12757865/d19f3f7e-c9a7-11e5-854c-4864ff49b26b.png)

**Comment by kanglu666** [comment]
fixed, ready for testing in next release
