### ISSUE TITLE
Cannot attach pipe inspection photos

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#4]
I tired to add photo for a pipe inspection and a message said to save inspection first. I then hit the Save button for the pipe inspection indicated with the red arrow and a “Sample Error” message popped up.

![conveyance4](https://cloud.githubusercontent.com/assets/16919958/12658095/f9aeaa08-c5d4-11e5-8de7-2904f1aaad82.JPG)

**Comment by mjuber-kci** [comment]
Upon further investigation, it appears that the error was thrown due to Personnel not being filled out.

**Comment by leeensminger** [comment]
Lu, for this and other popup error messages, can we have the message display more descriptive text?

Keeping assigned to me for now (low priority).

**Comment by kanglu666** [comment]
fixed, pipe inspection check function created, when user click save, it will check if all required fields are not null. ready for testing in next release
