### ISSUE TITLE
Missing Layers from New Work Area

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#40]
I created a 2nd work area and noticed that there are only 3 layers present in the Table of Contents. This may be related to the issue Christina logged in #14. 

![image](https://cloud.githubusercontent.com/assets/16919958/12760584/0d392a88-c9b5-11e5-9fdb-adc75a4ec7a6.png)

**Comment by leeensminger** [comment]
These are groups.  Expand the groups and you'll see all feature layers available, for both NPDES business data and base data.
