### ISSUE TITLE
Category is misspelled 

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#44]
Category is misspelled in two places on the inspection form where photos are attached. 

![image](https://cloud.githubusercontent.com/assets/16919898/12762482/4e43616c-c9bd-11e5-9a34-ca4cdeb88437.png)

**Comment by cstevenson1** [comment]
Category is also misspelled in the notification box that pops up if you do not choose the category of the photo first.

![image](https://cloud.githubusercontent.com/assets/16919898/13007361/cf034d60-d15d-11e5-8992-f307373c119f.png)

**Comment by kanglu666** [comment]
updated
