### ISSUE TITLE
Inspected Reason for Conveyances 

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#45]
For all Conveyance Types, Inspection Reason and Description should grey out if "Yes" is selected for Inspected. Also, "Description" should be "Reason Description".

![image](https://cloud.githubusercontent.com/assets/16919958/12761674/e7801eaa-c9b9-11e5-9532-6a158122a2b1.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
