### ISSUE TITLE
Flow Rate field

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#46]
Either the Flow Rate field needs to be capable of containing text so that "UNABLE TO MEASURE" could be included, or a separate field needs to be added, such as Flow Rate Estimated (Y/N). If "Yes" is selected, then Flow Rate will be filled out, if "No" is selected, the Flow Rate will be greyed out. 

![image](https://cloud.githubusercontent.com/assets/16919958/12857008/cec909ae-cc15-11e5-8c22-f9d8bb8bc312.png)

**Comment by leeensminger** [comment]
@mjuber-kci , here again I think would be a great opportunity to streamline the data collection / QC process, and implement some SOPs where: 

If flow could not be measured (unable to measure), then Flow Rate = 0  (by this point in the workflow you've already indicated that there is flow present, so a value of 0 = unable to measure).  Or we could make this field not required, so users could leave it Null.  

Thoughts?

**Comment by mjuber-kci** [comment]
Yes, I think either option would be fine.
