### ISSUE TITLE
Need to be able to add more "Other" fields for Lab Results

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#49]
For the Lab Results form, we need to have the ability to add more than 1 "Other" field. 

![image](https://cloud.githubusercontent.com/assets/16919958/12920039/e40a4ff6-cf14-11e5-9374-bcc0c2268b6e.png)

**Comment by leeensminger** [comment]
Logging as an enhancement for now, as this was not discussed during design.  Requires a data model change.

**Comment by leeensminger** [comment]
Updated in data model, pending loading by BC.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
