### ISSUE TITLE
Creating new features

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#5]
Is the only way to add a new feature through the "New" in the feature list tab?

**Comment by leeensminger** [comment]
Yes, the New button in the feature list tab is the only way to add a new feature.  

![image](https://cloud.githubusercontent.com/assets/4103847/12701817/2f87149c-c7e4-11e5-8d2b-d593e9739db8.png)

**Comment by leeensminger** [comment]
@cstevenson1 Is this suitable?  Please note any bugs or enhancements about this item, or, close the issue.  Thanks!

**Comment by cstevenson1** [comment]
That should be fine. I had discussed it with Matt and we were wondering if there was a possibility of having shortcuts on the top toolbar for commonly used items (i.e. a short cut to add a conveyance etc.)

**Comment by cstevenson1** [comment]
no fix necessary
