### ISSUE TITLE
Should not be able to remove all layers from table of contents

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#50]
While testing the table of contents, I noticed the field tool will allow the user to remove a layer. Essential layers for field crews should be locked to prevent accidental deleting and inconsistencies between toughbooks. 

![image](https://cloud.githubusercontent.com/assets/16919898/12926833/2431f4f8-cf33-11e5-99b3-453d984280d9.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
