### ISSUE TITLE
Button to populate GNIS ID does not function

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#53]
In the Inventory tab of a pipe conveyance, next to the Conveyance Stream field, there is a button that I believe is suppose to be used to fill out the GNIS ID when the pipe conveys a stream. The stream layer should be added to the field tool and associated with this feature so that the GNIS ID populates when the user selects a stream by using the mentioned button. 

![image](https://cloud.githubusercontent.com/assets/16919898/12951508/a7774108-cfe0-11e5-8448-f8c960e5f8c4.png)

**Comment by kanglu666** [comment]
I need the Stream Layer (with GNIS ID and other fields) in our Base Map

**Comment by leeensminger** [comment]
Duplicate with #26

**Comment by kanglu666** [comment]
updated, ready for testing in next release
