### ISSUE TITLE
Field Tool Crash

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#54]
I added a pipe conveyance and filled out the location and inventory tab. I saved the conveyance then went to the Selections tab. I filled in Select: CONVEYANCE County: Sussex (this is where my work area was) then hit the select button at the bottom of the form. A list of conveyances appeared in the feature list and I clicked on the check mark next to the last conveyance in the list to open it and received the errors shown in the last picture. As expected, the field tool closed after hitting cancel in the pop up boxes.

![image](https://cloud.githubusercontent.com/assets/16919898/12951875/6b8e8348-cfe2-11e5-9fc3-a3185772cec6.png)

![image](https://cloud.githubusercontent.com/assets/16919898/12952016/ff2f37aa-cfe2-11e5-8589-6ceab2e97414.png)

![image](https://cloud.githubusercontent.com/assets/16919898/12951858/5d2792f4-cfe2-11e5-9656-27cf3d2ee5f1.png)

**Comment by leeensminger** [comment]
Confirmed, this happens consistently with Pipes..

**Comment by kanglu666** [comment]
fixed, ready for testing in next release
