### ISSUE TITLE
Clear button does not function in Selections

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#57]
The "clear" button within the geographic filters of the Selections tab does not function. After clicking it, all existing values in the filters remain unchanged. 

![image](https://cloud.githubusercontent.com/assets/16919898/12957608/81880b42-cffb-11e5-8821-42733c695109.png)

**Comment by kanglu666** [comment]
fixed. ready for testing in next release
