### ISSUE TITLE
Settings icon is not functional

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#58]
The settings icon, which should allow for input of Personnel and Last Rain Date, is not functional. Previously mentioned in #17. 

![image](https://cloud.githubusercontent.com/assets/16919958/12978125/1876f170-d09d-11e5-9a76-0451b80b3855.png)

**Comment by kanglu666** [comment]
setting icon with tools (Bookmarks, Measure and GPS tools) will be moved into the left tab.

**Comment by mjuber-kci** [comment]
The settings icon is now functional, however, it does not include a place to input Last Rain Date and Personnel.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
