### ISSUE TITLE
Pipe End Inspection

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#6]
I created a new pipe end and completely filled out all of the Location and Inventory information and saved the structure successfully. I created a new inspection and completed everything and before attaching photos I went to save the inspection. First it stated that the a "New IDDE_PRELIM_SCREENINGS Added" followed by two error messages. I could not save the inspection or attach any photos.

1st Error
![capture1](https://cloud.githubusercontent.com/assets/16919958/12677677/a1b31b74-c668-11e5-8a2c-bf7f507bc3f1.JPG)

2nd Error
![capture2](https://cloud.githubusercontent.com/assets/16919958/12677683/afa35960-c668-11e5-9a41-65bf84399ef5.JPG)

**Comment by leeensminger** [comment]
Discussed that we highlight required fields.

**Comment by kanglu666** [comment]
fixed, check inspection fields function in place, will check required value before save.
