### ISSUE TITLE
Can buffer for drawing barrel conveyances be larger?

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#61]
When there are more than two barrels next to each other, the buffer used to select the upstream/downstream structures is not large enough to encompass the structures. Could the buffer be larger for just barrel conveyances?

![image](https://cloud.githubusercontent.com/assets/16919958/12978974/362b8848-d0a2-11e5-9625-b9548fe706d6.png)

**Comment by kanglu666** [comment]
. was 10 feet radius buffer;  update to 20 feet, ready for testing in next release
