### ISSUE TITLE
Misspellings for required fields pop up notification 

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#62]
Notification should read "All required fields in inventory section must have a value". It appeared when I tried to save a pipe end before finishing the inventory form. 

![image](https://cloud.githubusercontent.com/assets/16919898/12979413/de4c0532-d0a4-11e5-9ebc-2c61a67acfc9.png)

**Comment by kanglu666** [comment]
updated
