### ISSUE TITLE
IDDE Prelim Screening fields are not always required.

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#63]
If "No" is selected for Water Quality Investigation Needed, then Source, Flow, Odor, Staining, Other and Screening Comments should grey out.

![image](https://cloud.githubusercontent.com/assets/16919958/12979422/f6f5dd60-d0a4-11e5-8de4-928234cc68fc.png)

If "Yes" is selected for Water Quality Investigation Needed, then Flow, Odor, Staining, and Other are required, whereas Source and Screening Comments are optional. One of the required fields should always have "Yes" selected. 

![image](https://cloud.githubusercontent.com/assets/16919958/12979551/eba1e76e-d0a5-11e5-942c-691d294c4312.png)

If "Yes" is selected for Other, then Screening comments should be required.

![image](https://cloud.githubusercontent.com/assets/16919958/12979688/cdee9f68-d0a6-11e5-90ff-ee1f9c2195ee.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
