### ISSUE TITLE
Blank inventory tab for roadway culvert conveyance

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#64]
The inventory tab is blank for a conveyance of conveyance type=roadway culvert. It will then not allow you to save the conveyance because the required fields needing a value notification pops up. 

![image](https://cloud.githubusercontent.com/assets/16919898/12979927/08399ffa-d0a8-11e5-94cd-ea91a788d074.png)

**Comment by leeensminger** [comment]
@kanglu666 Roadway culverts should have inventory form

**Comment by kanglu666** [comment]
inventory form added for both driveway and roadway type.

**Comment by mjuber-kci** [comment]
Inventory tab is missing fields (no place to enter pipe properties). Fields for Shape, Material, Width, and Height need to be added.

![image](https://cloud.githubusercontent.com/assets/16919958/13952633/ee5fc4a8-f00d-11e5-8079-d2a0dfb7bdf9.png)

**Comment by leeensminger** [comment]
same comment as for #122 . we should be able to implement this within the existing database model.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
