### ISSUE TITLE
Sample Error

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#65]
I tried creating a new work area and received the following error. It is the first and only time so far that I have received it.

![capture](https://cloud.githubusercontent.com/assets/16919898/12984365/5877b318-d0bb-11e5-8e93-41ec2dab2d92.JPG)

**Comment by kanglu666** [comment]
this error was happening because the ArcGIS Server was down for a while. it's working fine now, if this error happen again, still means the arcgis server issue, just let us know.
