### ISSUE TITLE
Bookmarks do not save between uses of the field tool

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#66]
I added a bookmark and it was placed in the drop down list of available bookmarks. I then switched to a different work area but did not create any features in it. I then went back to the first work area that I had created the bookmark in and it was no longer in the list of available options.

![image](https://cloud.githubusercontent.com/assets/16919898/12984861/c7e9e76e-d0bd-11e5-8c3b-cc3693e91230.png)

![image](https://cloud.githubusercontent.com/assets/16919898/12984891/f4ab27c2-d0bd-11e5-95f6-da97897eadec.png)

**Comment by leeensminger** [comment]
@kanglu666 can you confirm the functionality for bookmarks

**Comment by kanglu666** [comment]
updated, Bookmarks Tool will save all new bookmarks created in your workarea.
