### ISSUE TITLE
Should State be on Conveyances and Structures? 

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#67]
I noticed that the field for State is in the location tab for conveyances but not for structures. Is there a reason we would want it on one and not both?

![image](https://cloud.githubusercontent.com/assets/16919898/12986240/28b890d0-d0c4-11e5-9d68-b011bd9f1fbe.png)

![image](https://cloud.githubusercontent.com/assets/16919898/12986316/9574a0ce-d0c4-11e5-8865-9fbb15640b15.png)

**Comment by kanglu666** [comment]
Updated, State field has been added into Structure, BMP and Conveyance location tabs.
ready for testing in next release

**Comment by leeensminger** [comment]
Include State in overlay data.  State is incorporated into the Counties layer - Counties.STATE. 

Right now, we only have DE.  Other states may be added in the future, but there are other implications to doing this that need to be thought through.
