### ISSUE TITLE
Field tool needs prompt to save data before adding new feature

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#68]
A warning message stating all unsaved data will be lost should appear when the user has a new feature open and tries to add another feature before hitting save. I added a swale connection point and filled out the location and inventory tab. I then hit new within the feature list tab and selected conveyance. I tried using the swale connection point as the upstream structure for the conveyance but it no longer existed. 

![image](https://cloud.githubusercontent.com/assets/16919898/12986439/44bbb8ec-d0c5-11e5-9321-ae74bd434f16.png)

![image](https://cloud.githubusercontent.com/assets/16919898/12986461/5b71d594-d0c5-11e5-8505-5ee24060731e.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
We also want to be prompted to save the data before leaving the structure form to use the Selections or Settings tab. It appears if you create a new structure without saving and then use the measure tool in the Setting tab that it will delete the point you were working on.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
