### ISSUE TITLE
Work Order Tab -  Page 4 of 5 Misspelling

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#69]
![work orders - contract is mispelled](https://cloud.githubusercontent.com/assets/16919984/12987219/117c738c-d0c9-11e5-8c0c-7d30c6790ccb.JPG)

Point of Contract should be, "Point of Contact"

**Comment by kanglu666** [comment]
updated

**Comment by cstevenson1** [comment]
![image](https://cloud.githubusercontent.com/assets/16919898/13855598/a1ea8398-ec47-11e5-896a-15b14788b040.png)


Additional misspellings of contact on page 4 of work order form

**Comment by mortynsky** [comment]
This issue appears to have not been resolved!

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by mortynsky** [comment]
This issue has been fixed!
