### ISSUE TITLE
Watershed Overlay Not Working

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#7]
Watershed and Watershed HUC8 are not automatically filling out in the Location tab upon creating a new structure.

**Comment by kanglu666** [comment]
Watershed HUC8 overlay is working now.
we dont have watershed layer in our basemap, if we need watershed overlay functional, need add watershed layer in basemap

**Comment by kanglu666** [comment]
updated, ready for testing in next release
