### ISSUE TITLE
Cross-sectional area is not calculating

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#70]
The cross-sectional area field within the inventory tab of the pipe conveyance should populate based on the user entered measurements. It is currently leaving the value as 0.

![image](https://cloud.githubusercontent.com/assets/16919898/12987291/69ffa90c-d0c9-11e5-809f-09caf6d1a3c4.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by cstevenson1** [comment]
Calculation for Round Pipe should not require Height and Width. It should be based on width alone since Height is not filled out on a round pipe. 

Can we have the order of height and width switched in the form? We would like Width to come first and then Height.

Calculation does not work for arch pipes. If we supplied a spreadsheet with cross sectional areas for our standard sizes, could it be used to populate the Cross Sectional Area field?

![image](https://cloud.githubusercontent.com/assets/16919898/15331693/85d051ce-1c30-11e6-9292-743f7e58f8a6.png)

**Comment by leeensminger** [comment]
@kanglu666 as discussed, we will:

- Disable Height field when Shape = Round
- Switch Height field and Width field

**Comment by leeensminger** [comment]
@cstevenson1 Can you please provide the spreadsheet?

**Comment by leeensminger** [comment]
Arch Sizes: http://culvertdesign.com/standard-pipe-arch-sizes/

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1 release
