### ISSUE TITLE
BMP Inventory Tab

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#71]
![bmp form is not organized by parameters](https://cloud.githubusercontent.com/assets/16919984/12987452/1eb25732-d0ca-11e5-9272-9e3ccd067d21.JPG)

All BMP Parameters starting with 1. Access - 23. Emergency Spillway should be organized sequentially to match the same order under the Inspection tab.

**Comment by kanglu666** [comment]
![1](https://user-images.githubusercontent.com/6352480/54003290-b2bc7e80-411f-11e9-9a79-6b9de6e8d99e.jpg)

**Comment by kanglu666** [comment]
Scroll bar added, and order updated

**Comment by cstevenson1** [comment]
Parameter order in the inventory tab tab now matches the parameter order in the inspection tab. Please push to prod.

**Comment by leeensminger** [comment]
@kanglu666 please add to prod release when the time comes

**Comment by cstevenson1** [comment]
same as before. confirmed in Dev Field Tool v8.0

@KCI-Ablowers push to prod

**Comment by KCI-Ablowers** [comment]
Confirmed by @cstevenson1 - Push to Prod

**Comment by kanglu666** [comment]
ready in PROD 8.3 release

**Comment by cstevenson1** [comment]
confirmed in prod
