### ISSUE TITLE
Conveyance location tab should have structure location field renamed

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#72]
Within the location tab of the pipe conveyance, there is a field that reads structure location. The field should be renamed to Conveyance Location or if the same form is being used between structures and conveyances then it should be renamed to Feature Location. 

![image](https://cloud.githubusercontent.com/assets/16919898/12987608/ced932c0-d0ca-11e5-8608-9943aee71aec.png)

**Comment by kanglu666** [comment]
updated
