### ISSUE TITLE
Inspection Score

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#73]
![inspection score](https://cloud.githubusercontent.com/assets/16919984/12987524/7c339718-d0ca-11e5-80f8-63ddecc48885.JPG)

Inspection Score, Overall Comments, and Inspection Photos are grayed out even when, "Yes" is selected under the Inventory tab.  This prevents moving forward with the work flow process for a BMP Inspection.

**Comment by leeensminger** [comment]
@mortynsky , the required workflow to enable these fields is as follows:

1. Set the parameter, in Inventory tab, = Yes.
2. Save the BMP (this is key)
3. Re-enter inspection form.

Can you confirm that performing this workflow still results in this bug?  

The known exception to this point is #97 , (downstream embankment is consistently disabled)

**Comment by mortynsky** [comment]
This bug has been resolved except:

The known exception to this point is #97 , (downstream embankment is consistently disabled)
