### ISSUE TITLE
Adding a new Work Area

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#74]
![adding a new work area](https://cloud.githubusercontent.com/assets/16919984/12988362/5c420f08-d0ce-11e5-80c9-c4da2a47a447.JPG)

The attached error occurs when trying to add a New Work Area.  

It prohibits you from moving forward with the process.

**Comment by mortynsky** [comment]
![adding a new work area hardwired](https://cloud.githubusercontent.com/assets/16919984/12988937/04420440-d0d1-11e5-9cee-43f4a910f317.JPG)

When hardwired, only three layer boxes in the TOC come up.  It does not let me draw/add a new work area.

**Comment by leeensminger** [comment]
Resolved with phone call
