### ISSUE TITLE
Supervisor should not be a manual input field

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#75]
Supervisor field for Work Orders should not be a manual input field. It should either be a drop down with the options or automatically be determined based on which District is selected. 

![image](https://cloud.githubusercontent.com/assets/16919958/12988509/19845206-d0cf-11e5-9500-42a1dcc2feeb.png)

**Comment by leeensminger** [comment]
We can provide a dropdown, or automatically populate based on district.  The latter seems to be a better option, to me.  Please confirm.

Can you provide us with the list of Supervisors and their associated District?

**Comment by mortynsky** [comment]
Person	Name	                    Person's Location	                Organization       District
10693	Kelley, Maureen	   AREA 48	                 DELDOT	           North District
39272	Fain, Richard G           AREA45	                 DELDOT	           Canal District
53489	Shaffer, Duwayne A	   AREA21	                 DELDOT	           Central District
106455	Probert, Alastair	   AREA47	                 DELDOT             South District

Note:  This list is subject to change depending on if people move positions, leave, retire, etc.

**Comment by leeensminger** [comment]
Lu, please remove the user-input field, and automatically display a read-only text string, from LU_DISTRICT_SUPERVISORS.NAME, where the District for the active feature matches LU_DISTRICT_SUPERVISORS.DISTRICT.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
