### ISSUE TITLE
Complete Date for Work Orders should not be populated initially

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#76]
This Completed Date for work orders should not be populated when the work order is initially created. It should be populated when DelDOT notifies KCI that the work order was completed.

![image](https://cloud.githubusercontent.com/assets/16919958/12988678/cc9f7b5e-d0cf-11e5-8499-e49548514336.png)

**Comment by leeensminger** [comment]
See also #77

**Comment by kanglu666** [comment]
updated, ready for testing in next release
