### ISSUE TITLE
Submitted Date for Work Orders should not be populated initially

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#77]
This Submitted Date for work orders should not be populated when the work order is initially created. It should be populated when KCI submits the batch of work orders to DelDOT.

![image](https://cloud.githubusercontent.com/assets/16919958/12988752/34b8e2a2-d0d0-11e5-98c3-b247744b8351.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
