### ISSUE TITLE
Need ability to attach photo to pipe connection points

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#78]
Points with structure type=pipe connection need ability to attach photos. It appears that all photos are attached through the inspection tab and the inspection tab for pipe connection is blank.

![image](https://cloud.githubusercontent.com/assets/16919898/12988813/90a390d0-d0d0-11e5-86d5-217de0bcf987.png)

**Comment by leeensminger** [comment]
Pipe Connections intentionally do not have inspections, as per my notes of our conversations in the past.  Can you confirm that is still accurate?

My understanding is that Pipe Connections are underground and not visible.  Is that true?  If yes, is it necessary to associate a photo for this feature?

**Comment by cstevenson1** [comment]
After discussion, we have decided this is not an issue. We can attach the photo to the DelDOT conveyance that it is tying into. To accommodate this update, we will need to add a domain value to photo category of PIPE CONNECTION. This would give us the option of labeling a photo as upstream, downstream, or a pipe connection for conveyances. Below is an example of a pipe connection photo.  

![image](https://cloud.githubusercontent.com/assets/16919898/13059485/693ef996-d3f8-11e5-9abc-aeba2ecb332a.png)

![image](https://cloud.githubusercontent.com/assets/16919898/13059478/5d7bb680-d3f8-11e5-817c-404ff8e6a745.png)
