### ISSUE TITLE
Error message for deleting a photo that carried over from the previous inspection 

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#79]
I received the following pop up message after trying to delete a photo that had carried over to my new inspection from the previous one I had created. The photo did delete after hitting OK in the pop up box. 

![image](https://cloud.githubusercontent.com/assets/16919898/13007496/be9bc4ce-d15e-11e5-89bb-de3f3205c44a.png)

**Comment by kanglu666** [comment]
updated with fix issue #3
