### ISSUE TITLE
Incorrect Domain Values in Geographic Filters

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#8]
Subdivision and Watershed have the same incorrect domain values in the Selections tab. The values appear to be the feature types.

![image](https://cloud.githubusercontent.com/assets/16919898/12678342/3c01fb8e-c66c-11e5-9496-29b936425f4b.png)

**Comment by leeensminger** [comment]
Selection filters are pulling from the feature layer list.  Please update to implement Communities base layer and 8 digit watershed base layer.

**Comment by kanglu666** [comment]
fixed, ready for testing in next release

**Comment by cstevenson1** [comment]
No longer appears to be pulling from feature layer list but Watershed should not have been replaced with Watershed HUC8. 

![image](https://cloud.githubusercontent.com/assets/16919898/13928470/2afb3b4c-ef6c-11e5-80d0-8d47a5bf0462.png)

**Comment by leeensminger** [comment]
Replace HUC8 in the Geographic Filter with the original DNREC_Watersheds layer.

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release
