### ISSUE TITLE
Structure and Conveyance #'s

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#80]
It appears that the structure and conveyance #'s are being generated based on date and time rather than the agreed upon logic that includes the location (i.e. county and maintenance area).

![image](https://cloud.githubusercontent.com/assets/16919958/13008558/f1a0b5ea-d164-11e5-986a-db51e2ecf885.png)

**Comment by kanglu666** [comment]
Please provide the logic, and we may need to discuss it

**Comment by leeensminger** [comment]
Format is (2 digit County code  + 2 digit Maintenance area + 6 digit unique Number)-
Use the following logic to populate the STRUCTURE NUMBER:
County Values-
•	New Castle = 01
•	Kent = 02
•	Sussex = 03
Maintenance Values
•	Laurel =01
•	Seaford = 02
•	Ellendale = 03
•	Gravel Hill = 04
•	Dagsboro = 05
•	Harrington = 06
•	Magnolia = 07
•	Cheswold = 08
•	Middletown = 09
•	Bear = 10
•	Kiamensi = 11
•	Talley = 12
Unique Number
•	Add consecutive unique numbers for each structure starting at “000001”

**Comment by kanglu666** [comment]
county number and maintenance number applied to new structure and conveyance #.

As discussed: the last six digit begin with "000001", will be processed by a GP service daily, user need to check in their data for gp service to update the Structure # and Conveyance # every night, then user need to do the sync each time before they go out field.

**Comment by kanglu666** [comment]
Nightly Geo-process script has been developed to do this job, ready fir testing in version 1.0 release

**Comment by mjuber-kci** [comment]
It does not appears that the structure numbering in the app is functioning correctly. The structures and conveyances I have created are in New Castle County in the Bear Maintenance area and all of their structure IDs are 02010 which would equate to Kent County in the Laurel Maintenance area. 

![image](https://cloud.githubusercontent.com/assets/16919958/15079483/c53debd0-1386-11e6-9e8a-653207ee9561.png)


Will features at least have a unique temporary ID until they are officially assigned an ID at night?

**Comment by kanglu666** [comment]
All temporary numbers (Conveyance #) should be a 4 digit number: county number + maintenance area #. the one shows here has an extra number 0 in the middle that cause the issue. 
updated, ready for testing in version 1.1 release

**Comment by mjuber-kci** [comment]
The temporary numbers still appear to be wrong. I created a structure and a conveyance in New Castle County in the Kiamensi Maintenance Area and the temporary number assigned was 0211.  It appears that New Castle County was assigned 02 instead of 01. 

County Values Should Be-
**• New Castle = 01**
• Kent = 02
• Sussex = 03

![image](https://cloud.githubusercontent.com/assets/16919958/16687332/022a2aa0-44e6-11e6-94fc-6adee5bc4c65.png)

**Comment by kanglu666** [comment]
from the basemap .mpk county layer:
Kent = 01
New Castle = 02
Sussex = 03

**Comment by leeensminger** [comment]
@kanglu666 changed in mpk to show correct values:

M:\2014\17141728.A\GIS\BaseData\Base_Data_Package\MPKs\BaseData_2_LargePolygons.mpk

**Comment by kanglu666** [comment]
Basemap mpk updated, ready for testing in version 1.3 release.

Note: Create the new  BaseData_1_Primary.mpk and BaseData_2_LargePolygons.mpk
