### ISSUE TITLE
BMP Inspection Form Window

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#81]
The BMP Inspection form window that pops up is scrollable on the Toughbook.  Can the form be fitted to the toughbook so that the arrow bar Up/Down and Side/Side be eliminated?  This may or may not be applicable to other form windows for structures, conveyances, etc., but was noticed under the BMP Inspection form.

![form is scrollable](https://cloud.githubusercontent.com/assets/16919984/13008732/17fa12c6-d166-11e5-8647-a54ff515e991.JPG)

**Comment by cstevenson1** [comment]
since we are using different devices now there is no longer a need for this fix
