### ISSUE TITLE
Conveyance and Structure location tab should have refresh button

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#82]
The refresh button for the overlays in the location tab is present for BMPs but missing for structures and conveyances. 

![image](https://cloud.githubusercontent.com/assets/16919898/13009263/870274ee-d169-11e5-9c88-edcb68b9bb1f.png)

![image](https://cloud.githubusercontent.com/assets/16919898/13009238/63184ad6-d169-11e5-96b0-59000c7e8ee5.png)

![image](https://cloud.githubusercontent.com/assets/16919898/13008727/0ab0cff6-d166-11e5-85d3-d50cc51fa32f.png)

**Comment by leeensminger** [comment]
add checkbox for County, District, Maint Area.  Also include this functionality in PID Points.

**Comment by leeensminger** [comment]
Clicking Refresh will automatically perform the overlay for the checked boxes.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
