### ISSUE TITLE
BMP Action Items Form

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#83]
When assigning an, "Action Type" to a BMP parameter the, "Action" drop down box displays all of the possible actions for all possible "Action Types".  Can the "Action" drop down box filter out only the Actions that pertain to the Action Type selected?  This is how the current application function and will greatly save time and reduce errors generated in the field.  Thanks!

![bmp action form](https://cloud.githubusercontent.com/assets/16919984/13009578/2ca2065c-d16b-11e5-9802-a5afb62a07ae.JPG)

**Comment by leeensminger** [comment]
@mortynsky Can you update this Excel with the values?  We just need the Action Type, for each Action.  

[BMP_Action_Groups.xlsx](https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/files/153692/BMP_Action_Groups.xlsx)

**Comment by mortynsky** [comment]
Please see the attached, .xlsx document with the updated Action Types for each Action.

[Copy of BMP_Action_Groups.xlsx](https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/files/161435/Copy.of.BMP_Action_Groups.xlsx)

Please note:

1. "rip-rap" was changed to "riprap"
2. Not Required does not fall into any Action_Type

Thanks,

Matt

**Comment by leeensminger** [comment]
updated in database

**Comment by kanglu666** [comment]
1: "rip-rap" was changed to "riprap": NOT UPDATED in DATABASE.
2: NEED a LOOK UP Table in Database.
 i will leave this as enhancement for next development

**Comment by mortynsky** [comment]
Issue still not fixed.

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1 release

**Comment by mortynsky** [comment]
This issue has been fixed!
