### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#84]
We know this was a known issue but the delete button does not function. 

![image](https://cloud.githubusercontent.com/assets/16919898/13009803/774a9f9c-d16c-11e5-8709-dbf3f2ecd2d2.png)

**Comment by leeensminger** [comment]
@kanglu666 please confirm this has been updated and ready for testing at next release.  update label as necessary.

**Comment by kanglu666** [comment]
ready for testing in next release
