### ISSUE TITLE
Sample Error

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#85]
A "Sample Error" saying, "Sample Exception: Abort due to constraint violation :" pops up when you have not filled out all required fields necessary under the Location and Inventory tab so you can move forward to the Inspection tab.  Can this error say something like, "Required fields need to be filled out before moving forward"?  Or maybe highlight in Red or make what fields are still required stand out, similar to what happens on a website when you fill out a form but did not fill in all of the necessary information to save or move on?  Just a thought.

![required field](https://cloud.githubusercontent.com/assets/16919984/13009891/e0bad640-d16c-11e5-8263-dfd3691429c4.JPG)

**Comment by leeensminger** [comment]
The text for errors has been updated.  

Lu, double check.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by mortynsky** [comment]
This issue does not look to have been addressed!

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.0 release

**Comment by mortynsky** [comment]
This issue is fixed!  Now the word, "Inventory" is misspelled.

![inventory misspelled](https://cloud.githubusercontent.com/assets/16919984/15191168/6dc74f82-1781-11e6-99c0-91ea9bc6b46a.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.1 release

**Comment by mortynsky** [comment]
The word "location" needs to have a capital "L".

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.3 release

**Comment by mortynsky** [comment]
This issue has been fixed!  Thanks
