### ISSUE TITLE
Add score to BMP Invasive Species Summary Box

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#86]
Can you add a, "Score" Column to the BMP Invasive Species Summary Box?

![add score to invasive summary box](https://cloud.githubusercontent.com/assets/16919984/13009991/7a5d0e8a-d16d-11e5-96d2-4bbb587c9573.JPG)

**Comment by cstevenson1** [comment]
fix is no longer necessary
