### ISSUE TITLE
BMP Location Tab "Select All" Box

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#87]
The BMP Location tab, "Select All" box does not appear to work.  One thing to note is that other users were able to get this box to work under the first BMP created after installing the application.  After a second BMP is created this box does not work.

![bmp location tab](https://cloud.githubusercontent.com/assets/16919984/13010194/a3b33a42-d16e-11e5-9194-ce355da10fde.JPG)

**Comment by kanglu666** [comment]
updated, select all checkbox applied to Sturecture , BMP and Conveyance feature.
ready for testing in next release

**Comment by mortynsky** [comment]
This issue has been fixed!
