### ISSUE TITLE
Duplicate BMPs Created

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#88]
After saving a New BMP two BMPs are generated with the same ID.

![dupliate bmp created](https://cloud.githubusercontent.com/assets/16919984/13010915/50f56c36-d172-11e5-97a6-8a7c4775619c.JPG)

**Comment by kanglu666** [comment]
fixed, the ID field for BMP list is actually the BMP_NUM field.
we also need to discuss the BMP_NUM value.

**Comment by mortynsky** [comment]
This issue has been fixed!
