### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#89]
The application crashes if you double click on a row in the BMP Invasive Species Summary Table!

![crash](https://cloud.githubusercontent.com/assets/16919984/13011211/b3d4ea2e-d173-11e5-8d2a-7395260263fa.JPG)

**Comment by kanglu666** [comment]
nothing wrong on my part, please test in next release.

**Comment by kanglu666** [comment]
ready for testing in next release

**Comment by mortynsky** [comment]
This issue is not fixed.  It has to be row 2 or lower.

**Comment by kanglu666** [comment]
not sure what the issue is, it's working correctly on my side.
Please test in version 1.1 release. if the issue still happen, we can work together to figure out.

**Comment by mortynsky** [comment]
This issue still occurs if you double click on the second or lower row in the BMP Invasive Species Summary Table.  This may not be that big of a deal or worth the time to fix.

**Comment by kanglu666** [comment]
working fine on my side, not sure what the issue is. 
let's schedule a screen share we can check out what wrong

**Comment by leeensminger** [comment]
in screenshare, determined that the Invasive comment is causing an error when user inputs no comment text..

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.3 release

**Comment by mortynsky** [comment]
This issues has been fixed!  Thanks
