### ISSUE TITLE
Incorrect Outfall Component Material

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#9]
The domain values for all of the outfall components are incorrect. It appears to be using the Pipe Material domain values.

![image](https://cloud.githubusercontent.com/assets/16919958/12678629/b5ed63ce-c66d-11e5-9acf-ea085b6346fb.png)

**Comment by kanglu666** [comment]
all the domain values directly pulled from the database. if the domain values are wrong, please check the database.

**Comment by mjuber-kci** [comment]
There are separate domain values for Pipe Material and Outfall Component Material. The Outfall Component Material domain values are listed below: 
![image](https://cloud.githubusercontent.com/assets/16919958/13363637/6487a8a0-dc98-11e5-9af8-f3ba52561107.png)

**Comment by leeensminger** [comment]
pending database reload by BC..

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by mjuber-kci** [comment]
Defined Outfall Channel Material and Undefined Outfall Channel Material need to have the domain values listed above as well.

**Comment by leeensminger** [comment]
updated in DB, ready after BC loads
