### ISSUE TITLE
New Barrel Conveyance feature displays barrels previously created

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#90]
I created a Barrel Conveyance with 3 barrels and everything worked normally (circled in blue). I closed out of the barrel conveyance and began creating a new barrel conveyance with the conveyance circled in green.  However as soon as the Barrels/Conveyances form opened, it automatically showed the three barrels I created in the previous Barrel Conveyance (circled in red).

![image](https://cloud.githubusercontent.com/assets/16919958/13011717/1cf02332-d176-11e5-876e-7594c9796083.png)

**Comment by leeensminger** [comment]
Reference similar issue #39

**Comment by kanglu666** [comment]
fixed, ready for testing in next release
