### ISSUE TITLE
Adding a New BMP

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#92]
After adding a new BMP the form that pops up is the last form you were working on after closing out of a your previous BMP.  In this example the inspection of the previous BMP was active which is completely unrelated to the BMP I am currently creating/working in.  After saving and closing an inspection the inspection form should be closed unless the user navigates and opens for the form.  When creating a new BMP a blank Location tab should be what comes up related to that new BMP created.  All other forms should be set back to default and closed out.  I ran into this problem while adding a BMP but I think this happens across the board with Structured and Conveyances as well.

![adding a new bmp](https://cloud.githubusercontent.com/assets/16919984/13012262/84875d74-d178-11e5-8be8-42967fb56dac.JPG)

![adding a new bmp 2](https://cloud.githubusercontent.com/assets/16919984/13012272/8e4812e0-d178-11e5-9eab-c31aecd05644.JPG)

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by mortynsky** [comment]
To me this issue does not appear to be fixed.

**Comment by kanglu666** [comment]
updated, ready for testing in next release

**Comment by mortynsky** [comment]
This issue has been fixed!
