### ISSUE TITLE
Multiple BMP records for same geometry (Polygon)

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#94]
When creating a new BMP and you are filling information under the "DelDOT BMP Number" domain if you hit the, "Save" Icon it will generate a BMP record each time you hit the icon.  Therefore you can end up with multiple records for the same geometry.

1.
![bmp number creating multiple bmp records for same polygon](https://cloud.githubusercontent.com/assets/16919984/13014215/bf057a3c-d180-11e5-93eb-dc51a285e99f.JPG)

2.
![bmp number creating multiple bmp records for same polygon 2](https://cloud.githubusercontent.com/assets/16919984/13014223/c547ef60-d180-11e5-92fb-e2200070537a.JPG)

**Comment by kanglu666** [comment]
fixed, this issue is related to #88 , ready for testing in next release

**Comment by mortynsky** [comment]
This issue has been fixed!
