### ISSUE TITLE
Saving a Structure Misspelling

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#95]
When you try and save a structure but do not have all the required fields filled in you get the following error: "All requied fields in inventery section must have value" and it should read, " All required fields in the inventory section must have a valid value".  If these changes cannot occur required and inventory need to be spelled correctly.

![inventory misspelling](https://cloud.githubusercontent.com/assets/16919984/13015346/82b09016-d186-11e5-9fd6-080a5d7c748d.JPG)

**Comment by kanglu666** [comment]
updated

**Comment by mortynsky** [comment]
Issue has been resolved.
