### ISSUE TITLE
Outfall Component Inspection

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#96]
The Check box for "Rate Components bu Overall Rating" is not functional. Also, it should be "by", not "bu".

![image](https://cloud.githubusercontent.com/assets/16919958/13016590/a8d20070-d18d-11e5-9833-9eef8aa1048e.png)

**Comment by kanglu666** [comment]
check boxes in Outfall Component Inspection have been removed

**Comment by leeensminger** [comment]
@kanglu666 can you reinstate the checkbox only for "Rate components by Overall Rating".

When this checkbox is toggled off AND all component dropdown menus are enabled AND Inspected = Yes:

1. System prevents user from editing Overall Rating
2. User updates component dropdown menus (defined outfall channel condition, bed erosion, etc.)
3. System automatically populates Overall Rating = LOWEST Component Rating that the user applies

When this checkbox is toggled on AND all component dropdown menus are enabled AND Inspected = Yes:
1. System prevents user from editing Component inspection values
2. User updates Overall Rating
3. System automatically populates all component inspection values = the Overall Rating

**Comment by cstevenson1** [comment]
no fix needed at this time
