### ISSUE TITLE
BMP Inventory/InspectionTab

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#97]
When you select, "Yes" for all BMP Inspection parameters under the, "Inventory" tab, "Downstream Embankment Cover" is still grayed out.  

1.
![all invenotry selected yes](https://cloud.githubusercontent.com/assets/16919984/13016813/04f46586-d18f-11e5-9b34-07d75086fc60.JPG)

2.
![all invenotry selected yes downstream embankment grayed out](https://cloud.githubusercontent.com/assets/16919984/13016815/0d228dbe-d18f-11e5-8990-1b6ef2d4117b.JPG)

**Comment by kanglu666** [comment]
fixed, ready for testing in next release

**Comment by mortynsky** [comment]
Issue has been resolved.
