### ISSUE TITLE
BMP Inventory Tab

### ISSUE THREAD

**Issue by mortynsky** [leeensminger/DelDOT-NPDES-Field-Tool#98]
Can the drop down boxes for the 24 parameters be check boxes?  If the box is checked that means YES, if the box is not checked that means NO.  Can they be numbered 1 - 24 in the correct order?

![bmp inventory tab](https://cloud.githubusercontent.com/assets/16919984/13017376/dcfab3de-d191-11e5-8ae9-615155bd86e7.JPG)

**Comment by cstevenson1** [comment]
minimal value, closing bug
