### ISSUE TITLE
Selecting pipe to add to barrel conveyance

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#99]
Can we break step 1 for selecting pipes to add to a barrel conveyance into two steps to make the directions more clear and user friendly?
Ex: 1. Click here to begin
      2. Select conveyance pipes from map
      3. Choose one pipe from the list below

![image](https://cloud.githubusercontent.com/assets/16919898/13016619/e71124ec-d18d-11e5-99b0-39b354bbb4ac.png)

**Comment by kanglu666** [comment]
updated, ready for testing in next release
